### ISSUE TITLE
BkgErrGODAS does not work with 4DEnVAR

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#1003]
The `BkgErrGODAS` variable change is not working right for `4D-Ens-Var`, it's creating crazy increments (The ensemble portion of 4denvar is working correctly, and the other variable changes seem to be fine)

As a comparison, here are the SST increments for:

3DVAR
![image](https://github.com/JCSDA-internal/soca/assets/12516201/59413966-35bb-4a4d-bf15-0a96a77d3fde)

4DEnVar, with pure static, `BkgErrGODAS` commented out
![image](https://github.com/JCSDA-internal/soca/assets/12516201/ffb80801-2b72-4ad2-ac34-5fe991825463)

and the same as above, but with `BkgErrGODAS` turned on (the range actually goes from -30 to 30 !)
![image](https://github.com/JCSDA-internal/soca/assets/12516201/d25fe933-7a61-4f1f-bb3a-dc79117545b6)

**Comment by travissluka** [comment]
@shlyaeva @ncrossette I haven't started looking into the code yet (I'm sure it's something wrong on the SOCA side) but do you have any quick theories about why a linear variable change would break like that with `4D-Ens-Var`

**Comment by shlyaeva** [comment]
Can you point us to a yaml you use?

**Comment by travissluka** [comment]
> Can you point us to a yaml you use?

@shlyaeva I'm actually testing now with `EXPLICIT_DIFFUSION` instead, but it's otherwise essentially the same as this file https://github.com/JCSDA-internal/soca-science/blob/96028d63444a07f8a018163638e497f1f89a0347/configs/soca/soca_4dhyb.yaml#L65

**Comment by travissluka** [comment]
note to self: I've been meaning to rewrite `BkgErrGODAS` as a generic saber outer block, it might be a good time now to do that. (and while at it, add in the option to save what the the calculated parametric stddev is, for debugging purposes)

**Comment by shlyaeva** [comment]
@travissluka so is it fully ensemble, with `BkgErrGODAS` around the ensemble covariance?

**Comment by travissluka** [comment]
noting there that my images were captioned wrong. the 4denvar is running with **pure static B** for hybrid covariance in the images shown

**Comment by travissluka** [comment]
ok, so after poking around, I don't think this is actually an issue with `BgkErrGODAS` but rather the way the time parallel part of 4denvar is implemented

here is 4denvar with pure static B, on the left is with `parallel subwindows: false` (broken), and with `parallel subwindows: true` on the right (looks right!)
![image](https://github.com/JCSDA-internal/soca/assets/12516201/9c0db565-e403-4a09-9579-baf563d16e41)

interestingly with `parallel subwindows: true` I am getting a whole bunch of warnings that look like the following (not sure if this is actually a problem though, probably not?):
```
FieldSet3D::deserialize: valid times are different.                                                    
This FieldSet3D valid time: 2021-06-30T00:00:00Z                                                       
Valid time of the serialized FieldSet3D: 2021-07-01T00:00:00Z
FieldSet3D::deserialize: valid times are different.                                                    
This FieldSet3D valid time: 2021-06-30T00:00:00Z                                                       
Valid time of the serialized FieldSet3D: 2021-07-01T00:00:00Z                                          
FieldSet3D::deserialize: valid times are different.                                                    
This FieldSet3D valid time: 2021-06-30T00:00:00Z                                                       
Valid time of the serialized FieldSet3D: 2021-07-01T00:00:00Z
```

@shlyaeva given this, I can't think of any reason why the problem would be on the soca side, should I move this issue to oops?

**Comment by shlyaeva** [comment]
yes, go ahead and move to oops please

**Comment by travissluka** [comment]
I moved this issue to oops. Since there is a valid workaround of using `parallel subwindows: true` and a carefully set number of PEs, this shouldn't impede our work with 4denvar.
