### ISSUE TITLE
update for oops PR, Update the UnstructuredInterpolator's geometric algorithms

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#1009]
make sure soca is up to date with upstream PR 
- https://github.com/JCSDA-internal/oops/pull/2532#event-11612220828

bonus points for actually testing it with the global 1/4 deg

**Comment by fmahebert** [comment]
> bonus points for actually testing it with the global 1/4 deg

A test with a regional domain may be good to run as well, just to be sure I didn't break anything at regional domain edges...?
