### ISSUE TITLE
ML based balance

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#1014]
## Description
Develop an ML based balance operator as a saber outer block, I think that's what it should be, could you confirm @travissluka and/or @shlyaeva ?

Hard to tell yet in how many steps I will do this work, but the initial goal is to call pre-trained AI balance emulators (developed in the `daml` repo) from within `soca`. I'll add a training option later on.

## Help!
Build `libtorch` as part of the containers and on HPC. Help with this would be nice, the `gnu` version is easy to build, but I couldn't figure out how to build with intel.

**Comment by shlyaeva** [comment]
Yes, I think this should be a saber outer block. If you have any questions on interfaces for saber blocks or related, let me know!

**Comment by travissluka** [comment]
unfortunately, searching https://packages.spack.io/ it seems that `py-torch` is available, but not the C++ api

**Comment by guillaumevernieres** [comment]
> unfortunately, searching https://packages.spack.io/ it seems that `py-torch` is available, but not the C++ api

I guess we'll stick with `gnu` for now then. Thanks for checking @travissluka .
