### ISSUE TITLE
Something is wrong in the minimization: The analysis "over-shoots" the obs

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#1018]
## Description
I simplified **B** to be the identity, using the id saber central block, simplified the obs filtering, tried different cost function but I see the same issue:
When only assimilating ice concentration, the analysis goes out of the [0, 1] bounds. This should not happen with the simple configuration described above.

### To Reproduce:
Here's a scratch with all the needed files to run soca:
```/work/noaa/da/gvernier/ai/runs/da-test/gdastest```
run the `var.x`
the bkg `cicen` and obs are between [0, 1] but the analysis is not.

**Comment by travissluka** [comment]
how far outside 0, 1 are we talking about? Also, have you looked at the `hofx1` values, are those outside [0,1] ?

I'm by no means a var expert (very far from it in fact) but wouldn't we expect analysis values outside the obs values for any type of interpolation other than nearest neighbor? For example, suppose you have an observation of 1.0 that lies exactly between two grid points. Those grid points have values of 0.0 and 1.0, so the interpolated hofx is 0.5. This means there should be a positive increment, which when interpolated back to the grid would make that grid point currently 1.0 go above 1.0.

**Comment by shlyaeva** [comment]
I can look into this too next Tue/Wed; I'll check in then.

**Comment by guillaumevernieres** [comment]
> how far outside 0, 1 are we talking about? Also, have you looked at the `hofx1` values, are those outside [0,1] ?
> 
> I'm by no means a var expert (very far from it in fact) but wouldn't we expect analysis values outside the obs values for any type of interpolation other than nearest neighbor? For example, suppose you have an observation of 1.0 that lies exactly between two grid points. Those grid points have values of 0.0 and 1.0, so the interpolated hofx is 0.5. This means there should be a positive increment, which when interpolated back to the grid would make that grid point currently 1.0 go above 1.0.

I'm talking about the h(x) for the analysis that is out of bounds @travissluka . But yes, maybe I'm freaking out for nothing, if the obs are dense enough and the interpolation stencils overlaps, then maybe that's the expected scenario. Don't spend too much time on this, I was doing 3 things at the same time yesterday, that never goes well ... I'll try to run a test with fewer obs.

**Comment by guillaumevernieres** [comment]
closing this, most of this issue is related to the specification of the bkg error. User issue, I don't think it's a bug.

**Comment by shlyaeva** [comment]
> User issue, I don't think it's a bug.

Great!

> I can look into this too next Tue/Wed; I'll check in then.

Ha, that never happened, did it? oops.

**Comment by guillaumevernieres** [comment]
> > User issue, I don't think it's a bug.
> 
> Great!
> 
> > I can look into this too next Tue/Wed; I'll check in then.
> 
> Ha, that never happened, did it? oops.

I've got a buffer of ~2 weeks, you can pretend it happened.
