### ISSUE TITLE
Delete MOM6 model forecast from SOCA

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#1023]
I just want to make sure I'm not crazy before doing this, but the way I see it, the model class shouldn't live in soca:

1) We don't run in core right now, we do everything with the pseudo model, it'll stay that way for the foreseeable future.
2) In the distant future (i.e. not this year) when we want to do things in-core, we'll never run MOM6 by itself, an ocean model is not very useful without an atmospheric coupler to calculate the fluxes, so we would always be running some type of coupled model (MOM6SIS2, UFS S2S, UFS NGGODAS, GEOS, ..etc) each of which compile and interface differently. I like @shlyaeva 's idea of having the coupled model classes living outside of fv3/soca repos,

This will help us now with compiling soca with the ufs-bundle. And, if later when we go to do in-core it turns out that I'm wrong, we can just put the model forecast back into soca.

(I suppose I could make an exception and let @guillaumevernieres add an AI-based forecast model  for sea-ice that lives in soca)

thoughts? @guillaumevernieres @shlyaeva @kbhargava @climbfuji

**Comment by shlyaeva** [comment]
Looks reasonable to my non-soca-expert eye.

**Comment by kbhargava** [comment]
I vote for it. 👍🏽

**Comment by guillaumevernieres** [comment]
Sounds good to me as well @travissluka .
