### ISSUE TITLE
compare.sh tests failing on different machines

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#103]
Tests relying on compare.sh are not bit reproducible and so are failing on some machines. Several things need to be looked at

1. I think there are still some bugs hidden in the code. E.g I should not be getting completely different answers in `soca_test_increment` depending on whether i run in Release or Debug
2. compiler flags for optimization and math model choice should be played with. Intel compilers are especially notorious for changing answers with some of the default optimization settings.
3. Add tolerances to the compare.sh script

**Comment by travissluka** [comment]
@aerorahul can you send me a copy of the `soca/test/testoutput/*.test.test.out` files you are getting? I'd like to see just how far off we currently are.

**Comment by aerorahul** [comment]
@travissluka ok. Working on it right now. Will send both Intel 17, GCC7.3 on discover and Mac (outside container)

**Comment by aerorahul** [comment]
Contains testoutput files.
[soca-test.tar.gz](https://github.com/JCSDA/soca/files/3121919/soca-test.tar.gz)

**Comment by travissluka** [comment]
* item 1 should be resolved now
* on to item 2. @aerorahul can you give me the output you get from running `gcc -Q --help=target` on both your mac and discover. This should tell me what architecture specific instructions gcc is using by default, some of these features are guaranteed to change answers. 
* Depending on what we find we can have you add compiler flags to get your answers closer to the baseline ctest answers, and whatever else can't be accounted for can be handled by adding in tolerances to the compare.sh script.

**Comment by aerorahul** [comment]
@travissluka Thanks for digging into identifying baseline compiler flags.  I was under the impression that the compiler flags provided via `ecbuild` and `CMakeLists.txt` would supersede these.
[gcc.discover.txt](https://github.com/JCSDA/soca/files/3132640/gcc.discover.txt)
[gcc.macOS.txt](https://github.com/JCSDA/soca/files/3132641/gcc.macOS.txt)

**Comment by travissluka** [comment]
@aerorahul FYI the discover settings are standard linux settings, the mac settings have a slight difference, but nothing that should significantly change answers, especially if cmake is set to compile in `RelWithDebInfo` instead of `Release`. Nothing nearly as bad as Gaea's default settings, which use a completely different math model (`387` instead of the normal `sse` used in `-mfpmath=`)

So, anyway, I'm on to step 3, adding tolerances to `compare.sh`

**Comment by guillaumevernieres** [comment]
:+1:  
@travissluka , Sounds good to me. We have the same issues on Theia.

**Comment by aerorahul** [comment]
@travissluka what bothers me is tests in all other bundles pass with identical results.  It must be something in SOCA. I am guessing some compiler flag or the mixed use of real, kind_real, real(8), but can’t put a finger on it just quite.
