### ISSUE TITLE
mom6 grid is different in soca and r2d2 data

### ISSUE THREAD

**Issue by HamidehGMAO** [JCSDA-internal/soca#1055]
## Description

mom6's data grid is different in soca and r2d2. Looking at the MOM.res.nc file in here https://github.com/JCSDA-internal/soca/tree/develop/test/Data/72x35x25,  the longitude is between -280 and 80 
<img width="931" alt="image" src="https://github.com/JCSDA-internal/soca/assets/40796921/f47a3a37-5218-41d4-8a17-94394761ae1b">

while looking the the mom6 data in r2d2, Longitude is between -300 and 60
<img width="1046" alt="image" src="https://github.com/JCSDA-internal/soca/assets/40796921/1bb2006e-1e7d-4568-aaab-38cd1c767961">

because NOBM data's longitude is between -280 and 80, we have a bug in oasim hofx results.

**Comment by travissluka** [comment]
@HamidehGMAO FYI, when remapping you'll want to use the `lon` and `lat` variables from 
`/discover/nobackup/projects/jcsda/s2127/static/skylab-8.0.0/soca/025deg/soca_gridspec.nc` and `/discover/nobackup/projects/jcsda/s2127/static/skylab-8.0.0/soca/5deg/soca_gridspec.nc`

**Comment by HamidehGMAO** [comment]
I see! Thanks @travissluka.
