### ISSUE TITLE
Populate the State and Increment resolution change stubs using the oops GlobalInterpolator

### ISSUE THREAD

**Issue by fmahebert** [JCSDA-internal/soca#1064]
## Description

In SOCA, the State and Increment constructors that do a resolution change are stubs with no implementation:
- https://github.com/JCSDA-internal/soca/blob/f71c8466375e4045087ff11119004852bc61f3c4/src/soca/State/soca_state_mod.F90#L131
- https://github.com/JCSDA-internal/soca/blob/f71c8466375e4045087ff11119004852bc61f3c4/src/soca/Increment/soca_increment_mod.F90#L192

It should now be possible to fill in this code using the `oops::GlobalInterpolator`, as was done for fv3-jedi and mpas-jedi.

## Solution

From `State.cc` and `Increment.cc`, set up and use the `oops::GlobalInterpolator` to change the resolution of the State/Increment. Follow the example from fv3-jedi and mpas-jedi:
- https://github.com/JCSDA-internal/fv3-jedi/pull/1243
- https://github.com/JCSDA-internal/mpas-jedi/pull/1002

## Alternatives

Write SOCA-specific interpolator (and add many more lines of code to SOCA 😬 )

**Comment by travissluka** [comment]
@fmahebert I plan to start adding this in this week. I'll let you know if I run into any problems.
