### ISSUE TITLE
Clean up existing aggregated sea-ice variables

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#1087]
## Description

The variables 
- `sea_ice_category_area_fraction`
- `sea_ice_category_thickness`
- `sea_ice_category_snow_thickness`

don't contain category information anymore, they are all aggregated.

- update the variable names to reflect this (i.e. `sea_ice_area_fraction`)
- change places in the soca code that try to aggregate across the 3rd dimension to assume instead they are 2D
- deprecate the sea ice concentration operator in UFO (use Identity instead)
- update the sea ice thickness operator in UFO

I want to clean up the existing aggregated variables before adding the category variables in https://github.com/JCSDA-internal/soca/pull/1062

**Comment by guillaumevernieres** [comment]
We definitely want to keep the "category" variable name for when we start using the 3D variable as controls instead of the aggregate. 
We should not deprecate the ufo's that use the variables with categories, at least not until we refactor them as a change of variable, but I'm not sure why we would do this if they already exist in ufo.

**Comment by travissluka** [comment]
I thought we had decided that all categories are to be stored in separate variables (i.e. `sea_ice_category1_area_fraction`) for consistency with the thermo variables that have levels and **need** to be split into separate variables. In that case, there is no need for a distinct 3D `sea_ice_category_area_fraction` variable. I don't want multiple variables storing the same information.

Only the aggregated variables should be passed to UFO, it's more efficient to have the variable change on the model interface side. Otherwise extra interpolations are performed for each category (probably doesn't amount to much extra cost in reality, but it adds up)

**Comment by guillaumevernieres** [comment]
Arg, yes, ignore my comment above for the category stuff. For the UFO's, I doubt I'll have time to play with these anytime soon, so  maybe you can ignore too!

**Comment by travissluka** [comment]
do you use the ice thickness operator in ufo at EMC? It's in the  ctests for hofx3d, but I've never actually used it in the real world. So if you don't actually use it, I'll just comment it out from the hofx3d test for now and ignore it.

**Comment by guillaumevernieres** [comment]
> do you use the ice thickness operator in ufo at EMC? It's in the ctests for hofx3d, but I've never actually used it in the real world. So if you don't actually use it, I'll just comment it out from the hofx3d test for now and ignore it.

Not anymore, the latency of the freeboard obs is 1+month for now. Comment away!
