### ISSUE TITLE
remove BkgErrSOCA

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#1089]
## Description

@guillaumevernieres , @Dooruk , do either of you still use the `BkgErrSOCA` linear variable change?

I would like to delete it, as people should instead be using the `StdDev` saber outer block now.

**Comment by Dooruk** [comment]
No, we use `SOCABkgErrFilt` (SABER outer block), `BkgErrGODAS`, `BalanceSOCA`. Should we also switch from `BkgErrGODAS` to `StdDev`?

**Comment by travissluka** [comment]
> No we use `SOCABkgErrFilt` (SABER outer block), `BkgErrGODAS`, `BalanceSOCA`. Should we also switch from `BkgErrGODAS` to `StdDev`?

@Dooruk nope, keep using that! though after https://github.com/JCSDA-internal/soca/pull/1085 it will be renamed to the `ParametricOceanStdDev` saber outer block
