### ISSUE TITLE
reading ice files with categories and levels is broken

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#1092]
## Description

we merged https://github.com/JCSDA-internal/soca/pull/1062 a little too early. oops.

https://github.com/JCSDA-internal/soca/pull/1091 fixes one bug and disables the 3dvar_moreice test so we can get soca back to a working state. The ice thermo variables are not being read correctly because the number of levels is being set to 1 somewhere. The file read results in uninitialized memory (strangely the state norm looks right with gnu, but definitely wrong with intel)

```
51:  icelevs            1
51:  ncat            5
51:  shape of tmp4d          44          43           1           5           2
```

icelevs should be 7. Also, those debug prints should be removed

**Comment by guillaumevernieres** [comment]
FYI @travissluka , I'm ~looking at~ working on this issue today.

**Comment by travissluka** [comment]
@guillaumevernieres FYI, I've noticed you using `continue` in a few places in the code. `continue` doesn't do anything in fortran. What you probably want is `cycle`

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres FYI, I've noticed you using `continue` in a few places in the code. `continue` doesn't do anything in fortran. What you probably want is `cycle`

:man_facepalming: 
same issue with French/English ...
