### ISSUE TITLE
Improve Soca2Cice shuffling

### ISSUE THREAD

**Issue by shlyaeva** [JCSDA-internal/soca#1103]
## Description

The shuffle option in Soca2Cice currently is changing data in place. It means that during the loop through the data we lose info on some of the original cice fields that could have been useful for shuffling.

## Solution
Fix by having a copy of the background to refer to when shuffling.

**Comment by shlyaeva** [comment]
~~I've noticed that sometimes shuffle would shuffle in an ice concentration that's more different from the analysis than the background was. It may be a result of the above (needs checking once it's fixed), but may be worth putting in a safeguard to keep background as is if we can't do better with shuffle.~~
That was incorrect; KD tree finds own point as the closest if there's nothing better around.

**Comment by shlyaeva** [comment]
Code changes in https://github.com/JCSDA-internal/soca/tree/feature/soca2cice_shuffle

**Comment by shlyaeva** [comment]
Some "interesting" results. Note that it's the case of the first cycle where initial background looks fairly far from the obs.
Background:
![Image](https://github.com/user-attachments/assets/b03046a4-1f4e-43e7-885d-2eb6f738f000)

soca analysis (no postprocessing; I am cutting off values outside of [0, 1] when plotting):
![Image](https://github.com/user-attachments/assets/5a5afb26-f389-487f-a3f1-fe814ec3bcca)

analysis after Soca2Cice with shuffle off (currently EMC's default), and ice edge = 0.8. As expected, the analysis looks like background for ice concentrations < 0.8
![Image](https://github.com/user-attachments/assets/89f2fc93-47aa-4370-a755-ff2da5467996)

analysis after Soca2Cice with shuffle on, using develop. Note how much closer it is to unprocessed SOCA analysis for ice concentrations that were < 0.8 in the background.
![Image](https://github.com/user-attachments/assets/e659c041-4a37-46bc-8e88-61cb282456b1)

analysis after Soca2Cice with shuffle on, using the branch suggested in this issue that uses original background for shuffling. The idea was to avoid reusing the same ice profile all the time, but the drawback is that for significant in area ice concentration increments it can't pull close enough to the analysis (at least not on one iteration)
![Image](https://github.com/user-attachments/assets/492a6721-e429-4135-bdd8-c25b6025df60)



I still think it's better to not reuse the same ice profiles. The issue with the last plot can perhaps be diminished a bit by either making the stencil for shuffling larger, or playing with "ice edge" parameter. Any thoughts @guillaumevernieres, @travissluka?

**Comment by guillaumevernieres** [comment]
I agree with you @shlyaeva , we should probably not reuse the same ice profile. I remember seeing "weird" ice state when the increment added a large chunk of ice in the restart.
Making the stencil larger sounds like a good idea.

**Comment by shlyaeva** [comment]
@guillaumevernieres I also tried changing the ice edge to 40% (from 80%) and that makes soca2cice analysis close enough to soca analysis (because everything from 40-80% is rescaled instead of shuffled). I'll play around with that and with the stencil size and see what cice may be ok with, at least on a couple dates.

In the meantime I'll open a PR for the shuffle change.
