### ISSUE TITLE
Impose bounds to analysis state

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#128]
This will first be applied to T and S. Bounds will be imposed through a change of variable and replace the current clamping that we impose on the analysis.

**Comment by guillaumevernieres** [comment]
I will work on #125 and #127.
 @travissluka or @aerorahul , let me know if you are interested in #126. It's also a good opportunity to rename some of the transforms (soca, godas, ...).

**Comment by travissluka** [comment]
closing for now. We will open new similar issues under AOP22 addressing this topic
