### ISSUE TITLE
Update to eckit-1.1.0

### ISSUE THREAD

**Issue by markjolah** [JCSDA-internal/soca#157]
The rest of the JCSDA/JEDI repos and the jedi-stack will be moving to `eckit-1.1.0` in order to support the new ODC library.  This will lead to compile failures for soca, mainly related to header file changes.  I have a feature branch with updates for soca.  I'm not sure I have permission to push it though, as I get error 
```
remote: Repository not found.
fatal: repository 'https://github.com/JCSDA/soca.git/' not found
```

At the moment, several of the soca tests are still failing for me.  I may need help debugging.  Mainly I am seeing small errors in min, max, mean values like:
```
354: Run: Finishing oops::EnsVariance<SOCA> with status = 0
354: 5,6c5,6
354: < Test     :    socn   min=    0.000000   max=    7.827189   mean=    0.061866
354: < Test     :    tocn   min=    0.000000   max=    5.659445   mean=    0.019298
354: ---
354: > Test     :    socn   min=    0.000000   max=    7.827189   mean=    0.061865
354: > Test     :    tocn   min=    0.000000   max=    5.659445   mean=    0.019303
```

Failing tests are:
```
341 - test_soca_enspert (Failed)
354 - test_soca_ensvariance (Failed)
356 - test_soca_dirac_soca_cov (Failed)
357 - test_soca_dirac_socahyb_cov (Failed)
360 - test_soca_enshofx (Failed)
361 - test_soca_3dvarsoca (Failed)
362 - test_soca_3dvargodas (Failed)
363 - test_soca_3dhyb (Failed)
364 - test_soca_3dhybfgat (Failed)
365 - test_soca_checkpointmodel (Failed)
366 - test_soca_3dvarfgat (Failed)
```

The eckit-1.1.0 related PRs are coordinated by the central tracking issue: [jedi-stack#32](https://github.com/JCSDA/jedi-stack/issues/32)

**Comment by guillaumevernieres** [comment]
Thanks for doing that @markjolah ! I just sent you an invite to the soca team.

**Comment by ytremolet** [comment]
I've added write permission to the jedi core team. You should be able to push now.
