### ISSUE TITLE
Illegal floating point operations

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#203]
Testing with the oops branch to trap floating point math errors (https://github.com/JCSDA/oops/pull/420) shows that we are doing something bad in `kst_mod_MOD_soca_soft_jacobian` 

```
10: Caught SIGFPE:
10: floating-point invalid operation
10: /home/tsluka/work/jedi-soca/soca.build/gcc_7.4/openmpi_3.1.2/debug/bin/../lib/liboops.so(_Z14sigfpe_handleriP9siginfo_tPv+0x1d9) [0x1531a70040e3]
10: /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x1531a563cf20]
10: /home/tsluka/work/jedi-soca/soca.build/gcc_7.4/openmpi_3.1.2/debug/bin/../lib/libsoca.so(__soca_kst_mod_MOD_soca_soft_jacobian+0xfa1) [0x1531a7617232]
10: /home/tsluka/work/jedi-soca/soca.build/gcc_7.4/openmpi_3.1.2/debug/bin/../lib/libsoca.so(__soca_balance_mod_MOD_soca_balance_setup+0xe68) [0x1531a7612ede]
10: /home/tsluka/work/jedi-soca/soca.build/gcc_7.4/openmpi_3.1.2/debug/bin/../lib/libsoca.so(soca_balance_setup_f90+0x167) [0x1531a760177b]
10: /home/tsluka/work/jedi-soca/soca.build/gcc_7.4/openmpi_3.1.2/debug/bin/../lib/libsoca.so(_ZN4soca7BalanceC2ERKNS_5StateES3_RKNS_8GeometryERKN5eckit13ConfigurationE+0x90) [0x1531a7600078]
10: /home/tsluka/work/jedi-soca/soca.build/debug/bin/soca_enspert.x(_ZN4oops20LinearVariableChangeIN4soca6TraitsENS1_7BalanceEEC1ERKNS_5StateIS2_EES8_RKNS_8GeometryIS2_EERKN5eckit13ConfigurationE+0x19d) [0x55772
7788e83]
10: /home/tsluka/work/jedi-soca/soca.build/debug/bin/soca_enspert.x(_ZN4oops25LinearVariableChangeMakerIN4soca6TraitsENS_20LinearVariableChangeIS2_NS1_7BalanceEEEE4makeERKNS_5StateIS2_EESA_RKNS_8GeometryIS2_EERK
N5eckit13ConfigurationE+0x4a) [0x557727784510]
10: /home/tsluka/work/jedi-soca/soca.build/debug/bin/soca_enspert.x(_ZN4oops27LinearVariableChangeFactoryIN4soca6TraitsEE6createERKNS_5StateIS2_EES7_RKNS_8GeometryIS2_EERKN5eckit13ConfigurationE+0x361) [0x557727
791bc3]
10: /home/tsluka/work/jedi-soca/soca.build/debug/bin/soca_enspert.x(_ZN4oops24ModelSpaceCovarianceBaseIN4soca6TraitsEEC1ERKNS_5StateIS2_EES7_RKNS_8GeometryIS2_EERKN5eckit13ConfigurationE+0x1a7) [0x55772778cf9b]
10: /home/tsluka/work/jedi-soca/soca.build/debug/bin/soca_enspert.x(_ZN4oops15ErrorCovarianceIN4soca6TraitsEEC1ERKNS_8GeometryIS2_EERKNS_9VariablesERKN5eckit13ConfigurationERKNS_5StateIS2_EESI_+0x7b) [0x55772778
5819]
```

**Comment by travissluka** [comment]
...eh turns out it's a divide by zero that shouldn't have affected the value of answers, but using this as an opportunity to go through and squash all illegal float operations. Currently the following also fail with SIGFPE being caught:

``
The following tests FAILED:
         24 - test_soca_ensvariance (Failed)
         25 - test_soca_ensvariance_compare (Failed)
         33 - test_soca_hofx (Failed)
         34 - test_soca_hofx_compare (Failed)
         35 - test_soca_enshofx (Failed)
         36 - test_soca_3dvar_soca (Failed)
         37 - test_soca_3dvar_soca_compare (Failed)
         38 - test_soca_3dvar_godas (Failed)
         39 - test_soca_3dvar_godas_compare (Failed)
         40 - test_soca_3dvarfgat (Failed)
         41 - test_soca_3dvarfgat_compare (Failed)
         42 - test_soca_3dhyb (Failed)
         43 - test_soca_3dhyb_compare (Failed)
         44 - test_soca_3dhybfgat (Failed)
         45 - test_soca_3dhybfgat_compare (Failed)
```

**Comment by guillaumevernieres** [comment]
@travissluka , looks like the balance test is missing from your list above (simple fix).   
Ensemble variance throws a floating-point overflow in the schur product ... Happy to look at it.

**Comment by travissluka** [comment]
closing this since the balance operator issue was fixed... I'll open a separate epic to track all the remaining known (non-model related) floating point exceptions
