### ISSUE TITLE
Prepare for oops/saber ATLAS stuff

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#213]
prepare for the addition of atlas fields in oops/saber
https://github.com/JCSDA/saber/pull/27
https://github.com/JCSDA/oops/pull/395

`bump%setup_online()` is gone, so our stuff wont compile with that PR until we make changes...yay.

**Comment by guillaumevernieres** [comment]
@travissluka , happy to do it this time around. 
@benjaminmenetrier, @ytremolet , @mmiesch  do you have an approximate time line for when your work will be merged in saber and oops?

**Comment by ytremolet** [comment]
Not sure. @benjaminmenetrier is breaking it in smaller PRs. My guess is you have another week or two but that could evolve...
