### ISSUE TITLE
soca_staticbinit.x fails with 1/4 deg on discover

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#214]
while reviving the cycling scripts on discover after all the oops/saber changes,  I found that 1 and 0.5 deg work, but 0.25 deg dies at soca_staticbinit.x because of an off by one error in arrays being passed to bump. 

```
At line 1306 of file /gpfsm/dnb31/tsluka/jedi/soca.src/saber/src/saber/bump/type_bump.F90
Fortran runtime error: Index '11110' of dimension 1 of array 'bump%cmat%blk%bump_rh' above upper bound of 11109
```

Haven't figured out yet if this is a soca or saber bug. Looking into it.

**Comment by guillaumevernieres** [comment]
@travissluka , FYI, It worked fine on Hera until the switch to pnetcdf. Are you having the same issue with the release?

**Comment by guillaumevernieres** [comment]
I added bump init for the 3d convolution and how to use it, if you feel like trying: 
[feature/bypass-socaerror](https://github.com/JCSDA/soca/tree/feature/bypass-socaerror)

Checkout parameters_bump_cor.yml and 3dvar_godas_bump.yml. Initialize bump with soca_parameter.x

Discover has quite a bit more memory than Theia, maybe it will work.

**Comment by travissluka** [comment]
On release I get a crash from corrupted memory. It's entirely possible this bug was there all along but wasn't being caught until something got moved around in saber. I haven't had a chance to debug yet on discover, apparently my wife doesn't let me work during non work hours...

**Comment by guillaumevernieres** [comment]
Well, that wouldn't be the first time. 
I meant the soca-bundle v0.1 for release. That's what we've been running on Hera with no (known) problems.

**Comment by travissluka** [comment]
this will be  fixed when https://github.com/JCSDA/saber/pull/39 is merged
