### ISSUE TITLE
thinning, difference check and gaussian thinning filters yaml changes

### ISSUE THREAD

**Issue by shlyaeva** [JCSDA-internal/soca#227]
I've just merged an update to ufo that will break experiments where Thinning, Gaussian Thinning or Difference Check filters are used.
Yamls for those filters now require explicitly specifying which variables are filtered out.
If you use any of those filters, please change the yamls. See examples in https://github.com/JCSDA/ufo/pull/718/files

**Comment by travissluka** [comment]
@shlyaeva  thanks for the heads up! Always better to find out from a human instead of wondering why the TravisCI cron job is suddenly failing!

**Comment by shlyaeva** [comment]
@travissluka: I meant to notify everyone before merging, so it wouldn't break anything, but forgot, sorry!
