### ISSUE TITLE
SOCA builds failing on TravisCI

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#278]
## Description
The soca builds on travisCI are suddenly failing, see https://travis-ci.com/JCSDA/soca/builds/147554389, after the most recent IODA PRs last night (https://github.com/JCSDA/ioda/pull/373)

The log indicates ecbuild can't find `ecbuild_check_multiurl`

@mer-a-o @srherbener @mmiesch I see that the IODA PR was not tested on TravisCI, any idea if this is breaking any other project's TravisCI builds??

**Comment by mer-a-o** [comment]
You need to use the updated docker image. The old docker image does not have the most recent ecbuild. Change the first line in your Dockerfile to pull  jcsda/docker-gnu-openmpi-dev:latest.
