### ISSUE TITLE
No master branch?

### ISSUE THREAD

**Issue by cmgas** [JCSDA-internal/soca#285]
When I try to run "git flow init -d", the system complains because there is no master branch for soca. 
I wanted to look at the mpi communicators, but cannot create a new feature... 
@guillaumevernieres ? @travissluka ?

**Comment by guillaumevernieres** [comment]
@cmgas , sorry for the delay in replying. I just gave you the permission to push branches.

**Comment by travissluka** [comment]
I don't really believe in the `master` branch, now that I'm being sucked into the  **DevOps** cult... nonetheless I've created a `master` branch so that the git-flow commands wont yell at you.

**Comment by travissluka** [comment]
... and for the record `master` seems to not work on TravisCI.. oh well
