### ISSUE TITLE
Download ocean color observations from VIIRS and MODIS

### ISSUE THREAD

**Issue by liuxiao37k** [JCSDA-internal/soca#324]
Add scripts to download ocean color L2 NRT observations from VIIRS and MODIS. VIIRS data (platforms: JPSS1/NOAA-20 and S-NPP) are retrieved from NOAA CoastWatch and MODIS data (platform: Aqua) from NASA GSFC.

These observations are needed for the Ocean DA activities.

**Comment by guillaumevernieres** [comment]
@liuxiao37k  please assign yourself (Assignees label on the right).
