### ISSUE TITLE
Time binning of the GeoVaLs read from files

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#327]
## Description
Time binning of the atmospheric geovals in GetValues is not implemented.

## Solution/Optimization
Implement the binning for atmospheric geovals in GetValues.cc.

 Reading of all the geovals should be done at the constructor level as suggested by @shlyaeva [here](https://github.com/JCSDA/soca/pull/326#discussion_r408243199)

## Alternatives
Do nothing.

**Comment by shlyaeva** [comment]
I think this can be closed now that this functionality is removed from soca. (I'm going through all issues where I'm mentioned, and noticed this one).

**Comment by travissluka** [comment]
taking advantage of @guillaumevernieres  being on vacation and closing this myself :-)
