### ISSUE TITLE
== operator in Geometry class

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#348]
## Description
To test if a change of resolution is needed in Increment and State, a Geometry "==" operator is needed, or would be convenient to have. This should probably be defined in the base class but will be implemented in soca, for now (or ever)

## Solution
Brew some coffee and code.

## Alternatives
So many hacky ways to solve that problem.

## Related to
- needed by #339

**Comment by travissluka** [comment]
we're not fancy enough to earn having a == operator
