### ISSUE TITLE
CTEST failed due to new multiple geometry on Hera/Orion with Intel 18/19 compiler

### ISSUE THREAD

**Issue by clouden90** [JCSDA-internal/soca#358]
## Description
CTEST failed on Hera & Orion due to the new multiple geometry codes (fresh build). Error message (Hera) is attached below:

4: Exception: Assertion failed: inputnml_sn_ > 0 in FmsInput, line 30 of /scratch2/NCEPDEV/marineda/Xiao.Liu/git-versions/godas-git-branches/godas/src/soca-bundle/developments/soca-bundle/soca/src/soca/Geometry/FmsInput.cc

### To Reproduce:
What compilers/machines are you seeing this with? Intel18 on Hera & Intel19 on Orion

**Comment by guillaumevernieres** [comment]
:+1: thanks for spotting the issue @clouden90 ! (Don't forget to assign yourself).

**Comment by guillaumevernieres** [comment]
@clouden90 , I just tested with intel-18 on Hera and all is good. Can you be a bit more specific as to what exactly fails?
![test-yc-issue](https://user-images.githubusercontent.com/14031856/82374660-5de7e980-99ed-11ea-8fcf-914224b20f0d.png)

**Comment by clouden90** [comment]
> @clouden90 , I just tested with intel-18 on Hera and all is good. Can you be a bit more specific as to what exactly fails?
> ![test-yc-issue](https://user-images.githubusercontent.com/14031856/82374660-5de7e980-99ed-11ea-8fcf-914224b20f0d.png)

@guillaumevernieres,  screenshots of info on loaded modules  (suggested by GODAS README.md) and ctest failed are attached below:
![screen1](https://user-images.githubusercontent.com/30629225/82379398-d7cfa100-99f4-11ea-9daf-bb6b6f69a109.png)
![image](https://user-images.githubusercontent.com/30629225/82379552-15ccc500-99f5-11ea-912d-042c39586e7a.png)

and below are detailed error message (gridgen case for example):
![image](https://user-images.githubusercontent.com/30629225/82379755-72c87b00-99f5-11ea-852b-a1cd3b5d8bc3.png)

To me it looks like the program aborted due to inputnml_sn_ < 0. I checked the value of inputnml_sn_ is < 0 even the target file is existed. Maybe this is a compiler dependent issue?

**Comment by aerorahul** [comment]
@clouden90 cant run tests on hera front end node. Try a compute node with 6+ pe's

**Comment by clouden90** [comment]
> @clouden90 cant run tests on hera front end node. Try a compute node with 6+ pe's

Thx, @aerorahul . did tests on compute node but still can not pass:
![image](https://user-images.githubusercontent.com/30629225/82381013-79f08880-99f7-11ea-86ff-6c2b7f7bbfd1.png)

**Comment by guillaumevernieres** [comment]
can you share the output of:
 `ls ./build/soca/test/`

**Comment by clouden90** [comment]
> ls ./build/soca/test/
@guillaumevernieres , here is the screenshot:
![image](https://user-images.githubusercontent.com/30629225/82386427-63036380-9a02-11ea-9f22-f46e3216c8d1.png)

**Comment by guillaumevernieres** [comment]
Fresh clone and fresh build and it's still ok.
Here's how to build:
Currently Loaded Modules:
  1) intel/18.0.5.274   
  2) impi/2018.0.4   
  3) netcdf-hdf5parallel/4.7.0   
  4) intelpython/3.6.8   
  5) jedi-stack/intel-impi-18.0.5   
  6) nco/4.9.1

```console
ecbuild -DMPIEXEC_EXECUTABLE=`which srun` -DMPIEXEC_NUMPROC_FLAG="-n" ..
make -j12
```

**Comment by clouden90** [comment]
> Fresh clone and fresh build and it's still ok.
> Here's how to build:
> Currently Loaded Modules:
> 
> 1. intel/18.0.5.274
> 2. impi/2018.0.4
> 3. netcdf-hdf5parallel/4.7.0
> 4. intelpython/3.6.8
> 5. jedi-stack/intel-impi-18.0.5
> 6. nco/4.9.1
> 
> ```
> ecbuild -DMPIEXEC_EXECUTABLE=`which srun` -DMPIEXEC_NUMPROC_FLAG="-n" ..
> make -j12
> ```

Thx, @guillaumevernieres. I also redo fresh clone & fresh build with your ecbuild options. Here's how I build:
module purge
source /scratch2/NCEPDEV/marineda/Jong.Kim/hera.intel18
source /scratch2/NCEPDEV/marineda/Jong.Kim/hera.setenv
git clone -b develop https://github.com/JCSDA/soca.git
mkdir -p build
ecbuild -DMPIEXEC_EXECUTABLE=`which srun` -DMPIEXEC_NUMPROC_FLAG="-n" ../soca/bundle
cd soca
make -j12
salloc --ntasks 12 --qos=debug --time=00:30:00 --account=marine-cpu
ctest	

and this time I can pass most of tests:
![image](https://user-images.githubusercontent.com/30629225/82394082-0316b800-9a16-11ea-8f84-c81f6fcce47d.png)

So I think it is something to do with the ecbuild option (the only difference compared to my previous build). **We should highligh this ecbuild option somewhere maybe**.

**Comment by guillaumevernieres** [comment]
I haven't looked at godas in a while, maybe the readme needs an update. Could you create an issue in the godas repo? 

This is all you need to do:
```console
module use /scratch1/NCEPDEV/jcsda/Ryan.Honeyager/jedi/modules
module load jedi-stack/intel-impi-18.0.5
module load nco/4.9.1
ecbuild -DMPIEXEC_EXECUTABLE=`which srun` -DMPIEXEC_NUMPROC_FLAG="-n" ..
make -j12
```

**Comment by flampouris** [comment]
> ```
> module use /scratch1/NCEPDEV/jcsda/Ryan.Honeyager/jedi/modules
> ```
This path is on Hera.

**Comment by guillaumevernieres** [comment]
> > ```
> > module use /scratch1/NCEPDEV/jcsda/Ryan.Honeyager/jedi/modules
> > ```
> 
> This path is on Hera.

Yes, that's where @clouden90 was testing, judging from the snapshot of the logs above.

**Comment by guillaumevernieres** [comment]
> I haven't looked at godas in a while, maybe the readme needs an update. Could you create an issue in the godas repo?
> 
> This is all you need to do:
> 
> ```
> module use /scratch1/NCEPDEV/jcsda/Ryan.Honeyager/jedi/modules
> module load jedi-stack/intel-impi-18.0.5
> module load nco/4.9.1
> ecbuild -DMPIEXEC_EXECUTABLE=`which srun` -DMPIEXEC_NUMPROC_FLAG="-n" ..
> make -j12
> ```

I'm going to test ... again, apparently @flampouris , @jkbk2004 and @clouden90 are still having issues. If it's all good, please ping me.

**Comment by guillaumevernieres** [comment]
@flampouris , @jkbk2004  @clouden90 : Well, the "good news" is that it is now failing for me too. A busy night or tomorrow ahead ... Great! I'll keep you posted.

**Comment by guillaumevernieres** [comment]
@flampouris , @clouden90 , @jkbk2004 : OK, legit failure. I think it has to do with the file system and how quickly the assertion happens after the symlink is (suppose to be ) created. @aerorahul raised a concern about file system command within the code, here's a precise example of why we shouldn't ... Unfortunately, we have no way around it. I have  fix for it that I really dislike, but that will sort out our current issue. PR tomorrow.

**Comment by flampouris** [comment]
@guillaumevernieres The issues at Orion and hera seemed to be different. 

At Orion the eckit fails to compile, it is built on the fly every time, we are not pointing to a library.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres The issues at Orion and hera seemed to be different.
> 
> At Orion the eckit fails to compile, it is built on the fly every time, we are not pointing to a library.

@flampouris : OK, I'm on it. I need 5 mn of your time this am, check your calendar.

**Comment by guillaumevernieres** [comment]
@flampouris , @jkbk2004 , @clouden90 : [eckit pr#12](https://github.com/JCSDA/eckit/pull/12) fixed the issue. I was able to build on Orion, not tested on Hera yet.

**Comment by guillaumevernieres** [comment]
> @flampouris , @jkbk2004 , @clouden90 : [eckit pr#12](https://github.com/JCSDA/eckit/pull/12) fixed the issue. I was able to build on Orion, not tested on Hera yet.

A bit keyboard happy above. It builds, but mom6 fails now ...

**Comment by flampouris** [comment]
@guillaumevernieres when you are are ready, please provide info on which branch you use and how you build it at both machines.

**Comment by jkbk2004** [comment]
@flampouris @guillaumevernieres even nightly-stable soca branch of godas fails ctests on hera. I think we have to check.

**Comment by flampouris** [comment]
@jkbk2004 yes, that was the case also last night.

**Comment by guillaumevernieres** [comment]
Looks like Hera is down today. @flampouris , @jkbk2004 , did you build eckit as well? We do have a supposedly working hash-tag for that repo. I'll try as soon as I can login again.

**Comment by guillaumevernieres** [comment]
@jkbk2004 and @flampouris : Are you using that branch of the bumdle when building? https://github.com/JCSDA/soca-bundle/pull/30  :point_left: I need your review on this btw.

**Comment by guillaumevernieres** [comment]
@jkbk2004 , @flampouris , @clouden90 , @aerorahul : A fresh clone/build of soca-bundle develop on Hera seems to indicate that for some reason all is good again. Could one of you test? 

```
$ module use /scratch1/NCEPDEV/jcsda/Ryan.Honeyager/jedi/modules
$ module load jedi-stack/intel-impi-18.0.5
$ module load nco/4.9.1
$ git clone https://github.com/JCSDA/soca-bundle
$ ... 
$ ecbuild -DMPIEXEC_EXECUTABLE=`which srun` -DMPIEXEC_NUMPROC_FLAG="-n" -DBUILD_ECKIT=ON path_to_bundle
$ ...
```
![soca-ctests](https://user-images.githubusercontent.com/14031856/83874429-6d607580-a703-11ea-9d07-b1ca2871c081.png)

@aerorahul : Can you let me know when a new jedi-stack is available on Orion?

**Comment by jkbk2004** [comment]
@aerorahul @flampouris @guillaumevernieres @clouden90 I am testing now...

**Comment by jkbk2004** [comment]
@aerorahul @flampouris @guillaumevernieres @clouden90 exactly followed the steps but I see it still fails.
![socatest](https://user-images.githubusercontent.com/38663008/83877167-0d200280-a708-11ea-94b6-939a7994cf37.png)

**Comment by guillaumevernieres** [comment]
Thanks for testing. 
You should not run on the login nodes @jkbk2004 . 
```
$ salloc --ntasks 2 --qos=debug --time=00:10:00 --account=marine-cpu
```
could you post the output of the first failing test (`ctest -V -I 3,3` )?

**Comment by jkbk2004** [comment]
@guillaumevernieres here is the log from compute node.
[LastTest.log](https://github.com/JCSDA/soca/files/4736226/LastTest.log)

**Comment by guillaumevernieres** [comment]
Thanks @jkbk2004 , same error as the last time. It does annoy me to not be able to reproduce it anymore!
Could you try my blind folded "fix": soca branch `bugfix/filesn`. I'll create a pr if that fixes the issue.

**Comment by jkbk2004** [comment]
@guillaumevernieres This branch works! All good for ctests.
