### ISSUE TITLE
atlas fails to build in travis-ci

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#370]
## Description
atlas build started failing earlier today (2020-06-10)
```
/jcsda/work/repo.src/atlas/src/atlas_f/internals/atlas_write_to_fortran_unit.F90:11:36:

   11 |   use fckit_c_interop_module, only : copy_c_ptr_to_string

      |                                    1

Error: Symbol ‘copy_c_ptr_to_string’ referenced at (1) not found in module ‘fckit_c_interop_module’
```

**Comment by mer-a-o** [comment]
@guillaumevernieres: you need to use release-stable branch for atlas. I think Travis-CI is using develop branch:
https://travis-ci.com/github/JCSDA/soca/builds/170692092#L283

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres: you need to use release-stable branch for atlas. I think Travis-CI is using develop branch:
> https://travis-ci.com/github/JCSDA/soca/builds/170692092#L283

oops ... l probably reverted to develop in the last pr. Thanks @mer-a-o . 
Update: Just looked at the code and we are pointing to release-stable, not sure why travis-ci is pointing at develop. Digging in the script will happen tomorrow!

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres: you need to use release-stable branch for atlas. I think Travis-CI is using develop branch:
> https://travis-ci.com/github/JCSDA/soca/builds/170692092#L283

@mer-a-o I cleaned the cache and rebuilt (my one and only strategy to fix travis-ci!) and that did not do it. I made a local build the same way travis-ci does, in singularity, and it built/tested fine. [This branch](https://github.com/JCSDA/soca/pull/371,) which has zero code change tests fine, but develop keeps failing. At a loss. Taking a break from the issue, but pointers would be greatly appreciated! 
Was the container updated 2 days ago?

**Comment by mer-a-o** [comment]
@guillaumevernieres, looks like https://github.com/JCSDA/soca/pull/371 used `release-stable` branch of atlas and tests passed. But for Cron builds `develop` is used. Are the settings for branch names different for Cron jobs?

**Comment by guillaumevernieres** [comment]
@mer-a-o . I don't think so, but will check. I'm going to try to turn off the branch matching also ... for now.

**Comment by mer-a-o** [comment]
I think you need to remove atlas from `MATCH_REPOS` in .travis.yml.

**Comment by guillaumevernieres** [comment]
> I think you need to remove atlas from `MATCH_REPOS` in .travis.yml.

Yup, will try that, thanks @mer-a-o . I'll let @travissluka deal with a real solution :)

**Comment by guillaumevernieres** [comment]
![tadaaaa](https://user-images.githubusercontent.com/14031856/84415506-de5ecc00-abe0-11ea-8f5b-ef2c7260c605.png)
:tada: :tada: :tada: :tada:
