### ISSUE TITLE
Automated merge with non default dependencies in the soca/bundle (and not soca-bundle!))

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#386]
## Description
This keeps happening: When merging a pr that has modified the bundle cmakelists, the repository branch needs to be changed back to the default branches manually before the merge happens. I don't know if there is a simple solution to the issue, but that's one downside to having the bundle specified inside of soca.

**Comment by travissluka** [comment]
nothing to fix here... user error?

Rely on the branch matching of travisCI, and be careful when adding to git. (I always use `git add -p` to interactively make sure i'm adding only the lines that should be added)
