### ISSUE TITLE
Add a simple chlorophyll 3DVAR ctest

### ISSUE THREAD

**Issue by liuxiao37k** [JCSDA-internal/soca#432]
## Description
Include chlorophyll in the SOCA 3DVAR ctest. Due to a number of issues yet to be resolved (e.g. geovals refactoring, log-transformation, depth integration and penetration), here we start simple by only assimilating surface chlorophyll using the `Identity` operator. This feature will be revisited and improved at a later stage to integrate cutting-edge science.

## Solution
The proposed solution is implemented in a feature branch [here](https://github.com/JCSDA/soca/tree/feature/chl_3dvar).

`ocn.bkgerror.nc` is updated to include `chl`, the values of which are set to be 30% of the background values according to literature.

**Comment by guillaumevernieres** [comment]
Sounds like a good plan @liuxiao37k
