### ISSUE TITLE
State test is failing

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#449]
## Description
State test is :boom:  in constructor test, x.vars /= vars ... oops, mld and layer_depth probable culprit.

Edit again ... Known problem that we've pushed under the rag for a while, dang. We'll blame @shlyaeva & @cmgas for exposing the bug!
```
xx3.vars=13  variables: cicen, hicen, socn, tocn, ssh, hocn, sw, lhf, shf, lw, us, mld, layer_depth
vars=11         variables: cicen, hicen, socn, tocn, ssh, hocn, sw, lhf, shf, lw, us
```
For future reference, it's failing [here](https://github.com/JCSDA/oops/blob/168d1b702afbdd7b248ee2eee7d3f090d2fac1e3/src/test/interface/State.h#L105)

**Comment by shlyaeva** [comment]
You can also blame @cmgas, she wrote that nice test! That's what the oops tests are for; exposing soca's _known_ problems :)

**Comment by guillaumevernieres** [comment]
> You can also blame @cmgas, she wrote that nice test! That's what the oops tests are for; exposing soca's _known_ problems :)

Thanks (?) @shlyaeva , noted and edited ...

**Comment by travissluka** [comment]
FYI @guillaumevernieres don't say "does not close" in a pr.... because it will close!

**Comment by cmgas** [comment]
@travissluka you should also look at https://github.com/JCSDA/soca/tree/feature/test_interface_State_zero that is coming soon. I tested the new branch with removing the `EXPECT xx3.vars=vars` + `EXPECT xx4.vars=vars` and reactivating the state test, and the ReadWrite test breaks soca too.

**Comment by guillaumevernieres** [comment]
> FYI @guillaumevernieres don't say "does not close" in a pr.... because it will close!

Why not? We solved the problem by commenting out the test, case closed, points scored. We are re-opening to better solve the issue.

**Comment by travissluka** [comment]
general question: ideally, should things work if increment contains a proper subset of variables of the state variables, or do we have to make state and increment contain the same variables everywhere?
