### ISSUE TITLE
Add a flag for, or remove, the increment output.

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#451]
## Description
soca applications producing an increment generate `incr.X.nc` files. This results in a lot of disk space being used for files i'm not using, especially for ensemble applications. enspert/letkf for the 40 member 1 degree MOM6 generates ~30GB of these files for a single cycle

## Solution
- add flag to enable/disable increment output
- or rip it out completely

**Comment by guillaumevernieres** [comment]
I use these files. Flag sounds good.

**Comment by guillaumevernieres** [comment]
See [oops pr #955](https://github.com/JCSDA-internal/oops/pull/955)

**Comment by guillaumevernieres** [comment]
@travissluka , I am playing with @fabiolrdiniz 's write increment feature from  [oops #955](https://github.com/JCSDA-internal/oops/pull/955@travissluka). I'll push that work tonight or tomorrow am.
