### ISSUE TITLE
SOCA build on RDHPCS Hera

### ISSUE THREAD

**Issue by HenryRWinterbottom** [JCSDA-internal/soca#461]
The compilation for SOCA is routinely failing on RDHPCS Hera.

In /scratch2/BMC/gsienkf/Henry.Winterbottom/regression-tests/builds/UFS-RNR.20201011/sorc/logs, please find the cmake and make log within ufsrnr_jedi_soca.log.

The following error message has been consistent.

`no instance of constructor "ioda::ObsSpace::ObsSpace" matches the argument list
            argument types are: (eckit::LocalConfiguration, const eckit::mpi::Comm, util::DateTime, util::DateTime)
      ioda::ObsSpace atmobs(confatmobs, geom_->getComm(), bgn, end);
                            ^
`

We are using the following module environments at compile time:

module use -a /scratch1/NCEPDEV/jcsda/Ryan.Honeyager/jedi/modules/
module load jedi-stack/intel-impi-19.0.5

**Comment by guillaumevernieres** [comment]
@jkbk2004 or @clouden90 have you tried to build on Hera recently?

**Comment by guillaumevernieres** [comment]
@HenryWinterbottom-NOAA , just build soca using the bundle in soca-science. All good:
![soca-hera-build](https://user-images.githubusercontent.com/14031856/95751706-fcab0600-0c6c-11eb-981c-e70679877d26.png)
I did not run the ctests ...

See doc here on how to build on hera:
https://github.com/JCSDA/jedi-docs/blob/develop/docs/developer/jedi_environment/modules.rst

**Comment by clouden90** [comment]
> @jkbk2004 or @clouden90 have you tried to build on Hera recently?
> 
> 

@guillaumevernieres Tested with soca-science workflow (3dvar only) on Hera last week. Unfortunately now on PTO and can't access my laptop...

**Comment by HenryRWinterbottom** [comment]
@guillaumevernieres Thanks!

Just to be clear,  after multiple attempts I am eventually able to get it to build successfully. However,  every time that it does fail it is with the original error I posted.

Any thoughts on that or what might be leading to that result?

**Comment by guillaumevernieres** [comment]
@HenryWinterbottom-NOAA , are you rerunning the build with `make -j1`? If not, the traceback above probably doesn't mean anything if you are doing a parallel build.

**Comment by jkbk2004** [comment]
@clouden90 @guillaumevernieres @HenryWinterbottom-NOAA Cameron is trying on hera. @cameronbook how is your build test going on hera?

**Comment by HenryRWinterbottom** [comment]
@guillaumevernieres I just reread your comments above.

 I have been attempting to build (with multiple failures and intermittent success) from  https://github.com/JCSDA/soca.git.

You mentioned using the bundle beneath SOCA-science. Could it be that the repo I am pulling from is no longer valid? Should I instead be cloning from https://github.com/JCSDA/soca-science.git?

**Comment by jkbk2004** [comment]
@HenryWinterbottom-NOAA I don't expect any build issue on orion. Are you working on orion? Then send me email and cc to Cameron. We can follow up quick.

**Comment by HenryRWinterbottom** [comment]
@jkbk2004 No. We are working exclusively on RDHPCS Hera at the moment.

**Comment by jkbk2004** [comment]
> @jkbk2004 No. We are working exclusively on RDHPCS Hera at the moment.

@HenryWinterbottom-NOAA what is your email?

**Comment by HenryRWinterbottom** [comment]
henry.winterbottom@noaa.gov

**Comment by travissluka** [comment]
@HenryWinterbottom-NOAA there was a set of ioda/oops prs a while back that changed the code there. you mush have been using out of date repos. just make sure to do a `make update`

**Comment by HenryRWinterbottom** [comment]
@travissluka ok, good to know! I will add that to our build scripts.  Thank you (as always)!

**Comment by HenryRWinterbottom** [comment]
With help from everyone on this thread, our latest test of the SOCA-science build on RDHPCS Hera completed successfully.

Thank you to everyone for your help. Closing this ticket/issue.
