### ISSUE TITLE
Incorporate the obs scripts in the cycling experiments. 

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#47]
Add the adt obs preparation script to the cycling example under exp.

**Comment by guillaumevernieres** [comment]
Remove adt and replace by GODAS.

**Comment by guillaumevernieres** [comment]
@travissluka @aerorahul : I'm going to add the altimeter ("rads 2 ioda") script to the cycling, and update the config files for the 3dvar. @travissluka : I'll start from your branch.

**Comment by travissluka** [comment]
... was closed by some PR at some point in the past
