### ISSUE TITLE
hofx answers have changed

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#474]
## Description
answers have suddenly changed for hofx in soca
It might be due to https://github.com/JCSDA/oops/pull/4, eventhough i could have sworn that i tested to make sure answers wouldnt change with that pr. (oops!)

kdtree answers are finicky when retrieving N closest points but there happen to be > N points that are equidistant. perhaps calling `reserve()` first changes the way the tree happens to be partitioned at nodes with all equidistant points??

anyway, @danholdaway this might slightly impact your answers as well, if that pr is indeed the cause.

**Comment by ytremolet** [comment]
@travissluka I hope it doesn't count as jedi breaking soca when it was your own PR!!!

**Comment by guillaumevernieres** [comment]
> @travissluka I hope it doesn't count as jedi breaking soca when it was your own PR!!!

@ytremolet it sure does!
