### ISSUE TITLE
Variable change: log() and exp() transformations

### ISSUE THREAD

**Issue by liuxiao37k** [JCSDA-internal/soca#475]
## Description
Some ocean variables (e.g. chlorophyll) are always positive and reasonably follow a log-normal distribution on a global-scale. Logarithmic (forward) and exponential (inverse) transformations are thus needed when assimilating these variables in order to 1) normalize the data, and 2) avoid creating negative values after applying the increments.

## Solution
The solution would be to add a new "variable change" option in SOCA to apply logarithmic (forward) and exponential (inverse) transformations to a set of variables that need such transformations. The proposed code change/addition can be found in this [feature branch](https://github.com/JCSDA-internal/soca/tree/feature/ana2model_log). A new ctest would also be needed to test out the applications of this variable change.

**Comment by guillaumevernieres** [comment]
Thanks @liuxiao37k . Keep your branch alive, but I think the simplest way forward is to implement a log transform inside of `Ana2Model`, since we can't define sequences of variable transforms between model and state like we do for B.
This is how it should probably look like from a user's perspective:
```yaml
  variable change: Ana2Model
  rotate:
    u: [uocn]
    v: [vocn]
  log:
   variables: [chl, socn, ...]
```
Your current work is going to be useful, but one step at a time.

**Comment by liuxiao37k** [comment]
@guillaumevernieres Sounds good to me. I'll create a new branch with the changes that you suggested. There are still technical issues with the transformations (e.g. how to deal with zeros and very small values) but I suppose those should be fixed in separate PRs. Thanks!
 
@jkbk2004 for notification purpose.

**Comment by liuxiao37k** [comment]
@guillaumevernieres I have updated the solution in a new branch feature/ana2model_log. Please let me know when you think this is ready to be discussed in a draft PR. Thanks!

**Comment by guillaumevernieres** [comment]
@liuxiao37k I just had a quick glance at your branch. Looks good, go ahead and submit a draft PR. Thanks.
