### ISSUE TITLE
Convert variable names to CF conventions

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#48]
before the  code sprint, we should make sure variable names that we already have are consistent with the CF conventions, worry about new or ambiguous ones at the sprint. This will involve minor changes to UFO and ioda_converters as well. I think these are all the names currently in use. @guillaumevernieres  @aerorahul , thoughts?

**old_name => CF_name**
- ocean_upper_level_temperature  =>  sea_surface_temperature
- ocean_potential_temperature => sea_water_potential_temperature
- ocean_salinity => sea_water_salinity (or sea_water_practical_salinity?)
- ocean_depth => depth
- ocean_layer_thickness =>  cell_thickness 
- **steric_height => ?**
- ocean_fraction => sea_area_fraction
- ice_thickness => sea_ice_thickness
- ice_concentration => sea_ice_area_fraction
- sea_surface_height_above_geoid (hey, we got one right already!)

- insitu_temperature => sea_water_temperature
- **obs_absolute_dynamic_topography => ?**

**Comment by aerorahul** [comment]
Adding link to @srherbener IODA wiki page for [Obs. Variable Specs](https://wiki.ucar.edu/display/JEDI/Observation+Variable+Specifications)

**Comment by aerorahul** [comment]
@travissluka renaming above variables looks good to me.

**Comment by aerorahul** [comment]
steric_height **?=>?** steric_sea_surface_height
Most steric variables are in reference to a change, and not absolute.

**Comment by guillaumevernieres** [comment]
1. except that sea_surface_height_above_geoid should be "sea_surface_height_above_mean_dynamic_topography", not CF con.

2. Steric height is not used anymore, so we could drop it.

3. I don't like cell_thickness, that seems too generic.

**Comment by travissluka** [comment]
@guillaumevernieres  I don't like cell thickness either. do we really need it? wouldn't it be more generic to just have the model interface provide depth?

I'll leave sea_surface_height_above_geoid for now, we can discuss it with the CF people
