### ISSUE TITLE
VariableChange (nonlinear) not functioning in 3dvar configuration

### ISSUE THREAD

**Issue by liuxiao37k** [JCSDA-internal/soca#481]
## Description
VariableChange (Ana2Model) not functioning in 3dvar configuration.

### To Reproduce:
Encountered this issue while running 3dvar tests on Hera.
1. take 3dvar_godas.yml as an example, these lines below do not seem to trigger the Ana2Model variable change:
```
  variable change: Ana2Model 
  rotate:
    u: [uocn]
    v: [vocn]
```
2. to test it, I added other variables to the list to be rotated (they are not supposed to be rotated but I was just doing that as a test), e.g.
```
  variable change: Ana2Model 
  rotate:
    u: [uocn, socn, tocn]
    v: [vocn]
```
3. then, nothing changed and the test passed, suggesting `socn` and `tocn` was not rotated.
4. Similarly, I added 'log' option and the variables were not transformed.
```
  variable change: Ana2Model 
  log:
    var: [socn, tocn]
```

**Comment by guillaumevernieres** [comment]
@liuxiao37k ... Oops, no model in 3dvar so no ana2model transformation. We missed that one, sorry. It's used in the 3dfgat, so you could test with that (and the pseudo model).

**Comment by liuxiao37k** [comment]
@guillaumevernieres Thanks. Yes I was able to test log transformation with 3dvarfgat. Is there a near future plan to enable Ana2model in the UFS framework?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres Thanks. Yes I was able to test log transformation with 3dvarfgat. Is there a near future plan to enable Ana2model in the UFS framework?

@liuxiao37k  Yes, for sure. My bad, I keep forgetting that the 3dvar applications do not have a model anymore, and we forgot to remove the now useless variable change in the 3dvar's. Adding the transform to the current ufs/3dvar will require a few additions to the workflow. Have a look at the "ConvertState" application.

**Comment by travissluka** [comment]
@guillaumevernieres instead of convertstate, is it possible to just use the fgat psuedo model with just a single time slice?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres instead of convertstate, is it possible to just use the fgat psuedo model with just a single time slice?

@travissluka : Yes, we need to switch to fgat at some point, but no I think we would need a minimum of 2 states. Something to think about for sure.
