### ISSUE TITLE
some tests fail on discover

### ISSUE THREAD

**Issue by HamidehGMAO** [JCSDA-internal/soca#492]
## Description
The following tests FAILED:
  5 - test_soca_convertstate (Failed)
49 - test_soca_3dvarbump (Failed)
54 - test_soca_3dvarfgat (Failed)
and it seems results of tests have slightly changed, all of them are failing in the "Running compare script" part

### To Reproduce:
What compilers/machines are you seeing this with?
Give explicit steps to reproduce the behavior.
just run with intel modules on discover

## Output

```
5: Float mismatch at line 16: 0.001990  not equal to  0.001991  with max relative difference  2e-05  Actual relative difference =  0.0005022601707685247
5: Failed in the COMPARE step. Error code: 1 
###
49: Float mismatch at line 12: 37.225040  not equal to  37.225035  with max relative difference  4e-09  Actual relative difference =  1.343181865558474e-07
49: Float mismatch at line 13: 38.316970  not equal to  38.317084  with max relative difference  4e-09  Actual relative difference =  2.975182981021652e-06
49: Float mismatch at line 13: 5.053063  not equal to  5.053064  with max relative difference  4e-09  Actual relative difference =  1.9789972977579109e-07
.
.
.
49: Failed in the COMPARE step. Error code: 1 
```

**Comment by guillaumevernieres** [comment]
@HamidehGMAO , can you adjust the tolerances of the tests that are failing? Assuming this is the cause of the failure.

**Comment by travissluka** [comment]
very old issue... @HamidehGMAO is this still an issue ?

**Comment by HamidehGMAO** [comment]
Yeah! We just kept ignoring this. It seems it's because of using different compilers we get slightly different results.

**Comment by travissluka** [comment]
to be handled by https://github.com/JCSDA-internal/soca/issues/733
