### ISSUE TITLE
Simplify sea ice io

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#493]
## Description
This is a continuation of #490 and probably should have been done in #490, but, here we are. IO field will be expected to be the same as the sea ice state in soca, no more differentiating between sis2 and cice. Expected field will be ice fraction, thickness and snow depth for 1 category.

## Solution
Delete more stuff.

**Comment by travissluka** [comment]
not that its important, but I thought it was funny that the lat/lon on the ice restart file are wrong, making it look like we have sub-Saharan and Mediterranean ice.
![image](https://user-images.githubusercontent.com/12516201/100483973-daa00280-30b7-11eb-806a-3bd7e773380f.png)
