### ISSUE TITLE
Domain check filter does not work with open boundaries

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#500]
Add option to mask out the open boundary in mask2d, mask2du and v.

**Comment by travissluka** [comment]
... this is what I was complaining about yesterday. See https://github.com/JCSDA-internal/ufo/pull/550 for Cory's solution for regional FV3

**Comment by guillaumevernieres** [comment]
![regional-badfilter](https://user-images.githubusercontent.com/14031856/103682567-0e900280-4f57-11eb-9230-f9c76a8fd9d3.png)
> ... this is what I was complaining about yesterday. See [JCSDA-internal/ufo#550](https://github.com/JCSDA-internal/ufo/pull/550) for Cory's solution for regional FV3

poorly phrased title, the issue is not the domain check filter. We just need to add or modify our current mask. I think it's a relatively simple fix without touching anything in ufo.

**Comment by guillaumevernieres** [comment]
The figure above shows what we get currently with the domain check, simply padding the mask at the open boundary would do the trick. HAt10 domain shown below
![ocn bkg 2015031912 nc ave_ssh global](https://user-images.githubusercontent.com/14031856/103682990-9aa22a00-4f57-11eb-8b73-147ab2e52e62.png)

**Comment by guillaumevernieres** [comment]
Oooooo ....
![woot-done](https://user-images.githubusercontent.com/14031856/103723001-196e8580-4f9f-11eb-9a35-14a3721d8b23.png)
