### ISSUE TITLE
Runtime failure with MOM6 "advance" when built with intel17+

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#52]
The model advance fails when running the forecast from soca or the mom6 executable. Contact GFDL?

**Comment by travissluka** [comment]
gaea uses 16 by default, but has 17 and 18 available, i can try to compile and run the basic mom6-examples and see what happens,

**Comment by guillaumevernieres** [comment]
@travissluka : that would be useful, thanks.

**Comment by travissluka** [comment]
@guillaumevernieres  hgodas compiles and seems to run fine on gaea with intel 17.0.4.196

**Comment by guillaumevernieres** [comment]
@travissluka : Thanks for checking. So it looks like an issue on our side. I wonder if this is just a setup issue. We're building mom6 solo driver, but a lot of the configuration was adapted from the coupled mom6/sis2. No urgency to fix before the cs.

**Comment by guillaumevernieres** [comment]
Issue resolved by @aerorahul
