### ISSUE TITLE
soca travis CI broken (in ufo)

### ISSUE THREAD

**Issue by shlyaeva** [JCSDA-internal/soca#525]
## Description

https://travis-ci.com/github/JCSDA-internal/soca/builds/216670131

> -- Configuring done
CMake Error at /usr/local/share/ecbuild/cmake/ecbuild_add_library.cmake:294 (add_library):
  Target "ufo" links to target "gsl::gsl-lite" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  /usr/local/share/ecbuild/cmake/ecbuild_add_library.cmake:639 (ecbuild_add_library_impl)
  src/ufo/CMakeLists.txt:125 (ecbuild_add_library)

This is likely because we started using ioda-engines in ufo. There's probably something missing in ufo CMakeLists; @travissluka, @rhoneyager, @srherbener  could you take a look?

**Comment by travissluka** [comment]
https://github.com/JCSDA-internal/ufo/pull/705 broke it when `ioda_engines` was added to `UFO_LIBS_DEP`. It only breaks when ufo/ioda are not compiled within the same bundle.
I'm guessing that adding `find_package(gsl-lite REQUIRED HINTS $ENV{gsl_lite_DIR})` to ufo would work, but perhaps someone with more cmake knowledge can tell me why the gsl library info is not found by ufo from the ioda install.

**Comment by shlyaeva** [comment]
I've created a branch in ufo with @travissluka's proposed fix, and am running Travis CI in soca to test.
I agree with Travis, would be nice to know why the gsl library info is not found by ufo from the ioda install.

**Comment by shlyaeva** [comment]
Now, with [this ufo branch](https://github.com/JCSDA-internal/ufo/compare/bugfix/soca-travisci), it [fails with a different error](https://travis-ci.com/github/JCSDA-internal/soca/builds/216791576):
> -- Configuring done
CMake Error at /usr/local/share/ecbuild/cmake/ecbuild_add_library.cmake:294 (add_library):
  Target "ufo" links to target "MPI::MPI_C" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  /usr/local/share/ecbuild/cmake/ecbuild_add_library.cmake:639 (ecbuild_add_library_impl)
  src/ufo/CMakeLists.txt:125 (ecbuild_add_library)
CMake Error at /usr/local/share/ecbuild/cmake/ecbuild_add_library.cmake:294 (add_library):
  Target "ufo" links to target "MPI::MPI_C" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  /usr/local/share/ecbuild/cmake/ecbuild_add_library.cmake:639 (ecbuild_add_library_impl)
  src/ufo/CMakeLists.txt:125 (ecbuild_add_library)


I have no idea how to fix it, unfortunately.
