### ISSUE TITLE
SOCA is broken

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#535]
## Description
- Travis-ci tests are failing (ref test need updating)
- bump init is failing at higher resolution

### To Reproduce:
- Run the ctests
- Static B init fails at 1deg and higher

```console
       Setup subset Sc0
         Look for redundant points in the model grid
         Define subset Sc0
         Communicate data from model grid to subset Sc0
!!! ABORT in com_red_real_r1 on task #0283: both redundant values are different
!!! ABORT in com_red_real_r1 on task #0270: both redundant values are different
!!! ABORT in com_red_real_r1 on task #0198: both redundant values are different
!!! ABORT in com_red_real_r1 on task #0141: both redundant values are different
!!! ABORT in com_red_real_r1 on task #0001: both redundant values are different
!!! ABORT in com_red_real_r1 on task #0042: both redundant values are different
```

**Comment by guillaumevernieres** [comment]
Merging @benjaminmenetrier 's [PR](https://github.com/JCSDA-internal/soca/pull/534) fixed the travis-ci issue, but the BUMP initialization is still failing ...

**Comment by guillaumevernieres** [comment]
[SABER PR#67](https://github.com/JCSDA-internal/saber/pull/67) fixes the BUMP init issue that we are seeing ... Seems like bugs are fixing themselve, nice! (or maybe thank you @benjaminmenetrier ?)

**Comment by benjaminmenetrier** [comment]
Well, I don't remember, but I'm happy to hear everything is fixed!

**Comment by benjaminmenetrier** [comment]
Oh yes, I remember now: it's about the reproducibility parameter `rth` that was too high (1.0e-10 instead of 1.0e-12), leading to confusions in the redundant points detection algorithm.
