### ISSUE TITLE
Have interpolation return missing values on land

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#542]
## Description
The GetValues interpolation currently will return a reasonable value for state variables even if the obs location is nowhere near water. This hasn't been a problem until recently because those observations on land are removed in the QC step with the "land mask" check.

However, it is causing problems for obs statistics (and maybe ADT observation operator global bias removal?) E.g. there is a valid looking salinity hofx on the Caspian Sea and Great Lakes, even though those don't exist in the model.
![image](https://user-images.githubusercontent.com/12516201/111797225-961abb80-888e-11eb-95cb-87aba92f3f96.png)

If an observation is 100% on land its hofx should be a missing value.

**Comment by travissluka** [comment]
I'm hoping that once https://github.com/jcsda-internal/soca/issues/722 is handled, we can put masked interpolation in OOPS, which would handle this

**Comment by shlyaeva** [comment]
May be part of https://github.com/JCSDA-internal/AOP22/issues/34 ?
