### ISSUE TITLE
tests failing with clang 12.0.0 on my mac (div by zero in atlas)

### ISSUE THREAD

**Issue by shlyaeva** [JCSDA-internal/soca#556]
## Description

I am running soca on Mac Big Sur, with jedi stack installed 2 days ago, and the following modules loaded:
```
Currently Loaded Modules:
  1) jedi-clang/12.0.0   4) jedi-mpich/3.3.2   7) pnetcdf/1.12.1  10) ecbuild/jcsda-internal-3.3.2.jcsda3  13) boost-headers/1.68.0  16) json-schema-validator/2.1.0
  2) szip/2.1.1          5) hdf5/1.12.0        8) nccmp/1.8.7.0   11) gsl_lite/0.37.0                      14) eigen/3.3.7
  3) mpich/3.3.2         6) netcdf/4.7.4       9) nco/4.7.9       12) pio/2.5.1-debug                      15) json/3.9.1
```

These tests are failing:
```
The following tests FAILED:
	 10 - test_soca_static_socaerror_init (Failed)
	 11 - test_soca_static_socaerrorlowres_init (Failed)
	 12 - test_soca_balance_mask (Failed)
	 13 - test_soca_create_kmask (Failed)
	 14 - test_soca_enspert (Failed)
	 25 - test_soca_errorcovariance (Failed)
	 26 - test_soca_linearmodel (Failed)
	 28 - test_soca_varchange_balance (Failed)
	 29 - test_soca_varchange_balance_TSSSH (Failed)
	 36 - test_soca_ensvariance (Failed)
	 38 - test_soca_ensrecenter (Failed)
	 39 - test_soca_parameters_bump_cor_nicas (Failed)
	 40 - test_soca_dirac_soca_cov (Failed)
	 41 - test_soca_dirac_socahyb_cov (Failed)
	 43 - test_soca_hofx_3d (Failed)
	 46 - test_soca_enshofx (Failed)
	 47 - test_soca_3dvar_soca (Failed)
	 48 - test_soca_3dvarbump (Failed)
	 49 - test_soca_3dvar_godas (Failed)
	 50 - test_soca_addincrement (Failed)
	 51 - test_soca_3dvarlowres_soca (Failed)
	 53 - test_soca_3dvarfgat (Failed)
	 54 - test_soca_3dvarfgat_pseudo (Failed)
	 55 - test_soca_3dhyb (Failed)
	 56 - test_soca_3dhybfgat (Failed)
	 57 - test_soca_letkf (Failed)
	 58 - test_soca_checkpointmodel (Failed)
```

I think the most important failures are in `test_soca_static_socaerror*_init` tests, the others fail because these ones fail.
They seem to be failing in atlas on division by zero:
```
10: --- Compute NICAS parameters
10: -------------------------------------------------------------------
10: --- Block: var-var
10:        Compute adaptive sampling, subset Sc1
10:           Average support radii (H/V):
10:              Level   1:    3050.56 km  /       1.00 vert. unit
10:           Estimated nc1 from horizontal support radius:     1592
10:           Compute horizontal subset C1:Caught SIGFPE: floating-point divide by zero
10: Caught SIGFPE: floating-point divide by zero
10: 0   liboops.dylib                       0x000000010630beb9 _Z14sigfpe_handleriP9__siginfoPv + 761
10: 1   libsystem_platform.dylib            0x00007fff204c0d7d _sigtramp + 29
10: 2   ???                                 0x000000000000ffff 0x0 + 65535
10: 3   libatlas.0.20.dylib                 0x0000000106542707 _ZN5atlas4grid7spacing8gaussian32gaussian_latitudes_npole_equatorEmPd + 615
10: 4   libatlas.0.20.dylib                 0x0000000106543972 _ZN5atlas4grid7spacing8gaussian30gaussian_latitudes_npole_spoleEmPd + 18
10: 0   liboops.dylib                       0x00000001074c3eb9 _Z14sigfpe_handleriP9__siginfoPv + 761
```

See full log below.

### To Reproduce:

All details above.

**output logs**
[failedtests.log](https://github.com/JCSDA-internal/soca/files/6346330/failedtests.log)

**Comment by guillaumevernieres** [comment]
Hooo, test `39 - test_soca_parameters_bump_cor_nicas (Failed)` is pure bump! I was worried this could have been in our "original" (and excelent) implementation of bump, but nope. Thanks for creating the ticket @shlyaeva .
Are you able to run the bump related tests with `fv3-jedi` ?

**Comment by shlyaeva** [comment]
Oh, interesting. I'll build and run fv3-jedi now -- haven't done it since the fresh reinstall of everything on Saturday.

**Comment by shlyaeva** [comment]
There are some fv3-jedi tests failing for me for two different reasons (crtm coeffs not unpacked and openmp linking problems which are likely due to my environment setup), but none of the fv3-jedi tests fail with a similar error in atlas.

**Comment by guillaumevernieres** [comment]
Thanks for testing @shlyaeva . We do use bump options that are not turned on in fv3-jedi (mask and network), so there's still hope we'll be able to blame @benjaminmenetrier  :)
I'm wondering if this is related to the failure that @clouden90 is seeing in the 1/4 deg config.

**Comment by shlyaeva** [comment]
I've put a couple extra debug prints in the atlas method [that was failing](https://github.com/JCSDA-internal/atlas/blob/e0b77091009dbc3281796b9e4b9d2a023fe28a5e/src/atlas/grid/detail/spacing/gaussian/Latitudes.cc#L244), and the error went away. I have a vague recollection of hearing that something like this happened in ioda or ufo when the compiler was optimizing excessively.

**Comment by guillaumevernieres** [comment]
> I've put a couple extra debug prints in the atlas method [that was failing](https://github.com/JCSDA-internal/atlas/blob/e0b77091009dbc3281796b9e4b9d2a023fe28a5e/src/atlas/grid/detail/spacing/gaussian/Latitudes.cc#L244), and the error went away. I have a vague recollection of hearing that something like this happened in ioda or ufo when the compiler was optimizing excessively.

@shlyaeva I definitely remember having the same issue in `soca` as well, adding a debug statement means that the block of code will sometimes not be handled the same way by the compiler. I still think we have a bug somewhere.

**Comment by shlyaeva** [comment]
@guillaumevernieres OK with closing this? I've "solved" by adding random debug prints in atlas; my guess is it's compiler's excessive optimization that was causing it for me. Sounded like the 1/4 degree issue was resolved by the latest BUMP update, and is probably not related?
