### ISSUE TITLE
VertConv for ocean BGC

### ISSUE THREAD

**Issue by liuxiao37k** [JCSDA-internal/soca#590]
## Description
Doing vertical convolution for ocean BGC seems to routinely cause solver issues (e.g. producing NaN after a few iterations). This problematic behavior is, however, not consistent when soca is built with GNU vs. Intel.

A temporal fix would be to simply turn `VertConv` off for ocean BGC and do it in BGC checkpoint applications. e.g. apply 2D surface analysis in 3D based on vertical distributions, but we need to revisit this issue to fundamentally solve the problem.

**Comment by travissluka** [comment]
@liuxiao37k, when I have some time, I can try to take a debugging exactly why NaNs are showing up if you can point me to a  which machine/compiler you're seeing this on. (I have orion access, but not hera)

**Comment by liuxiao37k** [comment]
> @liuxiao37k, when I have some time, I can try to take a debugging exactly why NaNs are showing up if you can point me to a which machine/compiler you're seeing this on. (I have orion access, but not hera)

@travissluka thank you so much for offering to help debug. An example can be seen from travis-ci soca-science ctests (failed, you can see crazy values shown up at 1st and 2nd var iterations and then NaNs):
https://travis-ci.com/github/JCSDA-internal/soca-science/builds/228928291
I don't see this issue on Hera when building with Intel. Perhaps building soca-science bgc_ckpts_bugfix branch with GNU on Orion will replicate the results? thanks again!

**Comment by guillaumevernieres** [comment]
@liuxiao37k , I'm going to have a crack at it today. ~~Could you point me to a configuration that makes the vertical convolution fail with bgc variables?~~ _edit: never mind, looking at your old PR_

**Comment by guillaumevernieres** [comment]
Closing this issue after talking to @liuxiao37k . To be revisited in the future, but bgc analysis is 2D for now.
