### ISSUE TITLE
First public release of soca

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#593]
## Description
First public release of `soca`

**Comment by travissluka** [comment]
do we care about workflow for this release (`soca-science`) ? Or are we just going to ignore that and include `soca-workflow` in a following release when it's ready?

**Comment by guillaumevernieres** [comment]
> do we care about workflow for this release (`soca-science`) ? Or are we just going to ignore that and include `soca-workflow` in a following release when it's ready?

Undecided yet. I'm up for keeping it simple, and not releasing `soca-science`.
