### ISSUE TITLE
Document soca

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#594]
## Description
~~Use RTD and document.~~ We're not doing that ...
~~Some work was done in this branch: [read the doc branch](https://github.com/JCSDA-internal/soca/tree/feature/dontrtd)~~
Use doxygen for code documentations 

Note: Mimic what was done for `fv3-jedi`. The `soca` Documentation should go [here](https://github.com/JCSDA/jedi-docs/tree/develop/docs/inside/jedi-components/)

Todo list for the doc:

- [x] Tutorial (G)
- [x] UFO (G)
- [x] Model (G or T)
- [x] Variable changes (T)
- [x] Check State/Incr and Getvalue. (T)

**Comment by travissluka** [comment]
@guillaumevernieres state/increment seem fine. We have nothing configurable for getvalues, unlike fv3/mpas, so short of saying "there's nothing configurable" i'm not sure what else there is worthwhile to document for that

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres state/increment seem fine. We have nothing configurable for getvalues, unlike fv3/mpas, so short of saying "there's nothing configurable" i'm not sure what else there is worthwhile to document for that

Nice, so on to variable transforms?

**Comment by guillaumevernieres** [comment]
Virtual high 5 to those involved.
Closing this issue :tada:
