### ISSUE TITLE
Introduce vertical localization to soca LETKF

### ISSUE THREAD

**Issue by frolovsa** [JCSDA-internal/soca#598]
## Description
To pave the path for coupled DA, i would like to introduce vertical localization in the ocean LETKF. I am creating this as an Epic. I will add sub-issues later after we discuss this in this issue first. 

## Solution
I am advocating of doing it through GETKF (See document attached).
The document gives the background but more importantly, i have a question to @benjaminmenetrier and @guillaumevernieres if i can use GenPertB application to draw sample for B such as B=Kvert*Cvert*Kvert' ? And if yes, can one of you help me set up a yaml file for it? 

I am also thinking that we should implement a traditional obs space vertical localization in JEDI. SOCA is an obvious place to try this implementation first. 

## Alternatives
We can run a separate solver for the mixed layer vs deep ocean like @travissluka did in the past. But i am afraid that doesn't generalize well to coupled DA. We can always try it and compare it to GETKF. 

## Related to
[Adding vertical localization to ocean local volume solver.pdf](https://github.com/JCSDA-internal/soca/files/6673140/Adding.vertical.localization.to.ocean.local.volume.solver.pdf)

**Comment by guillaumevernieres** [comment]
@frolovsa : Just replace the covariance model by the identity (there is one in saber).

**Comment by shlyaeva** [comment]
@frolovsa looks like all issues in this epic were closed 🎉 
can the epic be closed now too?

**Comment by frolovsa** [comment]
yes
