### ISSUE TITLE
add dual res test

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#606]
## Description
We need to add a test for the dual res var.
I thought PR #605 was ready to go, but it turns out it breaks the dual res var in soca-science because `hocn` is required for the remapping, but `hocn` isn't allowed to be part of increment any more with that PR.

**Comment by travissluka** [comment]
nevermind, I don't know what i'm talking about

**Comment by guillaumevernieres** [comment]
2 free points! Nice! Gotta do more of those.
