### ISSUE TITLE
how does one run ctests on orion? Missing nco tools

### ISSUE THREAD

**Issue by frolovsa** [JCSDA-internal/soca#630]
## Description
Looks like letkf ctests require nco tools (ncks etc). These tools are not available by default in the jedi modules on orion. If i "module load nco" this doesn't help because ncks is still not added to the path. 

What do people do on orion if the want to run letkf ctests?

**Comment by travissluka** [comment]
look at 
https://github.com/JCSDA-internal/soca-science/blob/develop/configs/machine/machine.orion.gnu
or 
https://github.com/JCSDA-internal/soca-science/blob/develop/configs/machine/machine.orion.intel

**Comment by rickgrubin** [comment]
**Suggestion**: remove `ecbuild35` from the `module load` commands in the scripts you note -- it's no longer necessary (the `default` modules are equivalent, and the `ecbuild35.lua` file will go away when we move to a group / role account module tree).

**nco**: `nco/4.9.3` is provided via the system modules, so `module load nco/4.9.3` will provide what you need.

**Comment by frolovsa** [comment]
that was the trick i had to load a specific version of nco. module load nco was not enough. 
Thank you guys for your help.

**Comment by guillaumevernieres** [comment]
@rickgrubin , can you keep these modules alive? We're not going to want to point to `default` most of the times. `Default` is fine for development work when you don't care about reproducibility, but not for benchmarking/testing.
 
What we need is a set of modules that we can reliably count on throughout testing/experimenting periods. Wiping the modules while people are running experiments is a bad idea and shouldn't be done. Renaming perhaps, but I'm not sure why you would want to go through the work overhead of doing that ...

**Comment by rickgrubin** [comment]
> @rickgrubin , can you keep these modules alive? We're not going to want to point to `default` most of the times. `Default` is fine for development work when you don't care about reproducibility, but not for benchmarking/testing.
> 
> What we need is a set of modules that we can reliably count on throughout testing/experimenting periods. Wiping the modules while people are running experiments is a bad idea and shouldn't be done. Renaming perhaps, but I'm not sure why you would want to go through the work overhead of doing that ...

`default` modules are the same as `ecbuild35` -- if you say `module load jedi/gnu-openmpi`, it's the same as saying `module load jedi/gnu-openmpi/ecbuild35`

**Comment by guillaumevernieres** [comment]
@rickgrubin I assume your default is pointing to your latest stack, so while that works now, at some point default is going to point to something that isn't `ecbuild35`, or whatever stack we decided to build with . That's why we won't point to default most of the time. Makes sense?
