### ISSUE TITLE
SOCA RELEASE: Oct 29

### ISSUE THREAD

**Issue by mmiesch** [JCSDA-internal/soca#640]
Push the master and develop branches (with tags) of these repos to Public (add any that I am missing)

- [ ] soca
- [ ] MOM6

Then, for these repos on JCSDA, set up

- [ ] repo settings
- [ ] branch rules
- [ ] access permissions

Push the latest tags / master branches of these repos to public (add any that I am missing):

- [ ] jedi-docs

**Comment by guillaumevernieres** [comment]
@mer-a-o , could you update us in this issue when you get a reply from github support?
No need to extend the release work over the week end. We can finish up the repo move Monday or whenever github fixes the issue.

**Comment by mer-a-o** [comment]
Sure, I will update this issue when I get a reply.

**Comment by mer-a-o** [comment]
@guillaumevernieres @travissluka I haven't heard back from GitHub support yet. I will let you know when I get a reply.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres @travissluka I haven't heard back from GitHub support yet. I will let you know when I get a reply.

Thanks for the update @mer-a-o . I just edited @mmiesch 's issue description. We need to "move" 2 repositories, soca and our fork of MOM6.

**Comment by guillaumevernieres** [comment]
FYI @mer-a-o I just rename the public SOCA to soca ... Asking for forgivness  ... :)

**Comment by mer-a-o** [comment]
@guillaumevernieres, That's fine. :) 
I'm trying to push master branch on jcsda-internal/soca to public now. I will let you know once it's done.

**Comment by mer-a-o** [comment]
@guillaumevernieres, I updated the master branch on jcsda/soca and created the tag and release.

**Comment by mer-a-o** [comment]
@guillaumevernieres, in `bundle/CMakeLists.txt` I see:
```
ecbuild_bundle( PROJECT gsw   GIT "https://github.com/jcsda-internal/GSW-Fortran.git"  UPDATE BRANCH release/soca-1.0.0 )

ecbuild_bundle( PROJECT mom6  GIT "https://github.com/jcsda-internal/MOM6.git"  UPDATE BRANCH release/soca-1.0.0 RECURSIVE )
```
We are using jcsda-internal for gsw and mom6. Do you want to change this? If yes we need to either create tags 1.0.1 for jcsda and jcsda-internal or delete 1.0.0 tags and recreate them.

**Comment by guillaumevernieres** [comment]
Thanks @mer-a-o 
We still need to move MOM6 to JCSDA and edit that line https://github.com/JCSDA/soca/blob/b858ba06913f615c2e123db59b53975d7cba5517/bundle/CMakeLists.txt#L59

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres, in `bundle/CMakeLists.txt` I see:
> 
> ```
> ecbuild_bundle( PROJECT gsw   GIT "https://github.com/jcsda-internal/GSW-Fortran.git"  UPDATE BRANCH release/soca-1.0.0 )
> 
> ecbuild_bundle( PROJECT mom6  GIT "https://github.com/jcsda-internal/MOM6.git"  UPDATE BRANCH release/soca-1.0.0 RECURSIVE )
> ```
> 
> We are using jcsda-internal for gsw and mom6. Do you want to change this? If yes we need to either create tags 1.0.1 for jcsda and jcsda-internal or delete 1.0.0 tags and recreate them.

Oops, sorry. Yes, we need to release both mom6 and gsw. I vote for deleting and recreating the 1.0.0 tag.
