### ISSUE TITLE
create release branches

### ISSUE THREAD

**Issue by mmiesch** [JCSDA-internal/soca#641]
As soon as we can (by Oct 9), create `release/soca-1.0.0` branches of (add if I am missing anything):
- [x] MOM6
- [x] gsw
- [x] soca
- [x] jedi-docs

**Comment by mmiesch** [comment]
The release branch for jedi-docs has been created.  PRs for soca documentation should go to there so we can finalize them before publishing them.

**Comment by guillaumevernieres** [comment]
Not too bad, just 1 commit behind what's in `develop` works the the tagged repos from the mpas release. 
I'll push the `release/soca-1.0.0` branch in a few minutes.
@travissluka , we're "only" 1451 commits behind GFDL for MOM6 ...

**Comment by guillaumevernieres** [comment]
Just pushed `release/soca-1.0.01` for **gsw**, **soca** and **mom6**

**Comment by guillaumevernieres** [comment]
Closing this issue. Admin work is done ... for now.
I added branch protection for **soca**, so we will have to issue PR's to merge into `release/soca1.0.0` , same goes for `jedi-docs` @mmiesch added protections for `release/*` branches.
