### ISSUE TITLE
FREEZE CODE Oct 22

### ISSUE THREAD

**Issue by mmiesch** [JCSDA-internal/soca#642]
Freeze code one week before the release for testing purposes.  This does not apply to base repos like oops, saber, ioda, ufo, and jedi-cmake if we use the most recent existing releases/tags.  And, it does not apply to jedi-docs, which can be changed right up until the release date.  So, this leaves (add if I am missing anything):

- [ ] soca
- [ ] MOM6 forked from GFDL

**Comment by travissluka** [comment]
@guillaumevernieres close this?

**Comment by guillaumevernieres** [comment]
omg!!! we closed an issue with no milestone :boom:  I'm going to tell @gibbsp ...

**Comment by mmiesch** [comment]
You can throw me under the bus - I'll disappear soon

**Comment by gibbsp** [comment]
You're supposed to be using sprints! Looks like we need some follow-up training.
