### ISSUE TITLE
Advertising SOCA 1.0.0 Release

### ISSUE THREAD

**Issue by KShanahan24** [JCSDA-internal/soca#645]
Kat to advertise the release in the usual places:

- [x] Create a SOCA release page and add 1.0.0 information 
- [x] Send out a news blast about the release; SOCA team to give me information for the blast (likely similar to what is on the website)
- [x] Submit news blog post link to UCAR Currents 
- [x] UCP Newsletter article (UCP has specified that we need to provide at least one figure now for articles)

Due dates for the last two items to come.

**Comment by KShanahan24** [comment]
Hi all - Is there a plan to get me the items for the website and the news blast tomorrow?

**Comment by guillaumevernieres** [comment]
> Hi all - Is there a plan to get me the items for the website and the news blast tomorrow?

Can we use GPT-3?
