### ISSUE TITLE
test test_soca_create_kmask fails to run on hera

### ISSUE THREAD

**Issue by frolovsa** [JCSDA-internal/soca#649]
## Description
when building on hera with intel, kmask ctest fails. Tests listed before kmask succeed. 

13: Test command: /usr/bin/python3 "/home/Sergey.Frolov/work/jedi/src/soca/sqrtVertLoc/bundle/soca/test/Data/create_kmask.py" "TEST_DEPENDS" "test_static_socaerror_init" "test_balance_mask"
13: Test timeout computed to be: 10000000
13: Traceback (most recent call last):
13:   File "/home/Sergey.Frolov/work/jedi/src/soca/sqrtVertLoc/bundle/soca/test/Data/create_kmask.py", line 2, in <module>
13:     import netCDF4
13:   File "/home/Sergey.Frolov/.local/lib/python3.6/site-packages/netCDF4-1.5.4-py3.6-linux-x86_64.egg/netCDF4/__init__.py", line 3, in <module>
13:     from ._netCDF4 import *
13:   File "netCDF4/_netCDF4.pyx", line 1212, in init netCDF4._netCDF4
13:   File "/home/Sergey.Frolov/.local/lib/python3.6/site-packages/cftime-1.2.1-py3.6-linux-x86_64.egg/cftime/__init__.py", line 1, in <module>
13:     from ._cftime import utime, JulianDayFromDate, DateFromJulianDay, UNIT_CONVERSION_FACTORS
13:   File "__init__.pxd", line 918, in init cftime._cftime
13: ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
1/1 Test #13: test_soca_create_kmask ...........***Failed    0.33 sec

### To Reproduce:
clone soca. 
build soca. 
run ctests on compute node.

**Comment by guillaumevernieres** [comment]
@frolovsa , looks like your python install isn't compatible with one of the soca python script.

**Comment by frolovsa** [comment]
Right. i think i figured it out.
