### ISSUE TITLE
Adapt SOCA to work with https://github.com/JCSDA-internal/oops/pull/1333

### ISSUE THREAD

**Issue by danholdaway** [JCSDA-internal/soca#684]
VariableChange factory is being removed from OOPS. Implement the factory in SOCA instead.

**Comment by guillaumevernieres** [comment]
We were going to play :rock: :page_with_curl:  :scissors:  to figure out who would be doing that work ... No need now! Thanks for volunteering @danholdaway :+1:

**Comment by danholdaway** [comment]
No problem. Should be fairly straightforward having done it for fv3.

**Comment by danholdaway** [comment]
Bumping this back to you @guillaumevernieres and @travissluka. Branch name feature/changevar-stage1. I've added the factories and think everything should be in place that is needed. But now I think things might move a bit quicker with more knowledge of soca fields than I have. I think the initial thing to focus on is the hofx3d test and why it's failing. I have tracked the problem to this line: https://github.com/JCSDA-internal/soca/blob/abab602405d9eabbe140f15353fb5ef5484691da/src/soca/VariableChange/VariableChange.cc#L47 Essentially the transform occurs as you would expect. But then when it tries to copy the field names seem to be different between the two states and it complains about not finding cicen. In that operator= function there seems to a be a `%get` based on `name` when I might have expected `%metadata%name`, which seems to be what you make consistent between all fields. I tried changing a few things but couldn't make progress and was worried I might end up creating a lot more problems.

Here's a summary of what's changes in the branch:

- Added a factory for VariableChange
- Added a factory for LinearVariableChange and made it a vector of linear variable changes.
- Added functions called has_fields and update_fields to soca_fields_mod. The idea here was to provide functions for checking if the variables determining the behaviour the variable change are already satisfied. This doesn't work because soca transforms change the meaning of variables without changing the variable. As such it means it would think every transform needs to be the identity. I think this also means you might not be able to have an identity variable transform and one might need to be explicitly added. Some tests are failing, I suspect, for this reason. When it should be Id it defaults to Model2GeoVaLs. Right now these functions I've added don't work but we could improve the representation of variables with different meanings and use them in the anticipated way. At that above link you can see an example of how I think it should be working.
- Have updated some yamls but there are still some to do. 

Let me know if I can help. Once you have the hofx3d working you could bump back to me to finish if that makes sense.

**Comment by guillaumevernieres** [comment]
Thanks for doing all that work @danholdaway , you definitely saved us quite a bit of time!
I've got the hofx3d working, but I think we (@travissluka and myself) should probably work on the rest of the issues just so we are more aware of the extent of the required changes (I naively wasn't expecting this work to be that involved ... oops).
