### ISSUE TITLE
Rossby localization will not work properly with Halo distribution

### ISSUE THREAD

**Issue by frolovsa** [JCSDA-internal/soca#686]
## Description
I am working on modifying how obs localizations are specified in yamls. I noticed that Rossby localization does not have parameter "lengthscale". This parameter is currently needed to specify how many obs are kept on each PE in a "halo" around the mpi tile. This is done by specifying
`driver: update obs config with geometry info: true`
The update is performed in: 
https://github.com/JCSDA-internal/oops/blob/4315d3d2c3b23cb4c8057857425c5d24be7855ec/src/oops/runs/LocalEnsembleDA.h#L90

## Proposed Solution
I am still working on the new way to specify the lengthscale for Halo distribution. So lets hold tight and see what might work out. Most likely, you will specify something like:
`obs localization: lengthscale for horizontal halo distribution: (in meters)`
This would be a global value that will not change with altitude so most tiles will have to overprovision obs. Would that work, @travissluka ?

## what to do next
I dont think you guys need to do anything at the moment. just dont expect Rossby to work with Halo distribution. GC99 should still work.

**Comment by YongzuoLi-NOAA** [comment]
@frolovsa The following combination does not work
driver:
  update obs config with geometry info: true
observations:
  - obs space:
      distribution: Halo
    obs localization: # note, this is only used for LETKF
      localization method: Gaspari-Cohn
      lengthscale: 200e3
