### ISSUE TITLE
JCSDA/soca develop not up to date with JCSDA-internal/soca develop

### ISSUE THREAD

**Issue by shlyaeva** [JCSDA-internal/soca#687]
I noticed that JCSDA/soca develop branch hasn't been updated since November 5.
For other repos we have some hooks that were set up by Mark to keep develop up-to-date between JCSDA and JCSDA-internal. I wonder if that wasn't turned on for soca.

**Comment by guillaumevernieres** [comment]
Thanks for letting us know @shlyaeva .

**Comment by shlyaeva** [comment]
I think this is resolved now; closing.
