### ISSUE TITLE
The LETKF people broke soca!

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#688]
## Description
Looks like [ufo PR#1528](https://github.com/JCSDA-internal/ufo/pull/1528) broke soca ...
@frolovsa @weihuang-jedi , could you finish up your branch feature/soca_letkf_localization? Or is it ready for re-review? In which case mark it as such.

**Comment by frolovsa** [comment]
please review and merge 
https://github.com/JCSDA-internal/soca/pull/636

**Comment by guillaumevernieres** [comment]
I can't merge until you resolve the conflicts first @frolovsa

**Comment by frolovsa** [comment]
ok. i merged things and pushed them up. lets see what Travis CI has to say.
