### ISSUE TITLE
Read geoval is "broken"

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#691]
## Description
I am getting rid of the method that reads the atmospheric geovals in getvalues . Are you OK with that @HamidehGMAO ? That would mean not being able to use the crtm ufo from soca anymore.
@shlyaeva and @ytremolet are close to a 2 model h(x), which is what we will be using in the long term.

**Comment by HamidehGMAO** [comment]
ah OK, sounds good.

**Comment by travissluka** [comment]
broken due to https://github.com/JCSDA-internal/oops/pull/1574

**Comment by shlyaeva** [comment]
Yep, sorry, I forgot that soca creates GeoVaLs internally.
