### ISSUE TITLE
run breaks when the number of observations are less than PEs used

### ISSUE THREAD

**Issue by kbhargava** [JCSDA-internal/soca#702]
## Description
When the number of observations are less than the number of PEs used to run experiments in soca-science the steps run.var/hofx fails. It hangs at the step `GetValues<MODEL, OBS>::fillGeoVaLs`
@travissluka mentioned that it could be because noaa19 has fewer obs than PEs, and something in `fillGeoVaLs` is trying to do an MPI reduce with all PEs but the PEs with 0 obs are skipping the MPI call

### To Reproduce:
Run any DA or noDA experiment for 2015092012 using the sst_noaa19 obs from the R2D2 database located at `/work/noaa/marine/marineda/r2d2/obs/jcsda_soca/ob/benchmark_v1` on orion. The experiment breaks at run.var/hofx step. 

## Output
**output logs**
On orion the log can be seen at `/work/noaa/marine/kritib/runs/HAT10/1135x633x50/test_sstnoaa19/logs/2015092012/run.var  `

**Comment by travissluka** [comment]
@kbhargava this is apparently what we were talking about today.
I'm hoping that https://github.com/JCSDA-internal/soca/issues/722 will fix this issue for us. Fingers crossed
