### ISSUE TITLE
soca_dirac produces erroneous results when using "hybrid" covariance model

### ISSUE THREAD

**Issue by kbhargava** [JCSDA-internal/soca#704]
## Description
When soca_dirac.x is run with hybrid covariance model, the results are not as expected. Tried running experiment that would compute covariance using dual correlation length scales. The resulting dirac results for SSH were smaller by a factor of about 100 compared with running with single length scales.

## Output

Attaching file showing the results using large corr length scales, 10x rossby_radius just for sanity check,  (left), small scale,1x rossby_radius,  (middle) and equally weighted hybrid (right).

![image (3)](https://user-images.githubusercontent.com/22651193/150852060-5c008ae0-c24b-4f70-b40e-b0789279ff1b.png)

**Comment by travissluka** [comment]
turns out dirac works fine, it's just that the output files are being overwritten. Issue to be addressed by https://github.com/JCSDA-internal/oops/issues/1634
