### ISSUE TITLE
Someone broke soca

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#711]
## Description
This PR (https://github.com/JCSDA-internal/ioda/pull/578) breaks soca travisCI builds

See build log https://app.travis-ci.com/github/JCSDA-internal/soca/builds/245744926

`udunits_lib` is not found when compiling UFO

**Comment by travissluka** [comment]
@rhoneyager it seems that the `udunits` dependency isn't being propagated forward when UFO tries to build from a IODA outside the bundle.

**Comment by climbfuji** [comment]
Could be related to https://github.com/JCSDA-internal/ioda/issues/586? Which machine are you on? We should try again tomorrow morning after the missing dependencies were installed on Cheyenne.

**Comment by guillaumevernieres** [comment]
> Could be related to [JCSDA-internal/ioda#586](https://github.com/JCSDA-internal/ioda/issues/586)? Which machine are you on? We should try again tomorrow morning after the missing dependencies were installed on Cheyenne.

it's failing on travis-ci @climbfuji . Was the container updated yesterday?

**Comment by travissluka** [comment]
@guillaumevernieres @climbfuji no this is unrelated to ioda#586 and has nothing to do with the containers. `udunits` is there and is being found by IODA when it is built. This issue should actually be moved to either UFO or IODA repos.

@climbfuji as some background: SOCA is built differently than other projects when testing on TravisCI. Each repository is built separately, installed, and cached. We don't use a bundle when building on TravisCI. That way we don't have to rebuild the entire bundle if something in a single repo changes. It gets our TravisCI build and test times down  to as low as 15 minutes sometimes (instead of the wonderful hour and a half). 

The problem here is now that udunits is actually being used by IODA, it needs to also be used by the downstream repos. However it isn't being found by downstream repos when UFO is not built as part of the bundle because they don't have their own `find_package( udunits ... )` and/or they are not correctly requiring udunits when they call `find_package( ufo ...)`. This problem has happened many times before when a new dependency is used.

**Comment by climbfuji** [comment]
Makes sense (your explanation), thanks @travissluka. Yet, the problem on cheyenne is somewhat related in the sense that a new dependency was added/is now used in IODA that wasn't there before, and it wasn't tested on Cheyenne.

**Comment by rhoneyager** [comment]
> @rhoneyager it seems that the `udunits` dependency isn't being propagated forward when UFO tries to build from a IODA outside the bundle.

Oops. https://github.com/JCSDA-internal/ioda/pull/587 and https://github.com/JCSDA-internal/jedi-cmake/pull/15 should fix this.

**Comment by travissluka** [comment]
back up and running!
