### ISSUE TITLE
SOCA

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#715]

**Comment by guillaumevernieres** [comment]
a mouse operating issue probably ...

**Comment by travissluka** [comment]
@guillaumevernieres I just noticed this. "soca" is closed? so we're done with soca !?!? There's nothing left to do? So that's why you left.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres I just noticed this. "soca" is closed? so we're done with soca !?!? There's nothing left to do? So that's why you left.

Yes, but it looks like I was wrong. The identity tlm/ad has disappeared from soca! 
Could that be my first **unkind** soca contribution?

**Comment by ytremolet** [comment]
What?!?!? No more identity??? Did @guillaumevernieres take that highly sensitive technology away with him?
