### ISSUE TITLE
PR#703 broke the tests added by PR#708

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#718]
## Description
I disabled the tests that were added by https://github.com/JCSDA-internal/soca/pull/708 (bump3d) because the yaml files weren't working after https://github.com/JCSDA-internal/soca/pull/703 (anisotropic functions). Something about `cor_rh` vs `rh`, and how the input and output sections of the yaml needed to be changed but bump was complaining.... I gave up after 5 minutes, because it is a friday afternoon and I don't want to leave things broken.

@guillaumevernieres

**Comment by guillaumevernieres** [comment]
~~Weird, the tests are ok on my machine.~~

**Comment by guillaumevernieres** [comment]
> ## Description
> 
> I disabled the tests that were added by #708 (bump3d) because the yaml files weren't working after #703 (anisotropic functions). Something about `cor_rh` vs `rh`, and how the input and output sections of the yaml needed to be changed but bump was complaining.... I gave up after 5 minutes, because it is a friday afternoon and I don't want to leave things broken.
> 
> @guillaumevernieres

Thanks for the heads up @travissluka . Happy to sort it out next week.
