### ISSUE TITLE
Theia Test Failures with gcc7.3

### ISSUE THREAD

**Issue by flampouris** [JCSDA-internal/soca#72]
The following tests are failing at Theia:

        262 - iodaconv_lib-python_coding_norms (Failed)
	263 - iodaconv_gsi-ncdiag_coding_norms (Failed)
	265 - iodaconv_godae_coding_norms (Failed)
	267 - iodaconv_hgodas_coding_norms (Failed)
	270 - iodaconv_met-office_coding_norms (Failed)
	271 - iodaconv_ncep_coding_norms (Failed)
	308 - test_soca_enspert (Failed)
	309 - test_soca_ensvariance (Failed)
	320 - test_soca_bkgerrgodas (Timeout)
	326 - test_soca_3dvargodas (Failed)
	328 - test_soca_4dhybrid (Failed)

**Comment by travissluka** [comment]
a memory corruption issue was fixed with PR #97
I'd be curious to see if this is fixed on Theia now. Namely the tests:
- test_soca_enspert
- test_soca_ensvariance
- test_soca_bkgerrgodas
- test_soca_3dvargodas
