### ISSUE TITLE
[BUG] Interpolation doesn't work

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#736]
## Description
I had the brilliant idea yesterday to update my build ... Oops. Our soca_var for the S2S initialization is now crashing in the interpolation. I won't have time to dig into it this week (reverting to whatever works) but here it is for now until I have more time to document the issue: 

### To Reproduce:
Just run a realistic case. Same issue when running at 1deg and 1/4deg.

## Output
:boom: 

**output logs**
``` 
NOTE from PE     0: MPP_IO_SET_STACK_SIZE: stack size set to    8640000.
Exception: Assertion failed: root_ in kNearestNeighbours, line 91 of /work/noaa/da/jedipara/opt/modules/intel-2020.2/impi-2020.2/eckit/ecmwf-1.16.0/include/eckit/container/sptree/SPTree.h
Assertion failed: root_ in kNearestNeighbours, line 91 of /work/noaa/da/jedipara/opt/modules/intel-2020.2/impi-2020.2/eckit/ecmwf-1.16.0/include/eckit/container/sptree/SPTree.h
backtrace [38] stack has 23 addresses
```

**Comment by travissluka** [comment]
just off the top of my head....
I'm guessing this is happening when running with a high enough PE count that some PE's have no ocean points, and apparently the KD tree doesn't like to be queried when it has no points.

Assuming this will all get magically fixed when @fmahebert implements native masking in the interpolator, and such points would have a proper `missing_value` returned instead

**Comment by guillaumevernieres** [comment]
> just off the top of my head.... I'm guessing this is happening when running with a high enough PE count that some PE's have no ocean points, and apparently the KD tree doesn't like to be queried when it has no points.
> 
> Assuming this will all get magically fixed when @fmahebert implements native masking in the interpolator, and such points would have a proper `missing_value` returned instead

@travissluka , you can see the layout in [this issue](https://github.com/JCSDA-internal/soca/issues/732) ... So yes, quite a few pe's are doing nothing. No hurries on our side.
