### ISSUE TITLE
bug on soca build?!

### ISSUE THREAD

**Issue by HamidehGMAO** [JCSDA-internal/soca#739]
## Description
It seems I can't build SOCA (with intel on discover). Anyone else has this problem? 
<img width="991" alt="image" src="https://user-images.githubusercontent.com/40796921/165174762-2dc8bf75-7d0b-4f63-be21-4b474891ba67.png">

**Comment by travissluka** [comment]
i'm guessing you're using an old version of saber. try doing a `make update` first

**Comment by HamidehGMAO** [comment]
hmm, it was a clean build, but I see the last merge on soca could solve this
