### ISSUE TITLE
[Bug] Interpolation doesn't work

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#748]
## Description
... And hasn't for a while. I waited for the last oops PR and the updated atlas before writing this ticket:
We are having issues with the 1/4 degree global MOM6 when assimilating more than 1 obs space, it has been this way for quite a few commits, each giving a traceback slightly different than the last. 

### To Reproduce:
You can use my `scratch` here:
```console
/work/noaa/marine/Guillaume.Vernieres/runs/test-interp/scratch-ref
```
I won't erase it for a while, but I might change the `var.yaml`.

1. build the latest `soca` develop 
2. make a copy of `scratch-ref` somewhere
3. `srun -n 480 soca_var.x var.yaml` will crash with the following as an example of traceback:
```console
[...]
OOPS_TRACE LocalUnstructuredInterpolator::LocalUnstructuredInterpolator start
OOPS_TRACE LocalUnstructuredInterpolator::LocalUnstructuredInterpolator done
OOPS_TRACE LocalInterpolator<MODEL>::LocalInterpolator done
OOPS_TRACE LocalInterpolator<MODEL>::LocalInterpolator starting
==== backtrace (tid: 231470) ====
 0 0x000000000024a510 eckit::Value::operator+()  ???:0
 1 0x000000000024b123 eckit::Value::makeOrderedMap()  ???:0
 2 0x00000000000e7507 eckit::LocalConfiguration::LocalConfiguration()  ???:0
 3 0x0000000000629fbc atlas::functionspace::FunctionSpaceImpl::FunctionSpaceImpl()  ???:0
 4 0x000000000061b185 atlas::functionspace::detail::PointCloud::PointCloud()  ???:0
 5 0x000000000061b0e9 atlas::functionspace::PointCloud::PointCloud()  ???:0
 6 0x0000000000198b6d soca::Geometry::Geometry()  /work/noaa/marine/Guillaume.Vernieres/runs/test-interp/soca-science/bundle/soca/src/soca/Geometry/Geometry.cc:52
 7 0x0000000000198b6d std::_Tuple_impl<0ul, atlas::functionspace::PointCloud*, std::default_delete<atlas::functionspace::PointCloud> >::_M_head()  /apps/gcc-10.2.0/gcc-10.2.0/include/c+\
+/10.2.0/tuple:201
 8 0x0000000000198b6d std::__get_helper<0ul, atlas::functionspace::PointCloud*, std::default_delete<atlas::functionspace::PointCloud> >()  /apps/gcc-10.2.0/gcc-10.2.0/include/c++/10.2.0\
/tuple:1284
[...]
```

**Comment by guillaumevernieres** [comment]
@travissluka , @kbhargava , no issues with the regional MOM6? I'll try to dig into this problem today. Will post here if I find something.

**Comment by travissluka** [comment]
well, @frolovsa, it seems you're not the only one having problems with the interpolation

**Comment by kbhargava** [comment]
> @travissluka , @kbhargava , no issues with the regional MOM6? I'll try to dig into this problem today. Will post here if I find something.

My experiments were failing last Friday. Orion had scheduled maintenance yesterday so just diving deep into the issue today.

**Comment by shlyaeva** [comment]
Tagging @fmahebert in case he has ideas on what may be wrong.

**Comment by fmahebert** [comment]
No ideas immediately from given info...

**Comment by fmahebert** [comment]
I don't see anything clearly amiss in the line of code from the backtrace, that seems to roughly match fv3-jedi.

But what doesn't match fv3-jedi is that SOCA doesn't appear to distinguish between fields with/without halos. In fv3-jedi the geometry has two different FunctionSpaces, so we can construct fields (from FunctionSpaces) with/without halos depending on the needs of interpolation or saber.

How is this handled in SOCA? Perhaps I'm just misreading the code?

**Comment by travissluka** [comment]
@fmahebert , trying to refresh my memory, but I don't think the `atlas...()` methods are being used by the interpolation, just the `Geometry::latlon()` methods

**Comment by fmahebert** [comment]
@travissluka Ah yes, I see now where the halo is coming at the Fortran interface for the latlon method... thanks!

**Comment by travissluka** [comment]
@guillaumevernieres you using intel or gnu?

**Comment by travissluka** [comment]
ok, i'm able to duplicate the problem on orion.
I don't think it's the interpolation itself, but rather, for some reason the `Geometry` class that comes into the interpolator class is corrupted and can't be copied. Still trying to figure it out.

**Comment by travissluka** [comment]
I think I found the problem. We're running out of memory. When reducing to just one obs space, it runs but with the following stats:

```
OOPS_STATS ----------------------------------------------------------------------------------
OOPS_STATS --------------------------- Object counts ----------------------------------------
OOPS_STATS ----------------------------------------------------------------------------------
OOPS_STATS                                      Total  Simult. Remain    Avg (Mb)    HWM (Mb)
OOPS_STATS oops::LocalInterpolator         :     1440     960        
OOPS_STATS soca::Geometry                  :     3960     993      17
OOPS_STATS soca::UnstructuredInterpolator  :     2400    1440     

OOPS_STATS ---------------------------------- Parallel Timing Statistics ( 480 MPI tasks) -----------------------------------
OOPS_STATS Run end                                  - Runtime:    108.40 sec,  Memory: total:  1818.54 Gb, per task: min =     3.78 Gb, max =     4.77 Gb
```

That's a LOT of geometry and interpolator classes open at once. @fmahebert This is just one obs space,  any idea why there would be so many unstructured interpolators open at once?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres you using intel or gnu?

@travissluka intel

**Comment by travissluka** [comment]
looking at where interpolators are being created inside oops, I suspect this PR is when things started breaking for soca https://github.com/JCSDA-internal/oops/pull/1732

**Comment by kbhargava** [comment]
My experiments do not fail. However, the stats differ a bit from my older runs
```
OPS_STATS--
OOPS_STATS ----------------------------------------------------------------------------------
OOPS_STATS --------------------------- Object counts ----------------------------------------
OOPS_STATS ----------------------------------------------------------------------------------
OOPS_STATS                                      Total  Simult. Remain    Avg (Mb)    HWM (Mb)

OOPS_STATS oops::LocalInterpolator         :      360     240--------
OOPS_STATS soca::Geometry                  :    20937     569     311    
OOPS_STATS soca::UnstructuredInterpolator  :      480     360--------
```

Stats from my older experiments looked like:
```
OPS_STATS--
OOPS_STATS ----------------------------------------------------------------------------------
OOPS_STATS --------------------------- Object counts ----------------------------------------
OOPS_STATS ----------------------------------------------------------------------------------
OOPS_STATS                                      Total  Simult. Remain    Avg (Mb)    HWM (Mb)

OOPS_STATS soca::Geometry                  :     1242     144      89
```

**Comment by fmahebert** [comment]
@travissluka For each interpolation, each MPI rank makes one interpolator _per MPI rank_. This is because of how (for now) the data is split up: a different interpolator fills each rank's MPI buffer before the interpolation results are sent back to their owning processors. So looking at your numbers, I see 1440/480 = 3 LocalInterpolators per rank, and 2400/480 = 5 UnstructuredInterpolators per rank. That's not terribly many. Could this come down to the number of fields/components you are interpolating in this particular GetValues?

Pinging also @ytremolet in case he has insights.

**Comment by travissluka** [comment]
@fmahebert thanks that makes sense.

I think I figured out what the problem is (it's on the soca side), I'm testing it out now.
