### ISSUE TITLE
Adapt LinearVariableChange to OOPS#1800 

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#768]
## Description

See description of changes neeed in https://github.com/JCSDA-internal/oops/pull/1800

@shlyaeva @svahl991.... @guillaumevernieres claims this will break SOCA because we rely on `bkg` in some of the linear var changes.

**Comment by svahl991** [comment]
> this will break SOCA because we rely on bkg in some of the linear var changes.

So, to be clear, you're saying there are linear var changes where, in order to do `setTrajectory`, you need both a background state and a (different) first guess state at the same time? From my understanding and conversations with @ytremolet  I did not think that that this would ever be the case. Maybe we should talk.

I thought you were joking this morning when you said we were going to break SOCA again!

**Comment by guillaumevernieres** [comment]
> > this will break SOCA because we rely on bkg in some of the linear var changes.
> 
> So, to be clear, you're saying there are linear var changes where, in order to do `setTrajectory`, you need both a background state and a (different) first guess state at the same time? From my understanding and conversations with @ytremolet I did not think that that this would ever be the case. Maybe we should talk.
> 
> I thought you were joking this morning when you said we were going to break SOCA again!

@svahl991 that's a discussion that we've had a few years back. Some of the variable changes do need the background, I had that discussion with @shlyaeva  a while back. For example, our parametric diag B is based on estimating the background error from the background, not the trajectory. This is based on empirical results and also what other ocean DA system are doing.
We have solutions that we can implement to go around this change, but we would like a bit more time to make sure this isn't going to be a problem elsewhere.

**Comment by ytremolet** [comment]
A linear change of variable can have only one state it linearizes around. What that state should be is up to the caller, not to the change of variable.

**Comment by travissluka** [comment]
> I thought you were joking this morning when you said we were going to break SOCA again!

@svahl991 I was joking! Oops, I guess I jinxed it.

**Comment by travissluka** [comment]
@guillaumevernieres possible solutions from my limited understanding, in order of preference:

1. Have the `BkgErr*` classes read in the background state directly, defined in a new section of yaml. This might be useful if we wanted to play around with having the parametric B depend on either climatology or some other pre-smoothed/modified state instead.
2. calculate `BkgErr*` offline and read it in
3. Just ignore it, for now, and use `traj`, since outer loops were broken at last check anyway.
4. Convince the JEDI people to leave `bkg` in there, for now.

I think a combination of 1 and 2 might be most useful: give the option of `BkgErr` reading in either a state or the precomputed parameters. 1 would be the easiest to implement to retain same functionality and not have to modify our workflows.

**Comment by guillaumevernieres** [comment]
@travissluka : **2** is what I'll do in the global workflow, generate the diag of B and massage it, then use the stddev saber block to read it ... But that only works if we use bump_nicas.  I'm just wondering if we are overseeing something. I'll take a closer look tomorrow.

**Comment by guillaumevernieres** [comment]
> A linear change of variable can have only one state it linearizes around. What that state should be is up to the caller, not to the change of variable.

Yes @ytremolet . It's probably all good, the only place where we really need the background is for 1 lin var change. Still, I ll take a closer look tomorrow.

**Comment by shlyaeva** [comment]
A couple of questions:
- are all linear variable changes that require background  part of B?
- if that's the case, are they generic enough to become saber blocks?

**Comment by guillaumevernieres** [comment]
> A couple of questions:
> 
> * are all linear variable changes that require background  part of B?
yes and no. 
> * if that's the case, are they generic enough to become saber blocks?
We have 2 that define the std of the bkg error, we can save the diag of B and use the std dev saber block, so yes. The one issue that I need to look at today is in the linear var change VertConv.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres possible solutions from my limited understanding, in order of preference:
> 
> 1. Have the `BkgErr*` classes read in the background state directly, defined in a new section of yaml. This might be useful if we wanted to play around with having the parametric B depend on either climatology or some other pre-smoothed/modified state instead.
> 2. calculate `BkgErr*` offline and read it in
> 3. Just ignore it, for now, and use `traj`, since outer loops were broken at last check anyway.
> 4. Convince the JEDI people to leave `bkg` in there, for now.
> 
> I think a combination of 1 and 2 might be most useful: give the option of `BkgErr` reading in either a state or the precomputed parameters. 1 would be the easiest to implement to retain same functionality and not have to modify our workflows.

@travissluka 2 & 3 seems fine ... We're not going to do outer loops the way oops intends to outerloop any time soon, so we might be ok ignoring for a long while.

**Comment by travissluka** [comment]
@guillaumevernieres as a slightly better version of 3,  would it be true for us that `bkg` always equals `traj` at the beginning? If so, as a soca-style hack  I can just make it so that we save the first `traj` for subsequent use in `BkgErr` and ignore the following calls to change trajectory. Again, as a hack to maintain current functionality.

@shlyaeva 1) yes, they're all part of b 2) sure, we could use saber block, that would require us to use saber I'm assuming. we currently use direct calls to bump instead, just to be weird and different.... to be dealt with and cleaned up later this AOP year.

**Comment by shlyaeva** [comment]
> If so, as a soca-style hack I can just make it so that we save the first traj for subsequent use in BkgErr and ignore the following calls to change trajectory. Again, as a hack to maintain current functionality.

heh, looks like I'm thinking in soca-style hacks too 😇 ; I was thinking about the same yesterday. One thing I'm not sure about is if different objects of `LinearVariableChange` get created at different iterations (need to check in the code).

**Comment by guillaumevernieres** [comment]
Whatever is easiest for you @travissluka , but yes, that seems reasonable to me as a "temporary" solution.

We switched to saber blocks in the gdasapp, in anticipation of using bump3d. The only linear variable change that we would use is the `Balance`, which only needs the trajectory. So we're all good as long as we don't have to make use of `VertConv`.

**Comment by svahl991** [comment]
Thanks for working to find a workaround! So are people feeling OK with us merging https://github.com/JCSDA-internal/oops/pull/1800 on Monday as planned, or would you like more time? If so, how much?

**Comment by travissluka** [comment]
> Thanks for working to find a workaround! So are people feeling OK with us merging [JCSDA-internal/oops#1800](https://github.com/JCSDA-internal/oops/pull/1800) on Monday as planned, or would you like more time? If so, how much?

I'll need 1 day, starting today. I'm not really sure any more how long one day takes... hopefully it only takes one day.
But yes, I should be ready in time, and if not don't let us hold you up.
