### ISSUE TITLE
Some tests failing on orion with intel spack-stack

### ISSUE THREAD

**Issue by shlyaeva** [JCSDA-internal/soca#773]
## Description
The following tests fail on orion with intel spack-stack:

- `test_soca_convertstate`:
> 1266: Test Val : 5.9782488939415996e+00
1266: Ref  Val : 5.9783431324160823e+00
1266: Delta    : 9.4238474482644108e-05
1266: Relative tolerance: 5.9782960131788415e-06
1266: Absolute tolerance: 0.0000000000000000e+00
1266: Test Line: '   tocn   min=-1.8880081892310945   max=31.7033530247322126   mean=5.9782488939415996'
1266: Ref Line : '   tocn   min=-1.8880081892310945   max=31.7033530247322091   mean=5.9783431324160823'

Should be fixable by small adjustment of tolerance.

- `test_soca_dirac_soca_mask` and `test_soca_dirac_soca_nomask`:
> 1312: Caught SIGFPE: floating-point divide by zero
1312: Caught SIGFPE: floating-point divide by zero
1312:  0# sigfpe_handler(int, siginfo_t*, void*) in /work/noaa/da/ashlyaev/jedi/build/bin/../lib64/liboops.so
1312:  1# 0x00007FFA747E15D0 in /lib64/libpthread.so.0
1312:  2# atlas::grid::spacing::gaussian::compute_gaussian_quadrature_npole_equator(unsigned long, double*, double*) in /work/noaa/da/role-da/spack-stack/spack-stack-v1/envs/skylab-1.0.0-intel-2022.0.2/install/intel/2022.0.2/ecmwf-atlas-0.29.0-k4yxszy/lib64/libatlas.so.0.29
1312:  3# atlas::grid::spacing::gaussian::gaussian_latitudes_npole_equator(unsigned long, double*) in /work/noaa/da/role-da/spack-stack/spack-stack-v1/envs/skylab-1.0.0-intel-2022.0.2/install/intel/2022.0.2/ecmwf-atlas-0.29.0-k4yxszy/lib64/libatlas.so.0.29

I remember having (I think) the same issue on my mac at some point. I debugged then a bit and attributed it to a compiler optimization gone wrong. I think we had a similar issue at some point with some of the ufo code (may have to do with vectorization and dividing by zero past the end of array or something like this). I'll try to find how we fixed that.

- `test_soca_3dvar_soca`:
> 1317: Test Val : 1.3578991055153833e-01
1317: Ref  Val : 9.2820018030662005e-02
1317: Delta    : 4.2969892520876324e-02
1317: Relative tolerance: 1.1430496429110016e-07
1317: Absolute tolerance: 0.0000000000000000e+00
1317: Test Line: 'RPCGMinimizer: reduction in residual norm = 1.3578991055153833e-01'
1317: Ref Line : 'RPCGMinimizer: reduction in residual norm = 9.2820018030662005e-02'

Seems to be a pretty significant difference, not sure why.

- `test_soca_3dvar_single_ob`:
> 1318: Test Val : 0.0000000000000000e+00
1318: Ref  Val : 2.0050958797774292e-16
1318: Delta    : 2.0050958797774292e-16
1318: Relative tolerance: 1.0025479398887145e-22
1318: Absolute tolerance: 0.0000000000000000e+00
1318: Test Line: 'RPCGMinimizer: reduction in residual norm = 0.0000000000000000e+00'
1318: Ref Line : 'RPCGMinimizer: reduction in residual norm = 2.0050958797774292e-16'

Not sure how significant that is..

- `test_soca_3dvarbump`:
> 1319: Test Val : 1.5167557032312473e-01
1319: Ref  Val : 1.5167539132635138e-01
1319: Delta    : 1.7899677334787256e-07
1319: Relative tolerance: 1.5167548082473804e-07
1319: Absolute tolerance: 0.0000000000000000e+00
1319: Test Line: 'RPCGMinimizer: reduction in residual norm = 1.5167557032312473e-01'
1319: Ref Line : 'RPCGMinimizer: reduction in residual norm = 1.5167539132635138e-01'

Seems like tolerance can be changed.

- `test_soca_3dvar_godas`:
> 1320: Test Val : 1.4657743150452185e-01
1320: Ref  Val : 1.1870594894077013e-01
1320: Delta    : 2.7871482563751715e-02
1320: Relative tolerance: 1.3264169022264599e-07
1320: Absolute tolerance: 0.0000000000000000e+00
1320: Test Line: 'RPCGMinimizer: reduction in residual norm = 1.4657743150452185e-01'
1320: Ref Line : 'RPCGMinimizer: reduction in residual norm = 1.1870594894077013e-01'

Significant difference; not sure why.

- `test_soca_addincrement` and `test_soca_convertincrement`: may depend on the output of the failing tests?

- `test_soca_3dvarlowres_soca`: 
> 1323: Test Val : 1.0675545865616178e-01
1323: Ref  Val : 1.0675524134831732e-01
1323: Delta    : 2.1730784445506135e-07
1323: Relative tolerance: 1.0675535000223953e-07
1323: Absolute tolerance: 0.0000000000000000e+00
1323: Test Line: 'RPCGMinimizer: reduction in residual norm = 1.0675545865616178e-01'
1323: Ref Line : 'RPCGMinimizer: reduction in residual norm = 1.0675524134831732e-01'

Seems like tolerance can be adjusted.

- `test_soca_3dvarfgat`, `test_soca_3dfgat_pseudo`, `test_soca_3dhybfgat` (output not shown for the last two, but similar diffs):
> 1325: Test Val : 4.5208697320818997e-01
1325: Ref  Val : 3.4000878538451623e-01
1325: Delta    : 1.1207818782367374e-01
1325: Relative tolerance: 3.9604787929635310e-07
1325: Absolute tolerance: 0.0000000000000000e+00
1325: Test Line: 'RPCGMinimizer: reduction in residual norm = 4.5208697320818997e-01'
1325: Ref Line : 'RPCGMinimizer: reduction in residual norm = 3.4000878538451623e-01'

Significant difference, not sure why.

- `test_soca_checkpointmodel`:
> 1333: Test Val : 6.0186193018435992e+00
1333: Ref  Val : 6.0197585704204624e+00
1333: Delta    : 1.1392685768631949e-03
1333: Relative tolerance: 6.0191889361320300e-06
1333: Absolute tolerance: 0.0000000000000000e+00
1333: Test Line: '   tocn   min=-1.8883899372702533   max=31.7004645720658580   mean=6.0186193018435992'
1333: Ref Line : '   tocn   min=-1.8883899372702533   max=31.7004645720658580   mean=6.0197585704204624'

Is a difference like this reasonable?

### To Reproduce:
orion; load modules
```
module purge
module use /work/noaa/da/role-da/spack-stack/modulefiles
module load miniconda/3.9.7
module load ecflow/5.8.4
module use /work/noaa/da/role-da/spack-stack/spack-stack-v1/envs/skylab-1.0.0-intel-2022.0.2/install/modulefiles/Core
module load stack-intel/2022.0.2
module load stack-intel-oneapi-mpi/2021.5.1
module load stack-python/3.9.7
module load jedi-ewok-env/1.0.0 jedi-fv3-env/1.0.0 nco/5.0.6
```

**Comment by shlyaeva** [comment]
I can do adjustment of tolerances where it seems to make sense, and look into the issue with over-optimized atlas.

**Comment by shlyaeva** [comment]
Except for `3dvarbump` where setting relative tolerance to `1.e-5` (still reasonable, I think) does the trick, other tolerances would have to be adjusted significantly.

**Comment by guillaumevernieres** [comment]
Thanks for testing @shlyaeva ! We've been procrastinating over this issues (it's not because of the spack-stack) for a long while. Oops. 
@ShastriPaturi @liuxiao37k , @kbhargava  do you remember what tests are currently failing on orion?

**Comment by liuxiao37k** [comment]
@guillaumevernieres @shlyaeva I don't trust what I remember so I ran the soca ctests on Orion with the develop branch cloned on Friday:
```
The following tests FAILED:
	  4 - test_soca_convertstate (Failed)
	 58 - test_soca_3dvarbump (Failed)
	 60 - test_soca_addincrement (Failed)
	 61 - test_soca_convertincrement (Failed)
	 62 - test_soca_3dvarlowres_soca (Failed)
```
This is with `jedi/intel-impi/2020.2` loaded, though. 
For example, 
with ` 4 - test_soca_convertstate (Failed)`
```
4: Test Line: '   uocn   min=-0.8581693992488437   max=0.7000940838255798   mean=-0.0000952211558432'
4: Ref Line : '   uocn   min=-0.8581693992488437   max=0.7000940838255798   mean=-0.0000950722801715'
```
