### ISSUE TITLE
Test failure: test_soca_create_kmask on Cheyenne using spack-stack

### ISSUE THREAD

**Issue by climbfuji** [JCSDA-internal/soca#783]
## Description
The test `test_soca_create_kmask` fails on Cheyenne with spack-stack (GNU+OpenMPI). The error message is cryptic and hints to an MPI issue, but weird enough all MPI jobs that are not soca (e.g. ioda, oops, saber) work without problems.
```
heinzell@r3i1n18:/glade/scratch/heinzell/skylab-1.0/build> ctest -R test_soca_create_kmask --output-on-failure 2>&1 | tee log.ctest.noget.rerun-failed-test_soca_create_kmask
Test project /glade/scratch/heinzell/skylab-1.0/build
    Start 1274: test_soca_create_kmask
1/1 Test #1274: test_soca_create_kmask ...........***Failed    0.95 sec
--------------------------------------------------------------------------
No components were able to be opened in the pml framework.

This typically means that either no components of this type were
installed, or none of the installed components can be loaded.
Sometimes this means that shared libraries required by these
components are unable to be found/loaded.

  Host:      r3i1n18
  Framework: pml
--------------------------------------------------------------------------
[r3i1n18:25870] PML ucx cannot be selected


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   1.33 sec

The following tests FAILED:
	1274 - test_soca_create_kmask (Failed)
```

### To Reproduce:
On Cheyenne:
```
module purge
module unuse /glade/u/apps/ch/modulefiles/default/compilers
export MODULEPATH_ROOT=/glade/work/jedipara/cheyenne/spack-stack/modulefiles
module use /glade/work/jedipara/cheyenne/spack-stack/modulefiles/compilers
module use /glade/work/jedipara/cheyenne/spack-stack/modulefiles/misc
module load ecflow/5.8.4
module load miniconda/3.9.12

ulimit -s unlimited
module use /glade/work/jedipara/cheyenne/spack-stack/spack-stack-v1/envs/skylab-1.0.0-gnu-10.1.0/install/modulefiles/Core
module load stack-gcc/10.1.0
module load stack-openmpi/4.1.1
module load stack-python/3.9.12
module available
```
Clone jedi-bundle, build and run `ctest -R get_` on the login node. Then start an interactive session, e.g.
```
qsub -A NMMM0015 -l walltime=08:00:00 -N skylab-gnu-ctest -q economy -l select=1:ncpus=36:mpiprocs=36:ompthreads=1 -I
```
Repeat the above module load commands (starting from `module purge`) and run `ctest -E get_` or - not sure if that's possible - just `ctest -R test_soca_create_kmask --output-on-failure`.

## Additional context
I built the bundle using `cmake` without specifying `-DMPIEXEC_EXECUTABLE` etc, and not using `ecbuild`. It didn't have any bad effect on the other 1300-ish tests, but I'll try again with those commands/options.

## Output

See above

**Comment by guillaumevernieres** [comment]
@climbfuji FYI, the test you refer to is a serial job, it just runs `test/Data/create_kmask.py`.

**Comment by climbfuji** [comment]
> @climbfuji FYI, the test you refer to is a serial job, it just runs `test/Data/create_kmask.py`.

I know, that's why I am puzzled that it throws this error. I also tried to wrap it in `mpiexec -np 1 ...` but got the same error.

**Comment by climbfuji** [comment]
Having said that, if that create kmask script uses the netCDF library underneath (for example through netcdf4Python), then in spack-stack it links against the parallel-netcdf/parallel-hdf5 libraries, which have been built with the MPI wrappers and which - depending on how the system is configured and how the MPI library was built - may require running this as a fake parallel job. Will keep investigating.

**Comment by travissluka** [comment]
on a related thought, I've always hated this "test". It's not a test, it's just generating data for subsequent ctests. I've long contemplated removing this, and the subgrid generation step, and just including the output netcdf files as git-lfs data items.

**Comment by guillaumevernieres** [comment]
Or better yet @travissluka , we could remove the mask for the jacobian in the balance operator. This was useful a while back, but I'm not using that feature anymore, and I doubt anybody else would. That would allow the removal of a few other tests related to that feature.

**Comment by travissluka** [comment]
> Or better yet @travissluka , we could remove the mask for the jacobian in the balance operator. This was useful a while back, but I'm not using that feature anymore, and I doubt anybody else would. That would allow the removal of a few other tests related to that feature.

@guillaumevernieres the best way to fix a bug with code is to just delete the code! I created https://github.com/JCSDA-internal/soca/issues/784 and whoever has freetime first can assign themselves and start deleting.

**Comment by climbfuji** [comment]
Cleaning up is always good! Just for your information, the problem is not with the Python script itself, but with the spack-stack and/or OpenMPI install on Cheyenne with GNU. Any Python script that loads a dependency that was compiled with the openMPI wrappers fails with the same error. Working with the sysadmins on it.

**Comment by climbfuji** [comment]
Good news, although I don't want to spoil your cleaning efforts. The test now passes on Cheyenne with GNU. Here is the explanation from Brian from CISL IT, who did an amazing job figuring this out today:

> So I've discovered the issue that was affecting the Python case. Basically, we've been building the UCX library single-threaded as the multi-threaded version had been causing issues for one of our primary GPU applications on Casper. This got standardized to Cheyenne too but obviously it does not play nicely with mpi4py. Since the multithreading issue should not be relevant on Cheyenne, I've rebuilt UCX and confirmed that my basic Python tests now work with the gnu/10.1.0 version of openmpi/4.1.1. Please let me know if you see the same.

I do - the test now runs fine. Yay!
