### ISSUE TITLE
Remove kmask stuff

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#784]
## Description
remove all the `kmask` related code and tests. They supposedly are not being used and are just causing problems.

**Comment by travissluka** [comment]
@guillaumevernieres just to be clear, you were saying to remove the whole made up `dc/dT` stuff, right? since the `create_kmask.py` was responsible for both `kmask` and `dcdt`

**Comment by guillaumevernieres** [comment]
@travissluka :
- The mask fo the ssh jacobian can be deleted from the balance test and code here: [soca_balance_mod.F90#L190](https://github.com/JCSDA-internal/soca/blob/f48fb1385e7e6317ec76a9f4a8cdf98368db020b/src/soca/LinearVariableChange/Balance/soca_balance_mod.F90#L190)
- We need dc/dt in the balance, but we could add the output of that python script (minus the kmask stuff) to git-lfs?

**Comment by travissluka** [comment]
this was taken  care of sometime in the past, not sure when
