### ISSUE TITLE
ALGO-24: develop/test SOCA LETKF

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#787]
Develop functional LETKF, and demonstrate that it will work with ocean/ice for both regional and global cases.

- we will focus on the regional HAT10 one month case first, in house.
- this work will be done with soca-science, replicating under ewok will be done at a later date.

**Comment by gibbsp** [comment]
Changed timeline after AOP22 audit - see doc JCSDA_AOP2022_rev 2_20230105 audit. Integrate in Skylab in V4.

**Comment by travissluka** [comment]
> "this work will be done with soca-science, replicating under ewok will be done at a later date."

The original goal of getting LETKF working is finished.
Getting it integrated under ewok will not happen in skylab v4.
