### ISSUE TITLE
develop soca code failed with exception

### ISSUE THREAD

**Issue by weihuang-jedi** [JCSDA-internal/soca#793]
## Description
After update the soca code to current develop branch, compile and run, got error:

Test     : layer_depth   min=    0.838614   max= 6376.155029   mean=  911.245570
Test     :   cicen   min=    0.000000   max=    1.000000   mean=    0.219001
Test     :   hicen   min=    0.000000   max=    2.472954   mean=    0.240000
Test     :   hsnon   min=    0.000000   max=    0.743529   mean=    0.050114

Exception: InsituTemperature does not exist in ufo::ObsOperatorFactory
Exception: oops::LocalEnsembleDA<SOCA, UFO and IODA observations> terminating...
OOPS Ending   2022-08-02 16:15:34 (UTC-0500)

The yaml file, and run script works fine last week.

### To Reproduce:
This is run on orion, with module:

 module purge

 module use /work/noaa/da/role-da/spack-stack/spack-stack-v1/envs/skylab-1.0.0-intel-2022.0.2/install/modulefiles/Core
 module load stack-intel/2022.0.2
 module load stack-intel-oneapi-mpi/2021.5.1

 module load jedi-fv3-env/1.0.0
 module load jedi-ewok-env/1.0.0
 module load nco/5.0.6
 module load json/3.9.1   json-schema-validator/2.1.0

## Additional context
None

**Comment by travissluka** [comment]
can you point to the yaml file you're using?

**Comment by weihuang-jedi** [comment]
/work2/noaa/gsienkf/weihuang/ufs/soca/new-soca-solver/soca_solver.32t2n_64p/letkf_solver.yaml
or ~weihuang/letkf_solver.yaml

**Comment by travissluka** [comment]
Given the warning, it's acting like UFO can't find GSW when it is compiling, which is weird.

1) are you able to run the ctests successfully?
2) can you recursively set read permissions for `/work/noaa/gsienkf/weihuang/jedi/src/bld.soca` and `/work/noaa/gsienkf/weihuang/jedi/src/src.soca` so I can see if I can find anything obviously wrong.

**Comment by weihuang-jedi** [comment]
Have set permission to: /work/noaa/gsienkf/weihuang/jedi/src/bld.soca and
/work/noaa/gsienkf/weihuang/jedi/src/src.soca

Running ctest now.

**Comment by weihuang-jedi** [comment]
most ctest failed for me:

28% tests passed, 785 tests failed out of 1096

See /work/noaa/gsienkf/weihuang/jedi/src/bld.soca/log.ctest

**Comment by travissluka** [comment]
@weihuang-jedi for future reference, you can just `cd` to the soca dir and run `ctest` there to not have to run all the JEDI ctests.

The ctests (mostly) work for me with the compiler you note using. I would recommend deleting your src and build directories and trying to rebuild. There seems to be something odd with your build/environment

**Comment by weihuang-jedi** [comment]
I will do a fresh checkout and then a fresh build.

**Comment by weihuang-jedi** [comment]
After a fresh checkout and build, run ctest in soca directory, got:

Label Time Summary:
executable    =  27.78 sec*proc (21 tests)
mpi           = 196.02 sec*proc (67 tests)
script        = 170.75 sec*proc (48 tests)
soca          = 198.53 sec*proc (69 tests)

Total Test time (real) = 200.39 sec

The following tests FAILED:
          3 - test_soca_convertstate (Failed)
          8 - test_soca_static_socaerror_init (Failed)
          9 - test_soca_static_socaerrorlowres_init (Failed)
         12 - test_soca_enspert (Failed)
         13 - test_soca_sqrtvertloc (Failed)
         23 - test_soca_errorcovariance (Failed)
         24 - test_soca_linearmodel (Failed)
         36 - test_soca_ensvariance (Failed)
         39 - test_soca_ensrecenter (Failed)
         40 - test_soca_hybridgain (Failed)
         45 - test_soca_dirac_soca_cov (Failed)
         46 - test_soca_dirac_socahyb_cov (Failed)
         47 - test_soca_dirac_horizfilt (Failed)
         48 - test_soca_dirac_soca_mask (Failed)
         49 - test_soca_dirac_soca_nomask (Failed)
         50 - test_soca_hofx_3d (Failed)
         51 - test_soca_hofx_4d (Failed)
         53 - test_soca_enshofx (Failed)
         54 - test_soca_3dvar_soca (Failed)
         55 - test_soca_3dvar_single_ob (Failed)
         56 - test_soca_3dvarbump (Failed)
         57 - test_soca_3dvar_godas (Failed)
         58 - test_soca_addincrement (Failed)
         59 - test_soca_convertincrement (Failed)
         60 - test_soca_3dvarlowres_soca (Failed)
         62 - test_soca_3dvarfgat (Failed)
         63 - test_soca_3dvarfgat_pseudo (Failed)
         64 - test_soca_3dhyb (Failed)
         65 - test_soca_3dhybfgat (Failed)
         66 - test_soca_letkf (Failed)
         67 - test_soca_letkf_split_observer (Failed)
         68 - letkf_split_observer_post (Failed)
         69 - test_soca_letkf_split_solver (Failed)
         70 - test_soca_checkpointmodel (Failed)
Errors while running CTest
Output from these tests are in:
/work/noaa/gsienkf/weihuang/jedi/src/bld.soca/soca/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases
verbosely.

**Comment by weihuang-jedi** [comment]
rerun with:

ctest --rerun-failed --output-on-failure | tee log.ctest2

Got:

12% tests passed, 30 tests failed out of 34

Label Time Summary:
executable    =   2.83 sec*proc (2 tests)
mpi           = 188.53 sec*proc (33 tests)
script        = 186.78 sec*proc (32 tests)
soca          = 189.61 sec*proc (34 tests)

Total Test time (real) = 191.80 sec

The following tests FAILED:
          3 - test_soca_convertstate (Failed)
          8 - test_soca_static_socaerror_init (Failed)
          9 - test_soca_static_socaerrorlowres_init (Failed)
         12 - test_soca_enspert (Failed)
         13 - test_soca_sqrtvertloc (Failed)
         36 - test_soca_ensvariance (Failed)
         39 - test_soca_ensrecenter (Failed)
         40 - test_soca_hybridgain (Failed)
         45 - test_soca_dirac_soca_cov (Failed)
         46 - test_soca_dirac_socahyb_cov (Failed)
         48 - test_soca_dirac_soca_mask (Failed)
         49 - test_soca_dirac_soca_nomask (Failed)
         50 - test_soca_hofx_3d (Failed)
         51 - test_soca_hofx_4d (Failed)
         53 - test_soca_enshofx (Failed)
         54 - test_soca_3dvar_soca (Failed)
         55 - test_soca_3dvar_single_ob (Failed)
         56 - test_soca_3dvarbump (Failed)
         57 - test_soca_3dvar_godas (Failed)
         58 - test_soca_addincrement (Failed)
         59 - test_soca_convertincrement (Failed)
         60 - test_soca_3dvarlowres_soca (Failed)
         62 - test_soca_3dvarfgat (Failed)
         63 - test_soca_3dvarfgat_pseudo (Failed)
         64 - test_soca_3dhyb (Failed)
         65 - test_soca_3dhybfgat (Failed)
         66 - test_soca_letkf (Failed)
         67 - test_soca_letkf_split_observer (Failed)
         69 - test_soca_letkf_split_solver (Failed)
         70 - test_soca_checkpointmodel (Failed)

**Comment by travissluka** [comment]
it would be useful if you look to see why they are failing.
Either run in verbose mode `-V` or check the existing log `/work/noaa/gsienkf/weihuang/jedi/src/bld.soca/soca/Testing/Temporary/LastTest.log` for one of the tests.
I do not have permission to look at the file myself

**Comment by weihuang-jedi** [comment]
Travis,

I have changed the permission.
You may also check:
/work/noaa/gsienkf/weihuang/jedi/src/bld.soca/soca/log.test_soca_letkf

Which I run:

ctest -R test_soca_letkf -V | tee log.test_soca_letkf

and have error as:

66: Relative tolerance: 3.4548694513948700e-05
66: Absolute tolerance: 0.0000000000000000e+00
66: Test Line: '   socn   min=10.7210460395083924   max=40.4416591897031168
  mean=34.5508108724416090'
66: Ref Line : '   socn   min=10.7210460395083924   max=40.4416591897031168
  mean=34.5465781554557978'
66: srun: error: Orion-24-53: task 1: Aborted
66: srun: launch/slurm: _step_signal: Terminating StepId=6357402.0
66: srun: error: Orion-24-52: task 0: Aborted
1/3 Test #66: test_soca_letkf ..................***Failed   19.04 sec
test 67

**Comment by travissluka** [comment]
@weihuang-jedi The error indicates that your letkf runs successfully, but that references answers do not match exactly. This is because you are using a compiler that we ourselves on the soca team have not used yet. See https://github.com/JCSDA-internal/soca/issues/797

**Comment by weihuang-jedi** [comment]
Re-tried with previous compiler, still got:

0% tests passed, 9 tests failed out of 9

Label Time Summary:
mpi       =  81.89 sec*proc (8 tests)
script    =  81.91 sec*proc (9 tests)
soca      =  81.91 sec*proc (9 tests)

Total Test time (real) =  82.23 sec

The following tests FAILED:
          3 - test_soca_convertstate (Failed)
         45 - test_soca_dirac_soca_cov (Failed)
         46 - test_soca_dirac_socahyb_cov (Failed)
         56 - test_soca_3dvarbump (Failed)
         58 - test_soca_addincrement (Failed)
         59 - test_soca_convertincrement (Failed)
         60 - test_soca_3dvarlowres_soca (Failed)
         68 - letkf_split_observer_post (Failed)
         69 - test_soca_letkf_split_solver (Failed)
Errors while running CTest

As mentioned, most of the above code run parts passed, but failed at
comparison.

**Comment by frolovsa** [comment]
@travissluka It seems like soca generates quite different results under different compilers. There is an example here and in the related issue on Chayanne. Any thoughts on what to do about it? Is changing the tolerance an option?

**Comment by guillaumevernieres** [comment]
@frolovsa investigate the failure and if this is a tolerance issues, report to @travissluka and ignore ... If you need to replicate the tests exactly, just use the JCSDA singularity container on Orion.

**Comment by travissluka** [comment]
> @travissluka It seems like soca generates quite different results under different compilers. There is an example here and in the related issue on Chayanne. Any thoughts on what to do about it? Is changing the tolerance an option?

@frolovsa, yes I'm working on a PR that cleans up the tests. As part of that, tolerances will be fixed, and several of the tests that rely on `test_soca_enspert` will instead us a pregenerated ensemble. The `enspert` step seems to be a large source of tolerance issues across compilers.

**Comment by weihuang-jedi** [comment]
Re-run with previous compiler with newly cloned, re-built code, still got
same error:

Test     : Initial state for member 80:
Test     :   Valid time: 2015-12-01T12:00:00Z
Test     :    socn   min=    3.683630   max=   38.016514   mean=   34.362863
Test     :    tocn   min=   -1.895580   max=   31.775337   mean=    7.698882
Test     :     ssh   min=   -1.914767   max=    1.337421   mean=   -0.262997
Test     :    hocn   min=    0.001000   max=  250.045295   mean=   43.648247
Test     :     mld   min=    0.838614   max= 5348.085716   mean=  216.514473
Test     : layer_depth   min=    0.838614   max= 6376.155029   mean=
 911.245570
Test     :   cicen   min=    0.000000   max=    1.000000   mean=    0.219001
Test     :   hicen   min=    0.000000   max=    2.472954   mean=    0.240000
Test     :   hsnon   min=    0.000000   max=    0.743529   mean=    0.050114

Exception: InsituTemperature does not exist in ufo::ObsOperatorFactory
Exception: oops::LocalEnsembleDA<SOCA, UFO and IODA observations>
terminating...
OOPS Ending   2022-08-05 14:46:33 (UTC-0500)

**Comment by travissluka** [comment]
I'm fairly confident this is a problem with your personal build environment. Your build is somehow finding a version of UFO that was not compiled with GSW enabled.

@weihuang-jedi I took a look at your `~/intelenv` file and noticed that you set `LD_LIBRARY_PATH` to point to `/work/noaa/gsienkf/weihuang/jedi/src/my.compile/lib`. I see that your `my.compile` directory does NOT contain GSW. This is your problem.

**Comment by travissluka** [comment]
closing, this is a problem with personal build environment being set wrong, not a problem with SOCA

**Comment by frolovsa** [comment]
Thank you @travissluka for figuring this out.

**Comment by weihuang-jedi** [comment]
Change yaml file:

bash-4.2$ pwd
/work2/noaa/gsienkf/weihuang/ufs/soca/new-soca-solver/soca_solver.32t2n_64p
bash-4.2$ diff ../soca_solver.40t2n_80p/letkf_solver.yaml .
339c339,340
<       name: InsituTemperature
---
>      #name: InsituTemperature
>       name: Identity
369c370,371
<       name: MarineVertInterp
---
>      #name: MarineVertInterp
>       name: Identity

bash-4.2$ tail stdoutNerr/stdout.00000000
Test     :     ssh   min=   -1.914767   max=    1.337421   mean=   -0.262997
Test     :    hocn   min=    0.001000   max=  250.045295   mean=   43.648247
Test     :     mld   min=    0.838614   max= 5348.085716   mean=  216.514473
Test     : layer_depth   min=    0.838614   max= 6376.155029   mean=
 911.245570
Test     :   cicen   min=    0.000000   max=    1.000000   mean=    0.219001
Test     :   hicen   min=    0.000000   max=    2.472954   mean=    0.240000
Test     :   hsnon   min=    0.000000   max=    0.743529   mean=    0.050114

Unable to find field metadata for: sea_water_temperature
OOPS Ending   2022-08-05 11:43:32 (UTC-0500)
