### ISSUE TITLE
Bad latitude value running regional LETKF with halo distribution

### ISSUE THREAD

**Issue by kbhargava** [JCSDA-internal/soca#800]
## Description
Looks like the code encounters latitudes with garbage values when using the halo distribution with the regional LETKF

#### Compiler and machines used:
Intel compiler on orion
#### Explicit steps to reproduce the behavior:
1. Select the halo obs distribution in the LETKF yaml and set the halo size. I tested a few halo sizes between 100 and 500e3 for fun, the larger sizes lead to this error and the smaller ones to [this one](https://github.com/JCSDA-internal/ufo/issues/2032).
2. Submit the LETKF DA experiment for the regional case (1/4 degree HAT10 )
3. then, oops, look at the bug: 
`Exception: BadValue: Invalid latitude 6.742913661448822e+22  (/home/role-da/jcsda/jedi-stack/pkg/eckit/src/eckit/geometry/Sphere.cc +84 centralAngle)`

**Comment by frolovsa** [comment]
@kbhargava I am a bit confused. In this issue https://github.com/JCSDA-internal/ufo/issues/2032 you mentioned that you tried different halo sizes and the code worked. In this issue you say that it either causes the assert error or the bad latitude error. 

For this specific error above. Any chance you can give us a full stack trace so we know in which upstream function causes the bad latitude?

**Comment by kbhargava** [comment]
Huh!! Thanks for this. When I tested before I just manually submitted letkf steps as halo size couldn't be specified with the earlier workflow. 

Now I am running it as part of the workflow. Though this shouldn't change anything. Let me verify my configuration or if anything else I changed and then get back to you.

**Comment by travissluka** [comment]
This doesn't seem to be an issue anymore. Halo distribution runs without error (tested in https://github.com/JCSDA-internal/soca-science/issues/224)
