### ISSUE TITLE
Question: New thirdparty library dependency in soca?

### ISSUE THREAD

**Issue by climbfuji** [JCSDA-internal/soca#817]
## Description
@travissluka I get this when I build the latest jedi-bundle (develop), haven't seen it before:
```
CMake Error at /home/ubuntu/jedi/spack-stack/envs/skylab-2.0.0-intel-2021.4.0/install/intel/2021.4.0/ecbuild-3.6.5-6olrxph/share/ecbuild/cmake/ecbuild_add_test.cmake:312 (add_executable):
  Target "test_soca_obslocalization" links to target "sp::sp_d" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  soca/test/CMakeLists.txt:264 (ecbuild_add_test)
  soca/test/CMakeLists.txt:404 (soca_add_test)


CMake Error at /home/ubuntu/jedi/spack-stack/envs/skylab-2.0.0-intel-2021.4.0/install/intel/2021.4.0/ecbuild-3.6.5-6olrxph/share/ecbuild/cmake/ecbuild_add_test.cmake:312 (add_executable):
  Target "test_soca_obslocalization_vertical" links to target "sp::sp_d" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  soca/test/CMakeLists.txt:264 (ecbuild_add_test)
  soca/test/CMakeLists.txt:408 (soca_add_test)


CMake Error at /home/ubuntu/jedi/spack-stack/envs/skylab-2.0.0-intel-2021.4.0/install/intel/2021.4.0/ecbuild-3.6.5-6olrxph/share/ecbuild/cmake/ecbuild_add_test.cmake:312 (add_executable):
  Target "test_soca_obslocalizations" links to target "sp::sp_d" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  soca/test/CMakeLists.txt:264 (ecbuild_add_test)
  soca/test/CMakeLists.txt:411 (soca_add_test)
```
Is this new?

**Comment by shlyaeva** [comment]
@climbfuji I think this may be coming from saber: https://github.com/JCSDA-internal/saber/blob/e742e4f2d11ff69d6c6c1cd1b6ac35663166ad79/CMakeLists.txt#L56 . Tagging @benjaminmenetrier for awareness.

**Comment by climbfuji** [comment]
> @climbfuji I think this may be coming from saber: https://github.com/JCSDA-internal/saber/blob/e742e4f2d11ff69d6c6c1cd1b6ac35663166ad79/CMakeLists.txt#L56 . Tagging @benjaminmenetrier for awareness.

Thanks, @shlyaeva - @benjaminmenetrier @rtodling for future reference, please coordinate adding dependencies on libraries with us before making the code changes. We do have `NCEPLIBS-sp` (`sp@2.3.3`) in `spack-stack`, but it is not a dependency of the various `jedi-MODEL-env` environment packages, which means we have to add it manually to the module load commands / instructions.

This is not in the skylab-v2 release, just in develop, correct?

**Comment by climbfuji** [comment]
> > @climbfuji I think this may be coming from saber: https://github.com/JCSDA-internal/saber/blob/e742e4f2d11ff69d6c6c1cd1b6ac35663166ad79/CMakeLists.txt#L56 . Tagging @benjaminmenetrier for awareness.
> 
> Thanks, @shlyaeva - @benjaminmenetrier @rtodling for future reference, please coordinate adding dependencies on libraries with us before making the code changes. We do have `NCEPLIBS-sp` (`sp@2.3.3`) in `spack-stack`, but it is not a dependency of the various `jedi-MODEL-env` environment packages, which means we have to add it manually to the module load commands / instructions.
> 
> This is not in the skylab-v2 release, just in develop, correct?

Ok, I just found that this **is** in the feature/skylab-v2 branch of saber :-(

**Comment by shlyaeva** [comment]
@climbfuji, @benjaminmenetrier, @rtodling : could there be a hotfix to make `sp` optional? I believe it's not in critical path for skylab v2 release.

**Comment by climbfuji** [comment]
I am trying this now by simply loading sp/2.3.3 in addition to the other modules, and it seems to work fine. If we agree that we add this to the documentation or scripts that load the modules, then we won't need to make any code changes.

**Comment by benjaminmenetrier** [comment]
Sorry, I really thought `sp` was already optional as it should be. I tried to fix that in: `hotfix/optional_sp`. Could anyone test this branch without `sp` installed?
