### ISSUE TITLE
check U/V increments for LETKF

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#820]
## Description
U/V are not being updated by LETKF currently in soca science.

figure out what happens if we enable that feature. It is likely that we will have to implement a bounds on the u/v increment size.

close this issue once we are able to cycle the regional for 1 months without u/v blowing up.

**Comment by symoore90** [comment]
Hi @travissluka is there anyway to break this issue up into smaller pieces?

**Comment by travissluka** [comment]
@symoore90 In hindsight, yes probably. But this issue should be closed by the end of the week with the associated PR

**Comment by symoore90** [comment]
Thanks for the update. Let me know if you need help breaking them up going forward.
