### ISSUE TITLE
Update test obs files and yamls to new convention

### ISSUE THREAD

**Issue by shlyaeva** [JCSDA-internal/soca#831]
## Description

Detailed description and solution here: https://github.com/orgs/JCSDA-internal/teams/jedi-models/discussions/91

**Comment by shlyaeva** [comment]
I've started on the first order changes, and should be able to push those (with at least some tests passing) by end of day.

**Comment by shlyaeva** [comment]
Note: variables in `swh.nc` (`sea_surface_wave_significant_height`), `uocn_surface.nc` (`surface_eastward_sea_water_velocity`), `vocn_surface.nc` (`surface_northward_sea_water_velocity`) don't get updated automatically (they are not in [ObsSpace.yaml](https://github.com/JCSDA-internal/ioda/blob/feature/sprint-ioda-converters/share/ioda/yaml/validation/ObsSpace.yaml)), I won't have time to look at fixing them.

**Comment by shlyaeva** [comment]
> Note: variables in swh.nc (sea_surface_wave_significant_height), uocn_surface.nc (surface_eastward_sea_water_velocity), vocn_surface.nc (surface_northward_sea_water_velocity) don't get updated automatically (they are not in [ObsSpace.yaml](https://github.com/JCSDA-internal/ioda/blob/feature/sprint-ioda-converters/share/ioda/yaml/validation/ObsSpace.yaml)).

Two other variables that don't get renamed:
`chl.nc`: `sea_surface_chlorophyll`
`biomass_p`: `sea_surface_biomass_in_p_units`

**Comment by gthompsnJCSDA** [comment]
This issue can be resolved/closed once [ioda PR 875](https://github.com/JCSDA-internal/ioda/pull/875) is merged.
