### ISSUE TITLE
Add (u,v) to one of the var test

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#836]
## Description
EMC is adding (u,v) to the control variables. It might be useful to have this feature back and as part of the `soca` CI.

### Possible issues
- [ ] `Ana2Model` hasn't been tested in a while (Seems fine)
- [ ] missing B for u, v. (Using ens. derived B) 
- [x] #842

**Comment by travissluka** [comment]
@guillaumevernieres I'll take a look at this, having bump/var working again with U/V enabled will make my life easier for getting the LETKF workflow stuff https://github.com/JCSDA-internal/soca-science/pull/538  merged, since it needs bump initialized for perturbing the ensemble, and enabling uv results in 
``` 7: ERROR: cannot use fields on u/v grids    ```

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres I'll take a look at this, having bump/var working again with U/V enabled will make my life easier for getting the LETKF workflow stuff [JCSDA-internal/soca-science#538](https://github.com/JCSDA-internal/soca-science/pull/538) merged, since it needs bump initialized for perturbing the ensemble, and enabling uv results in `7: ERROR: cannot use fields on u/v grids `

@travissluka , we don't use the `SocaError` covariance model in our latest implementation. So soca-sci 538 isn't a problem, at least for us. What I'm wondering is if all the steps to rotate and interpolate (u,v) are still OK. @liuxiao37k and myself will probably investigate in the next few days/weeks and comeback to you if we find issues. We currently have (u, v) as part of the state in the GDASApp, so the plumbing is fine, we just need to add the proper variable changes and check that it's all OK.

**Comment by liuxiao37k** [comment]
@guillaumevernieres As a related note, I am very interested in testing `Ana2Model` again and understanding how the plumbing works - perhaps we can finally have the `log transformation` stuff working! https://github.com/JCSDA-internal/soca/pull/476/

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres As a related note, I am very interested in testing `Ana2Model` again and understanding how the plumbing works - perhaps we can finally have the `log transformation` stuff working! #476

@liuxiao37k , I was thinking the same yesterday. 
I'm looking at it in the context of the gdasapp where our cost function is "4D-Var", it's then just a matter of a yaml change. We could hack things around in soca-sci and do something similar.

Iet's scribble the steps for the processing of the perturbations this am.

**Comment by guillaumevernieres** [comment]
@travissluka , @liuxiao37k , I updated the description, but it looks like "we" (I'm probably the culprit on that one ...) never finished the implementation of the co-location.

**Comment by travissluka** [comment]
fyi, I have a PR i'll issue latter today that adds u/v and ana2model to several relevant tests. 
Unfortunately I've also discovered a nice bug where bump is giving vastly different answers depending on if the ctest is run by itself or as part of the full list of tests, sigh.

@guillaumevernieres please open separate issues that are beyond the scope of "Add (u,v) to one of the var test", ie the colocation stuff. (I'm trying to get in the habit this quarter of ensuring small easily completable issues, to keep people like Phil off my back!)
