### ISSUE TITLE
Test regional configuration hybrid-EnVar WITHOUT U/V

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#840]
## Description

Do a test run of the Hybrid-EnVar. For this first run, U/V should be off (similar to how we started the LETKF experiments). I'm sure we'll discover blocking issues once we try to run.

* [x] check the envar localization settings and pick values that are reasonable for a first guess
* [x] LETKF settings should be same (or similar) to what was used for the stand-alone LETKF experiments
* [x] rerun the test period

**Comment by symoore90** [comment]
Hi @travissluka is there anyway to break this issue up into smaller pieces?

**Comment by travissluka** [comment]
@symoore90 The way I'm approaching these types of issues (science issues that are not likely to have much, if any, code PR associated with it) is to try make the issue fit within a 2 week period (we were delayed last code sprint period due to other things breaking), and if it is a big issue like this make sure it is broken down into several tasks in the description (oooh, and I just now noticed the "convert task to issue" button in gihub, which could be useful in the future!) If the issue has the likelihood to span multiple sprint periods, or if multiple PRs are anticipated, is when I think I would want to break something like this down into smaller issues.

That said, this issue should be wrapped up by the end of the week... assuming nothing goes wrong 🙄

**Comment by symoore90** [comment]
Thanks for the update.

**Comment by travissluka** [comment]
@kbhargava I think we can close this out since you've move on to U/V? If so, perhaps post a plot or two for posterity (these science related issues might be a good place to put a couple plots so that they're easy to find in the future), and close the issue.

**Comment by kbhargava** [comment]
Here is a comparison for the different experiments, DA methods we have tested, so far. The LETKF is with U/V and hybrid is without U/V and with 0.5 weights. The below figure shows the mean absolute error | o-b |, the reference obs are the Copernicus Level 4 ADTs which are passive.
![absoluteDynamicTopography_ 'adt_coperl4'](https://user-images.githubusercontent.com/22651193/224136088-5ca4c1aa-3c21-43ce-a1ee-60e35459c304.png)

**Comment by kbhargava** [comment]
I am not looking at more plots right now as the plan is to test this with U and V. But just as a sanity check below is a plot of SST increments for the last cycle (2021081612). The increments look "kind of" reasoanble but definitely need some localization tuning. 
![image](https://user-images.githubusercontent.com/22651193/224138475-c05e21fd-db18-4b2e-9cf9-918e828d4088.png)

**Comment by kbhargava** [comment]
@travissluka I put couple of plots above and think that's okay for now. I plan to include more analysis of the results with U and V included. If you are okay with this, this can be closed.
