### ISSUE TITLE
Co location is not implemented/commented out:

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#842]
Add a co-locate option to the Ana2Model change of variable.
One might want to rotate, but not co-locate when using the LETKF for ex, but we have to at least colocate to be able to use the variational application.

I could work on this Friday @travissluka if that helps.

**Comment by guillaumevernieres** [comment]
I meant to start working on this last Friday, but I got distracted by other things. I should be able to find time to do that work this week @travissluka , unless you've already started. Let me know.

**Comment by travissluka** [comment]
nope , i haven't. When you go to start working on it, just try to remember to change the "AOP22 Release Workspace" Pipeline in the upper right to "in progress"... assuming you have zenhub

**Comment by guillaumevernieres** [comment]
@travissluka , that's what I have in mind for the variational applications:
![image](https://user-images.githubusercontent.com/14031856/220496622-7592deab-721c-4339-a5aa-99899800ad92.png)

I could make the  "stencil interpolation" optional, since it might not be needed for the LETKF?
