### ISSUE TITLE
fix ewok files for running 3dvar

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#855]
## Description
the `mom6-3dvar` experiments don't run, the ewok files in soca need to be updated.

* [x] update yaml files in soca repo (https://github.com/JCSDA-internal/soca/pull/856)
* [x] update the static files 
* [x] update ewok experiment file (https://github.com/JCSDA-internal/ewok/pull/611)
* [x] Need this too: https://github.com/JCSDA-internal/soca/pull/857

**Comment by travissluka** [comment]
@climbfuji There is a small change in the format of bump files apparently, so I need the static files for soca to be updated. I have the updated files on orion:

from: `/work2/noaa/da/tsluka/skylab/TMP_STATIC/soca/025deg/bump` 
to: `/work/noaa/da/role-da/static/skylab-4.0.0/soca/025deg/bump`

**Comment by travissluka** [comment]
@climbfuji I just updated the paths in the above comment to the correct paths... oops

**Comment by climbfuji** [comment]
Paths are now ok? Should I run
```
rsync --delete -av /work2/noaa/da/tsluka/skylab/TMP_STATIC/soca/025deg/bump/ /work/noaa/da/role-da/static/skylab-4.0.0/soca/025deg/bump/
```
???

**Comment by travissluka** [comment]
@climbfuji yes that looks correct. I'll run an ewok exp after you do that to verify all is well

**Comment by climbfuji** [comment]
Done

**Comment by climbfuji** [comment]
Data updated in `static/skylab-4.0.0/soca/025deg/bump/` on:
- [x] Orion: `/work/noaa/da/role-da/static/skylab-4.0.0/soca/025deg/bump/`
- [x] Discover: `/discover/nobackup/projects/jcsda/s2127/static/skylab-4.0.0/soca/025deg/bump/`
- [x] S4: `/data/prod/jedi/static/skylab-4.0.0/soca/025deg/bump/`
- [x] Cheyenne: `/glade/p/mmm/jedipara/static/skylab-4.0.0/soca/025deg/bump/`
- [x] AWS S3 us-east-1: `s3://r2d2.static.s3/skylab-4.0.0/soca/025deg/bump/`
- [x] AWS S3 us-east-2: `s3://r2d2.static.s3.us-east-2/skylab-4.0.0/soca/025deg/bump/`
- [x] AWS Parallelcluster (us-east-2, USAF account): `/mnt/experiments-efs/skylab-v4/soca/025deg/bump/`
- [x] AWS Single Node Red Hat 8 AMI:

**Comment by climbfuji** [comment]
@travissluka Data everywhere except on the yet-to-be-created Single Node Red Hat 8 AMI. Will keep the issue open until that's done.

**Comment by climbfuji** [comment]
Link tot he rsync command for AWS Single Node Red Hat 8 AMI: https://github.com/JCSDA-internal/ewok/issues/570#issuecomment-1480483869

**Comment by climbfuji** [comment]
The data is now on the EC2 instance from which I will create the Red Hat 8 AMI for the Skylab v4 release.

**Comment by climbfuji** [comment]
oops, just saw that https://github.com/JCSDA-internal/ewok/pull/611 isn't merged yet, reopening.
