### ISSUE TITLE
Add the EDA app to SOCA

### ISSUE THREAD

**Issue by kbhargava** [JCSDA-internal/soca#859]
## Description

Add the capability of doing EDA for SOCA following the [fv3-jedi example here](https://github.com/JCSDA-internal/fv3-jedi/tree/develop/test/testinput). There is  closed draft [PR#683](https://github.com/JCSDA-internal/soca/pull/683) that I would reopen and continue my work there. 
The story points for this would be:

- [ ] Add the EDA app
- [ ] Add the ctest and related yaml
- [ ] Add related yamls to soca-science config folder (more of a soca-science issue I guess but adding here as well for completeness )

@travissluka I will wait for you to assign it to appropriate epic/sprint/ etc.

**Comment by travissluka** [comment]
@kbhargava do we still care about this?

**Comment by kbhargava** [comment]
> @kbhargava do we still care about this?

Naah!! Not at the moment, may be some day when we cycle skylab.
