### ISSUE TITLE
Update to Anna's branch on the refactoring of geovals

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#86]
... @travissluka , @aerorahul : The last oops merge is breaking soca, @shlyaeva pushed a branch with a fix, I'm going through it right now, merging our latest work and hopefully issue a pr later today.

**Comment by shlyaeva** [comment]
the ufo feature/refactor_geovals shouldn't be breaking anything (hasn't been merged yet).
It's probably Yannick's yesterday's update, see changes that need to be done in the model traits here: https://github.com/JCSDA/fv3-jedi/pull/109/files

although I'd appreciate getting ready for feature/refactor_geovals: ufo is changing rapidly these days, and I'd like to avoid merging develop into that branch and resolving conflicts every day :)

**Comment by travissluka** [comment]
closed by PR #87
