### ISSUE TITLE
Test regional configuration hybrid-EDA/EnVAR with low ensemble count

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#870]
Do a test of the Hybrid EDA/EnVAR 

Tasks:
* [x] Run EDA-EnVAR for the entire test period with 5 ensemble members
* [x] Do the same with LETKF-EnVAR

Optional tasks:
* [ ] Evaluate the spread and tune settings

**Comment by kbhargava** [comment]
The EDA-EnVar experiments  with 5 ensemble members have been run. I also tested setting the weights to 80% for ensemble. Including the time-series plot for mean absolute error |obs-bkg| below for SST and ADT. STill working on more detailed plots using PADME. 
![seaSurfaceTemperature_['sst_viirs_npp_l3u_so025'].png](https://images.zenhubusercontent.com/60427247a45e7bdd38303999/93ac7f84-05a3-4e4c-9669-d227b5734354)

**Comment by kbhargava** [comment]
Forgot to add the ADT plot:

![absoluteDynamicTopography_['adt_3a_egm2008', 'adt_3b_egm2008', 'adt_c2_egm2008', 'adt_j3_egm2008', 'adt_sa_egm2008'].png](https://images.zenhubusercontent.com/60427247a45e7bdd38303999/0bbbb353-f437-4e72-a903-ed95a1bd1861)

**Comment by travissluka** [comment]
@kbhargava I'm closing this, as it's "working" now. The other tuning we had in mind will be handled in other issues (e.g. https://github.com/JCSDA-internal/soca-science/issues/588)
