### ISSUE TITLE
Get SOCA working with FMS 2022.04

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#872]
instead of `fms@release-jcsda` use `fms@2022.04`

~I'm *assuming* that updating to the latest mom6 will fix our compile issues.
If things get difficult because too much has changed with the MOM6 interface, I'll just comment out all the model "run" code.... not like we use it in the real world anyway.~

**Comment by climbfuji** [comment]
Do you want to try with the MOM6 used in the ufs-weather-model branch that is currently in use in ufs-bundle?

https://github.com/climbfuji/ufs-weather-model/tree/feature/consolidate_dom_update_20221114

It's this one: https://github.com/climbfuji/MOM6/tree/2705cf26eafc3fbbb2821c4dd1c7b195f6e8a810

**Comment by climbfuji** [comment]
If you get this to work we are also one step closer of merging ufs-related code changes back into the authoritative repositories.

**Comment by travissluka** [comment]
@climbfuji, @shlyaeva FMS2022.04 will not work for us.

It seems that the changes to the halo adjoint code were never merged upstream (see diff [here](https://github.com/NOAA-GFDL/FMS/commit/f3022f529c68594f14d070f8ccea880317bcf6b5#diff-3063d88097289c58ca7196d7f5897c12cbcd01e6f3a888d01f01de4da0133473)  for the file `mpp/include/mpp_do_update_ad.h`). I have absolutely no idea what those changes do, so I don't feel comfortable being the one to open any PRs. Tagging @danholdaway since I see your name attached to the commits for those changes in the jcsda fork. (FYI @guillaumevernieres )

**Comment by climbfuji** [comment]
Are the changes in `mpp/include/mpp_do_update_ad.h` alone enough or do you need changes in any of the other files?

Do we have a sense of how difficult it will be to get the `mpp/include/mpp_do_update_ad.h` merged into the authoritative repository?

**Comment by travissluka** [comment]
@climbfuji I'm trying to test now to see if that one file is all that needs to be changed (at least FMS2022.04 compiles if you just swap out that one file) :crossed_fingers:

**Comment by travissluka** [comment]
@climbfuji everything works with fms2022.04 if just `mpp/include/mpp_do_update_ad.h` is replaced with the version thats in the jcsda fork 🎉 

Looking at that file on GFDL's `main`, It looks like that file hasnt really been touched in a long time, so a PR should hopefully be painless. If we can find someone who knows what those changes were for. @jkbk2004 I was told you might know something about what those changes to the halo adjoint code were for

**Comment by climbfuji** [comment]
Maybe @aerorahul knows

**Comment by danholdaway** [comment]
That file handles the adjoint version of the halo filling. Needed by fv3 and mom6 adjoints. Even though there isn't a MOM6 adjoint I remember that some changes were added at some point to support things in soca. Probably @guillaumevernieres remembers why soca needed adjoint changes in fms. Something about variable transforms or adjoint interpolation where there's a mask? Since fv3-jedi is/was using that same version of FMS with `mpp/include/mpp_do_update_ad.h` I presume there wont be any impact but it would be evident from running the fv3-jedi tests if there was an issue.

**Comment by travissluka** [comment]
@danholdaway you're right that soca needs it for both the adjoint interpolation and one of the variable changes `HorizFilt`. If the FMS changes are indeed needed because of masked grids, then that would make sense with the weird results I was seeing (halo adjoint was more wrong with the more land there was on a PE)

**Comment by guillaumevernieres** [comment]
I certainly remember hitting a brick wall when realizing that the adjoint of the halo used by mom6 isn't the same as the one used by fv3 ... @jkbk2004 came to the rescue a few years ago and coded it for us. Thanks again :) @jkbk2004 !

**Comment by jkbk2004** [comment]
If an update is needed on the gfdl repo, we are trying to move to fms-2023.01. Should we consider to coordinate with gfdl to combine this feature to next release of fms-2023.02?

**Comment by climbfuji** [comment]
I think that's possible, yes. We'll want to stay in sync with the version that the ufs-weather-model uses, and we can't add code changes on top of an old release anyway.

**Comment by travissluka** [comment]
@jkbk2004 Since you're the one familiar with the changes, is there any chance I could convince you to open up a PR to the upstream GFDL repo with the changes you did in this file https://github.com/JCSDA/FMS/blob/release-stable/mpp/include/mpp_do_update_ad.h? Otherwise, we can open the PR so long as you can chime in with comments on what it is you did

**Comment by jkbk2004** [comment]
@travissluka Sorry for being slow.  Completely tied with hera resource issue. I created https://github.com/NOAA-GFDL/FMS/issues/1222. My intention is to see if we need to perform some FMS unit test of validation to make things easier for gfdl side.

**Comment by jkbk2004** [comment]
@travissluka jcsda fork is quite behind. If we just need to update mpp_do_update_ad.h, I may go ahead to create a pr from fresh fork branch on my side, right?

**Comment by travissluka** [comment]
> @travissluka jcsda fork is quite behind. If we just need to update mpp_do_update_ad.h, I may go ahead to create a pr from fresh fork branch on my side, right?

Yes please do that. I'll see if things compile and work on our side for SOCA once you do that.

**Comment by climbfuji** [comment]
> > @travissluka jcsda fork is quite behind. If we just need to update mpp_do_update_ad.h, I may go ahead to create a pr from fresh fork branch on my side, right?
> 
> Yes please do that. I'll see if things compile and work on our side for SOCA once you do that.

We'll also test with JEDI-UFS and JEDI-FV3 once we have the PR - many thanks for doing this.

**Comment by jkbk2004** [comment]
It may need some update inside the mpp ad routine. But we can continue to follow up with the pr https://github.com/NOAA-GFDL/FMS/pull/1225

**Comment by travissluka** [comment]
fixed by https://github.com/JCSDA-internal/soca/pull/1043
