### ISSUE TITLE
Add an option to use a vanilla version of the vertical convolution

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#884]
## Description
When I coded that thing eons ago, it was meant to be simple and based on layer thicknesses as a basis for decorrelation length scale. Not great, but good enough as part of a static B. We need that simple feature back in. It's also too easy to trip over yourself while trying to configure the parameters of that change of variable! 

~Also, I think there's a bug somewhere between lines 103-114 of [soca_vertconv_mod.F90](https://github.com/JCSDA-internal/soca/blob/develop/src/soca/LinearVariableChange/VertConv/soca_vertconv_mod.F90).~ We're seeing increment from surface temp larger at depth than at the surface, I assumed VertConv might have been the issue, but it seems to be coming from SocaError ... Which will be deprecated or transformed into something else soon, so ... ignoring the bug.

## Solution
Add a flag to exit `soca_calc_z` [here](https://github.com/JCSDA-internal/soca/blob/8fd638dcdf034bebaf855c0b1fc1e731150d7488/src/soca/LinearVariableChange/VertConv/soca_vertconv_mod.F90#L103).

## Related to
- [soca-science/578](https://github.com/JCSDA-internal/soca-science/issues/578)

**Comment by travissluka** [comment]
> SocaError ... Which will be deprecated or transformed into something else soon, so ... ignoring the bug.

@guillaumevernieres I have that slated for removal next quarter!
