### ISSUE TITLE
Adapt to newer MOM6 used in UFS

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#886]
## Description
Our current version of MOM6 is ancient. We need to make changes to use the newer version of MOM6 used by the UFS bundle

My initial look at this resulted in segfaults when trying to initialize SOCA, I need to figure out why.

**Comment by symoore90** [comment]
Hey @travissluka , is there an epic you can attach this issue to?

**Comment by travissluka** [comment]
fixed by https://github.com/JCSDA-internal/soca/pull/1043
