### ISSUE TITLE
CS: QA/QC for ocean profile data 

### ISSUE THREAD

**Issue by hyunchul386** [JCSDA-internal/soca#90]

**Comment by travissluka** [comment]
QC issues live in UFO not SOCA

**Comment by guillaumevernieres** [comment]
@travissluka : 
Yes and no. The generic filters only require changes in the yaml files in soca, and perhaps the addition of possibly currently missing fields (I can think of a few ...). So some of the QC issues will only live in soca. @hyunchul386 , do you have something related to this issue that you want to merge?
