### ISSUE TITLE
Convergence rates with profilers

### ISSUE THREAD

**Issue by Dooruk** [JCSDA-internal/soca#909]
We noticed some discrepancies between the convergence rates with and without T/S profilers during our 3Dvar tests (RPCG minimizer, static BUMP). These are from using GDAS observations @guillaumevernieres provided. These particular plots are from low resolution setups but I observed the same behavior with higher resolution tests I conducted.

### **With T/S profile obs:**
<img width="860" alt="with_profilers" src="https://github.com/JCSDA-internal/soca/assets/38666458/567642be-4ad3-4133-974c-dc2677b2dc2d">

### **Without T/S profile obs:**
<img width="855" alt="without_profilers" src="https://github.com/JCSDA-internal/soca/assets/38666458/a88d6bb3-7c89-4ebd-8068-e24ab852dcae">

I stored some previous convergence results before the marine vert interp #874 (which I thought might be related) but this potential "issue" is still there. Is this difference expected between the surface obs and profilers?

@danholdaway

**Comment by travissluka** [comment]
@Dooruk I think this is expected, especially if you're using the unthinned profiles with 1000+ vertical levels. It's on our to-do list to get the correlated vertical errors functionality tested, which would help with convergence when dealing with the high density vertical profiles.

**Comment by guillaumevernieres** [comment]
FYI, @ShastriPaturi is adding a `sequenceNumber` metadata to the profile obs to test the DA with correlated obs errors. He might have a few files processed already @Dooruk , in case you were interested in doing some testing on your side as well.

**Comment by Dooruk** [comment]
Thanks Travis, good to know. 

Sure @guillaumevernieres, we are working on updating our observations so perhaps we could include that metadata info. Would you then need to coordinate with @danholdaway for obs file transfers?
