### ISSUE TITLE
Bug in vertical gradient computation

### ISSUE THREAD

**Issue by hyunchul386** [JCSDA-internal/soca#910]
## Description
In the calculation of dvdz in soca_utill, a change/fix is suggested 

## Solution
to change/fix denominator part for dvdz in subroutine soca_diff in ~Utils/soca_utils.F90

Current method to calculation of dvdz in subroutine soca_diff is
dvdz(ik) = (v(ik+1)-v(ik-1))/(h(ik)+0.5*h(ik+1)+h(ik-1))

Suggested change/fix is
dvdz(ik) = (v(ik+1)-v(ik-1))/(h(ik)+0.5*(h(ik+1)+h(ik-1)))

## Alternatives
or 
dvdz(ik) = (v(ik+1)-v(ik-1))/(h(ik)+0.5*h(ik+1)+0.5*h(ik-1))

**Comment by guillaumevernieres** [comment]
Thanks for finding this issue @hyunchul386 , not quite sure why you call it an "enhancement"! It's clearly a bug.

**Comment by kbhargava** [comment]
Thanks @hyunchul386 for finding this bug. Do you want to issue a PR with bugfix. If you need I can help you with it.
