### ISSUE TITLE
3D hybrid fgat with pseudo model is broken

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#915]
## Description
The 3D hybrid fgat with a pseudo model is the configuration that I use for the `soca` implementation in the global-workflow. I tested with the `3D-FGAT` and `4D-Var` cost function and it worked fine until approximately early last week (~June 20th). I'm not 100% sure of the date, I was working on other unrelated "science" issues when things started failing after rebuilding. I wasted most of my time trying to figure out what was wrong in the yaml config, but I think the issue is in `soca` and/or `oops`.  

### To Reproduce:
I'll push a branch and probably issue a draft PR that will include a test with the EMC configuration. I should have done this earlier! 

**A problem for July 5th and beyond!**

**Comment by guillaumevernieres** [comment]
@travissluka , it looks like this [PR](https://github.com/JCSDA-internal/soca/pull/898) is the culprit. I should have tested our soca implementation in the `gdasapp` before approving! 

For our soca implementation, we read mom6's history files instead of the restarts. One of the difference is the fill value where masked. The restart's masked value are 0's while the history's fill value is a large number, hard-coded in fms. 

The issue only appears when using "ensemble covariance" in B. 

Possible solution:
- It's very likely that there is a bug somewhere, related to the changes in 898. We could try to fix it, or not ...
- Set the fill value to 0, or something user defined when reading states or increments. This actually does break quite a few tests, not sure why yet.

**Comment by travissluka** [comment]
@guillaumevernieres 1) what exactly were you getting for an error? 2) can you point me to a reasonable configuration and set of input files?

This sounds like the type of bug that I'd like to figure out what the root cause is, instead of just covering it up. If the actual value of the land makes a difference then something wrong is going on. I can debug next week.

**Comment by guillaumevernieres** [comment]
Thanks @travissluka .
1) Pointers pointing to nowhere, but I think that might have been a snafu in my configuration. NaN's when using the ensemble B. That can be corrected by changing the filled values to 0, only tested at low-res. It's very possible that there are more issues at 1/4 deg. Obviously not ideal!

2) Could I add our EMC config as a ctest? That would be quite useful for me, but it would require adding a few nc files to lfs.
