### ISSUE TITLE
Replace `InsituTemperature` ufo operator with the generic vert interp (for non-linear)

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#924]
## Description
Use VADER to do the insitu/potential temperature conversion. Once that capability is added to VADER (in a separate issue) change the SOCA yaml files to use the generic vertical interpolator UFO and make sure the conversion in VADER is working as intended.

* [x] change the soca ctests to use VADER/generic-vert-interp
* [x] Compare the two methods (variable conversion in VADER vs in UFO) and make sure they are roughly equivalent.
* [ ] ~~create PRs for similar changes in Skylab and soca-science~~ (will do this after linear variable change is added)

**Comment by travissluka** [comment]
@Dooruk when it comes time to test, I _think_ all you need to do is modify this area of the soca ctests https://github.com/JCSDA-internal/soca/blob/cefd6ab09ef66b94fb21d2950c2934848fe3fa70/test/testinput/hofx_3d.yml#L91 so that the insitu obs, instead of using a composite operator, uses a single `VertInterp` operator that has both the temperature and salinity variables.  `waterTemperature` will not be available from SOCA, so it will ask VADER for the conversion.

I'm sure I'm missing some details, but I guess we'll find out when we go to run it

**Comment by Dooruk** [comment]
Sounds too good to be true but sure, I can check.

**Comment by Dooruk** [comment]
This is what I've been testing with, I tried combinations of commented out parts. I'm receiving `Unable to find field metadata for: ocean_temperature` error. Am I doing something obviously wrong?


```
  - obs space:
      name: InsituTS
      obsdataout:
        engine:
          type: H5File
          obsfile: data_generated/hofx_3d/prof.hofx_3d.nc
      obsdatain:
        engine:
          type: H5File
          obsfile: data_static/obs/prof.nc
      simulated variables: [waterTemperature]
    obs operator:
      name: VertInterp
      observation alias file: testinput/obsop_name_map.yml
      # vertical coordinate: sea_water_depth
      # observation vertical coordinate: depth
      # observation vertical coordinate group: MetaData
      # interpolation method: linear
```

**Comment by Dooruk** [comment]
Maybe this following section is relevant?

https://github.com/JCSDA-internal/fv3-jedi/blob/30c90776de4190c7d9ab0dd03621e501c962bfbe/src/fv3jedi/VariableChange/VariableChange.cc#L26

**Comment by Dooruk** [comment]
I looked further into the variable change header file in fv3 and there is a part that includes fieldsmetadata.h for fv3-jedi.

https://github.com/JCSDA-internal/fv3-jedi/blob/30c90776de4190c7d9ab0dd03621e501c962bfbe/src/fv3jedi/VariableChange/VariableChange.h#L25

Does this mean we can't follow the same approach for `SOCA`? I guess the closest thing is the `Fields` folder? @guillaumevernieres 

@danholdaway is off this week so I can't ask him 😞

**Comment by travissluka** [comment]
@Dooruk we do have fields metadata that I mainly styled off of what Dan had done for fv3. I should have time tomorrow to checkout your branches and see if I can figure out what is going on.

**Comment by Dooruk** [comment]
Sounds good, maybe fv3 has a different approach. I see that they have a `Vadercookbook.h` file in their `VariableChange` which is connected to a bool fv3/vader wrapper in the base `VariableChange` class.
