### ISSUE TITLE
Add ctest for a hybrid 4DEnVAR to SOCA

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#929]
## Description
Self-explanatory. Add a ctest to exercise a 4DEnVAR in SOCA with hybrid covariance.

Note that there is supposedly a bug with the hybrid 4D covariance. So answers will change at some point when that is fixed.

**Comment by travissluka** [comment]
4denvar was easy enough to set up in our ctests. But...

 Quick question @shlyaeva, is there a way to save the 4D increments with 4denvar? I didn't see any test yamls with an example. My naive attempt at setting `variational.iterations[].online diagnostics.increment` is not working because `Assertion failed: increment_.is_3d() in write`

**Comment by shlyaeva** [comment]
4denvar is a bit in flux right now. Tagging @ytremolet on writing 4D increments.
