### ISSUE TITLE
MPI_Finalize issue with model

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#93]
`test_soca_model` and `test_soca_linearmodel` both "pass" except that the programs terminate with the error

```
10: *** The MPI_Comm_f2c() function was called after MPI_FINALIZE was invoked.
10: *** This is disallowed by the MPI standard.
10: *** Your MPI job will now abort.
```

**Comment by aerorahul** [comment]
This is a persistent issue. I think the something in mpp is calling mpi_finalize which should be handled outside in the oops destructor. I can’t put a finger on it just yet.
Something about how we finalize soca.

**Comment by danholdaway** [comment]
Are you calling mpp_exit in your run destructor or anywhere else? Haven't looked in a while but I remember that I had to comment it or had similar issues. It might also depend on when mpp_init is called. If mpi isn't yet initialized mpp will set it's internal comm to comm world then when mpp_exit is called remember that it initialized mpi and thus finalize the comm (comm world). You also have to pass the comm into mpp_init or again it thinks it's initializing comm world.

**Comment by ytremolet** [comment]
In principle mpi_finalize is called from the oops Run.cc in the destructor. If you inherit from that you should not call it. If you have your own Run (not sure that's a good idea), you would need to do the same. This takes care of issues we had before with the Logger and other utilities trying to access MPI.

**Comment by aerorahul** [comment]
SOCA does not call FMS::MPP_EXIT, since that call finalizes MPI when comm is MPI_COMM_WORLD. 
COMM is not being split in SOCA, so the COMM used by MPP is MPI_COMM_WORLD.

MPP_EXIT should be called as part of soca_finalize (to clean up). But, doing so has the unintended consequence of calling MPI_Finalize. One approach would be to allow the user to choose to call MPI_Finalize in MPP_EXIT, just as MPP_INIT allows to use a passed COMM.

What do you think @guillaumevernieres?

**Comment by travissluka** [comment]
`mpp_exit()` is being called through `MOM_infra_end()` within `soca_mom6_end()`.

In an attempt to get back to clean ctests I propose I just comment out that line for now. The mom6 `solo_driver` is a bit of a mess and does a horrible job of cleaning up anyway. We can take a closer look later on how to do things cleaner.

**Comment by guillaumevernieres** [comment]
I removed the mpi_finalize call a while ago, after this was handled through oops run. @travissluka , sounds good to me.

**Comment by guillaumevernieres** [comment]
@aerorahul : Whatever works! Keeping in mind, like @travissluka said, we probably will have to revisit some of that work. It's possible that we might have to rewrite some of the "init" and "exit" routine of mom6, which might be usefull to properly split the geometry and the model ... Not now though.
