### ISSUE TITLE
4D EnVAR tests randomly fail

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#938]
The 4DEnVar and 4DHybEnVar tests randomly fail, and are causing travis CI to break.
I have the same problem on my local machine. If I rerun the tests they work. So... :man_shrugging:

**Comment by shlyaeva** [comment]
@ytremolet has also noticed qg 4DEnVar tests failing randomly in one of the CIs in oops..

**Comment by travissluka** [comment]
> @ytremolet has also noticed qg 4DEnVar tests failing randomly in one of the CIs in oops..

ah good, glad it's not just me. It seems to load in the yaml file, then starts to initialize parts of MOM then quits completely without any warnings or errors. :man_shrugging:

**Comment by ytremolet** [comment]
Yes. But it doesn't happen very often so very hard to debug.

**Comment by travissluka** [comment]
hmm, errors seem to have gone away after merging 
- https://github.com/JCSDA-internal/soca/pull/940
