### ISSUE TITLE
fgat/hofx hangs with certain observation types

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#94]
`test_soca_3dvarfgat` and `test_soca_hofx` both hang at `State<MODEL>::getValues` when `SeaSurfaceSalinity` or `ADT` observations are used. Other observation types are not causing a problem.

With enough time it eventually continues (many minutes later), but this shouldn't happen with such few observations.

**Comment by guillaumevernieres** [comment]
@travissluka : I'm looking at it right now.

**Comment by guillaumevernieres** [comment]
@travissluka : As I suspected, 0 obs seems to be the issue, I'll work on a fix.

**Comment by travissluka** [comment]
Ah good, I was considering adding a test to check that things work even if
there are no obs, I guess I accidentally did that!

**Comment by guillaumevernieres** [comment]
I've got the fix for fgat, but hofx now fails at the end right after OOPS_TRACE ObsVector::read, name = EffectiveQC
No more hanging though.

**Comment by travissluka** [comment]
Yeah, I've seen that hofx error too... separate bug

**Comment by guillaumevernieres** [comment]
A failing test is better than a hanging test ... I guess. I just noticed that 3dvar_godas is failing on gcc as well. Do you have that issue?

**Comment by travissluka** [comment]
No, the 3dvar_godas test is passing for me with gcc 7.3

**Comment by guillaumevernieres** [comment]
gcc 7.3 out of the container? Did you test with a newer singularity image? Looks like we have 7.4 now, it fails with that for me. I thought I saw it pass earlier today. 
I'll submit a simple pr only addressing fgat and hofx.

**Comment by aerorahul** [comment]
I don’t think this is a compiler related issue. Something else must be the issue.

**Comment by danholdaway** [comment]
[JCSDA/ioda#211](https://github.com/JCSDA/ioda/issues/211)

**Comment by guillaumevernieres** [comment]
Thanks @danholdaway . 
@aerorahul , I was talking about the godas_bkgerror related tests, both are failing for me.

**Comment by travissluka** [comment]
closed by PR #95
