### ISSUE TITLE
Pass Configuration to model repo interfaces 

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#945]
## Description
- see https://github.com/JCSDA-internal/oops/pull/2284 for what is needed

**Comment by guillaumevernieres** [comment]
@travissluka , "happy" to work on this if you are still under the weather. Just ping me.

**Comment by travissluka** [comment]
> @travissluka , "happy" to work on this if you are still under the weather. Just ping me. 

@guillaumevernieres Have at it, otherwise I was going to look at it tomorrow
