### ISSUE TITLE
Ice level is hardcoded in soca ciceutils

### ISSUE THREAD

**Issue by Dooruk** [JCSDA-internal/soca#969]
While using `convertstate_soca2cice` task, it is possible to change `ice_lev` within the yaml config. However, this is hard coded in the following module, so yaml `ice_lev` is not registered, and causes an issue when the `ice_level` in `iced.nc` is not 7:

https://github.com/JCSDA-internal/soca/blob/ef327de7d8f12bbc911554164a7bbdc31bf518c7/src/soca/VariableChange/Soca2Cice/soca_ciceutils_mod.F90#L27

7 might be the standard for CICE6 but I converted some of Eric Hackert's CICE4 ice restarts and they have 4 levels.

### Output:

Sad Doruk with lots of print statements

**Comment by guillaumevernieres** [comment]
That change of variable will not work with CICE4 without some( a lot?) of modifications @Dooruk .  Are you planning to make the changes for CICE4 or are you going to wait for CICE6 to be in GEOS?

**Comment by Dooruk** [comment]
This is with CICE6 output. Bin Zhao wrote a script that converts CICE4 -> CICE6 `iced.nc` restart. So I ran CICE6 for a month with that converted restart and that's what I'm inputting into SOCA. However there are 4 ice_layers in my restarts but other than that I see all the proper/required variables are there.

And I'm testing with a `540x458x50` MOM6 setup, because that's what GEOS has for CICE6 for a short while.

**Comment by guillaumevernieres** [comment]
> This is with CICE6 output. Bin Zhao wrote a script that converts CICE4 -> CICE6 `iced.nc` restart. So I ran CICE6 for a month with that converted restart and that's what I'm inputting into SOCA. However there are 4 ice_layers in my restarts but other than that I see all the proper/required variables are there.
> 
> And I'm testing with a `540x458x50` MOM6 setup, because that's what GEOS has for CICE6 for a short while.

Nice! It does look like I hard coded `ice_lev` in a few places but it shouldn't be too involve to pass the `ice_lev` from configuration down to the various constructors.
