### ISSUE TITLE
Time interpolation does not work

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/soca#980]
## Description
Time interpolation for the computation of h(x) was recently added (in oops and/or ufo) as an alternative to the default nearest neighbor when using the 3D-FGAT or 4D-VAR cost function.
To switch to the linear time interp, one should just have to add the following yaml snippet to the `obspace`: 
```yaml
get values:
  time interpolation: linear
```
However, the results are exactly the same with or without the option above.
  
### To Reproduce:
1. **do this:** Add the yaml snippet from above to the obs spaces of the 3dvarfgat ctest
3. **then that:** re-run the 3dvarfgat ctest, the results should be different 
4. **then, oops, look at the bug**: No change in the results

This was observed as well in the `soca` implementation for the `UFS`.

**Comment by guillaumevernieres** [comment]
Move along ... nothing to see here.

**Comment by travissluka** [comment]
i'm just now seeing this 🤔 I'm not moving along

**Comment by guillaumevernieres** [comment]
> i'm just now seeing this 🤔 I'm not moving along

Shoo! Shoo! Shoo!

**Comment by guillaumevernieres** [comment]
I forgot what I did wrong but we sorted it out. Katie did some comparison a while back ... I don't remember if we shared the results.

**Comment by frolovsa** [comment]
we are having similar issues with @weihuang-jedi

**Comment by guillaumevernieres** [comment]
> we are having similar issues with @weihuang-jedi

The comparisons that we did looked reasonable @frolovsa . What issues are you guys having?

**Comment by shlyaeva** [comment]
If there are any issues with time interpolation, please report in oops issues. As far as I know it should work correctly for all applications. The only exception is 4DEnVar with time parallelization where it's not implemented (one should use 4DEnVar without time parallelization if they would like to use time interpolation).

**Comment by guillaumevernieres** [comment]
> If there are any issues with time interpolation, please report in oops issues. As far as I know it should work correctly for all applications. The only exception is 4DEnVar with time parallelization where it's not implemented (one should use 4DEnVar without time parallelization if they would like to use time interpolation).

No issues @shlyaeva , at least with the 3dvar-fgat. I'm not sure what @frolovsa is talking about, care to elaborate Sergey ?
