### ISSUE TITLE
soca enshofx test bug? each ensemble member tries to write to the same file independently

### ISSUE THREAD

**Issue by climbfuji** [JCSDA-internal/soca#981]
## Description

I am going down a rabbit hole ...in https://github.com/JCSDA-internal/jedi-bundle/pull/76, I am reporting repeated test failures for only one test, `test_soca_enshofx`. I added print statements to the code that throws the error described in the PR (`FATAL: NETCDF ERROR: Permission denied File=./Vertical_coordinate.nc`):
```
vi ../../../../../jedi-bundle-no-gfdl-forks/mom6/src/framework/MOM_io.F90
# 
...
  write(0,*) "CREATING FILE " // trim(filename) // " with: ", domain_set, num_PEs(), thread, SINGLE_FILE, one_file
  if (one_file) then
    call open_file(IO_handle, filename, OVERWRITE_FILE, threading=thread)
  else
    call open_file(IO_handle, filename, OVERWRITE_FILE, MOM_domain=Domain)
  endif
  write(0,*) "CREATED FILE " // trim(filename)
...
#
I_MPI_FABRICS="shm" /opt/intel/mpi/2021.6.0/bin/mpiexec "-n" "6" "/mnt/experiments-efs/dom.heinzeller/jedi-bundle-fms-2023p03/build-no-gfdl-forks-debug/bin/soca_enshofx.x" "testinput/enshofx.yml"
...
 CREATING FILE ./Vertical_coordinate with:  F           1         400
         400 T
 CREATING FILE ./Vertical_coordinate with:  F           1         400
         400 T
 CREATING FILE ./Vertical_coordinate with:  F           1         400
         400 T
 CREATED FILE ./Vertical_coordinate
 FATAL: NETCDF ERROR: Permission denied File=./Vertical_coordinate.nc
```
As we can see, multiple processes (each member) is trying to create and write to the file, but since it's only one PE per ensemble member it does so serially. If I set the environment variable `HDF5_USE_FILE_LOCKING=FALSE` before running the test, then the test passes.

My question to @travissluka @shlyaeva @ytremolet is: I think we sometimes set this env variable (e.g. https://github.com/JCSDA-internal/jedi-tools/blob/develop/buildscripts/compiling/run_intel_build_S4.sh where it doesn't make sense, because this is for a compile-jedi jobcard), but so far we haven't had to set it on aws-pcluster. It makes sense to disable file locking if we can guarantee that we only read from the same file with multiple independent processes, but writing to it seems rather dangerous?

### To Reproduce:

See above

## Additional context
n/a

## Output

See above

**Comment by travissluka** [comment]
Ah, nice find, that test has been flaky for a very long time and I never figured out why! I guess I didn't realize that enshofx was creating multiple instances of mom6 in parallel, so it makes sense now.

Yes, mom6 likes to write out a bunch of files when it runs, files we don't care about. Possible solutions:
1) I'll look through the mom6 config files and see if I can turn off as much unnecessary output as I can
2) if enshofx is running the ensemble members in parallel, is there any way to make it serial
3) we never actually use enshofx, delete the test??

**Comment by shlyaeva** [comment]
2. No, there's no way to make it serial -- EnsApplication splits communicator and runs several HofX applications in parallel.
3. 🤷‍♀️  makes sense to me..

**Comment by guillaumevernieres** [comment]
:bomb: 3

**Comment by travissluka** [comment]
I'm going with option 3. There is no way to disable writing those files without changing MOM code, which I really don't feel like doing right now. So, for now, I'm deleting the enshofx test,  we don't use it.

When the day comes when we use MOM6 in core with JEDI, we'll have to take a closer look at what output files mom is trying to create and do some MOM PRs to stop those (there are a few other NC output files MOM always tries to create.)
