### ISSUE TITLE
test_soca_increment fails

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/soca#99]
`test_soca_increment` fails at `testIncrementInterpAD` due to norms outside the tolerance, but only when the ice variables (`sea_ice_category_area_fraction` and `sea_ice_category_thickness`) are enabled in the `GeoVaLs` of the `increment_test.yml` file.

This only occurs for me when inside the container. Outside, compiling with GCC 7.3, it works fine.

**Comment by travissluka** [comment]
... in the container it is passing in debug mode, but not in release

**Comment by guillaumevernieres** [comment]
@travissluka : Looking into it.

**Comment by travissluka** [comment]
@guillaumevernieres it works with the ice variables if the number of lat/lon locations doesn't exceed 5

**Comment by guillaumevernieres** [comment]
@travissluka it doesn't seem to be related to the ice variable or the number of obs, but to the location of the obs. Obs on land or too close to land are failing the adjoint test. I don't care too much about land obs, but the fact that is fails when close to land bothers me. Looking at it right now.

**Comment by guillaumevernieres** [comment]
The increment test is passing with the current locations that are in the yml file. Adding obs that are on or close to land seem to make the adjoint test fail ... I have not figured out why (nor do I really want to, these obs will be qc'ed out). Is the test passing for you @aerorahul & @travissluka? 
What annoys me is that adding a derived data type to the current field data type is sufficient to make the increment test fail. There is something fishy with the linked list I think, I moved the linked list implementation to the the interface module, but I get the same issue.

**Comment by travissluka** [comment]
@guillaumevernieres I'm still getting failures inside the container, release mode only, not debug. The failure occurs randomly,  running the test 10 times in a row it passed for 2 of those times.

**Comment by travissluka** [comment]
also, when running under valgrind, debug mode is clean, but release starts complaining  after getting to `testIncrementInterpAD` about conditional statements within ufo and bump depending on uninitialized values... which would explain why it is randomly failing for me.

**Comment by guillaumevernieres** [comment]
@travissluka , I just restarted the container, the first time I run the increment test, it fails, all the subsequent calls are passing. 
It passes all the time with intel on theia.

**Comment by guillaumevernieres** [comment]
Glad to know debug is valgrind clean, it wasn't the last time I checked ... Progress I guess.

**Comment by travissluka** [comment]
feel free to put this on the backburner for now and move on to something
else... maybe someone will push something to UFO/BUMP in the future to
magically fix it.

I might go on a valgrind error squashing adventure the next time i'm
feeling especially sadistic.

**Comment by travissluka** [comment]
@guillaumevernieres after a fair amount of valgrinding I found the cause, `missing_value` in geovals was not being initialized correctly in the geovals copy constructor. I'll be pushing a bugfix to UFO shortly.

**Comment by guillaumevernieres** [comment]
@travissluka  nice! I wonder if that will fix the current issue that I have when adding a data type to the field ... Looking forward to trying out your fix.

**Comment by travissluka** [comment]
fixed with UFO PR
